### ISSUE TITLE
Use script hash to visit polyjuice creator page

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#1000]

**Comment by Keith-CY** [comment]
Now there're `eth addr reg account`, `meta contract account`, `eth user account`, `polyjuice account`, `polyjuice creator account`, `udt account`

Only `polyjuice creator account` is directed by `script hash`? @zmcNotafraid

**Comment by zmcNotafraid** [comment]
> directed

Only eth_user account and polyjuice account have eth_address, others only have script_hash

**Comment by Keith-CY** [comment]
> > directed
> 
> Only eth_user account and polyjuice account have eth_address, others only have script_hash

Got it

**Comment by Keith-CY** [comment]
Fixed by https://github.com/Magickbase/godwoken-explorer-ui/commit/074099f3e94c8cb8f6546a09a865de7e932d29a4, as page https://v1.testnet.gwscan.com/tx/0xae87c8b36432a05d9fd886a0c0bdf43926ae3276c44d94b43ac439257f2d46b4

Please have a review @Dawn-githup

**Comment by Dawn-githup** [comment]
![image](https://user-images.githubusercontent.com/77844990/191454397-23d27f2d-d542-46c7-a2b7-f92f2796ba61.png)

> need to supplement the transactions list?

**Comment by Keith-CY** [comment]
> ![image](https://user-images.githubusercontent.com/77844990/191454397-23d27f2d-d542-46c7-a2b7-f92f2796ba61.png)
> 
> > need to supplement the transactions list?

The tx list is missing because it was designed to show `eth/polyjuice txs`, filtered by `eth address`. However polyjuice creator is not an account of `polyjuice` so no records are returned

Will be handled with another issue https://github.com/Magickbase/godwoken_explorer/issues/1003

**Comment by Keith-CY** [comment]
Please add an address of polyjuice account for debugging @zmcNotafraid

**Comment by zmcNotafraid** [comment]
> Please add an address of polyjuice account for debugging @zmcNotafraid

polyjuice_account: 0xa20aa99c6b212670f98eda6fd45d06596060f422
polyjuice creator account:  0x829cc5785a4d8ac642ede32cb3cb5cb9dc389d5892f2fc2afc760691445be194
