### ISSUE TITLE
Show 'loading' status after transaction of token approval revocation is sent

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#1011]
Token approval won't be really revoked immediately after the revocation transaction is submitted because the transaction to revoke has to be packaged into a block to take effect.

And now packaging a transaction might take 1 minute at most, so in the worst case an approval record will still be listed for 1 minute after user's action.

The submission could be cached in front-end and `loading` statue could be introduced after the transaction is sent successfully but not packaged into a block.

Could you add a design of `loading revocation` in the approval list https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=4131%3A20601 @Kirl70 

And any question about the `loading` strategy? @qiweiii @FrederLu 

Note: we'll add this feature after the function of the approval list is published because it's not a serious issue.

**Comment by Kirl70** [comment]
The design has been adjusted:

https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=4131%3A20601
<img width="873" alt="image" src="https://user-images.githubusercontent.com/106060898/191935013-2d9453fd-359e-4d61-be77-8e861dc3bae5.png">

The undo button changes to a non-clickable state during the undo process, and the text icon changes, the loading icon rotates in a loop, and a prompt appears after a successful undo.

**Comment by FrederLu** [comment]
1、Need a tooltip when hovering over the `loading revocation` button?
2、`loading revocation` is a transitional state. When the information is successfully packaged, the record will disappear, right?

**Comment by Keith-CY** [comment]
> 1、Need a tooltip when hovering over the `loading revocation` button? 
> 2、`loading revocation` is a transitional state. When the information is successfully packaged, the record will disappear, right?

For the point 2, yes, when the transaction is mined into a block and the block is synchronized by our server, the record will disappear.

**Comment by Kirl70** [comment]
> 1、Need a tooltip when hovering over the `loading revocation` button? 2、`loading revocation` is a transitional state. When the information is successfully packaged, the record will disappear, right?

Hovering over the load button does not require a hint message, as the button already has hint text inside.
