### ISSUE TITLE
Unit test and e2e test in godwoken_explorer_ui.

### ISSUE THREAD

**Issue by JeffreyMa597** [Magickbase/godwoken_explorer#1020]
Because Cypress unit testing is relatively immature, it encountered a lot of configuration issues when integrated into our project. Ultimately, we decided to use Jest and react-test-library as our unit testing tools.
The configuration of Jest has been integrated into our project and now can be used normally after testing.
The unit test cases need to be written in the `tests`  folder at the root directory, which is separate from the Cypress E2E test cases. 

E2E: Cypress
Unit Test: Jest/React-test-library
<img width="300" alt="image" src="https://user-images.githubusercontent.com/22511289/192681178-a781b628-b38b-4c15-8863-b5beaac9afd8.png">

Thank you.

**Comment by Keith-CY** [comment]
`Jest` was introduced by PR https://github.com/Magickbase/godwoken-explorer-ui/pull/576
