### ISSUE TITLE
Approved ERC721 transactions cannot be revoked.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#1030]
Method：Approve
https://v1.testnet.gwscan.com/tx/0x50150e27fab811b4046cba02c0da302a2938f487c2fea56d57c3d8baf158477b
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/25676576/193244504-7142f215-e63c-4823-8329-1f7a94ef48ca.png">

---
Method：SetApprovalForAll
https://v1.testnet.gwscan.com/tx/0x69470f023c076e475bfba77e1a9e5c493b967351f767fcab3ebbef04b80924df
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/25676576/193244585-c7206f7a-ceab-4573-94b7-94c8afa79247.png">

There was a problem with the method used when revoking, which resulted in the approve ERC721 transaction not being revoked.

**Comment by qiweiii** [comment]
Maybe this is related to backend

**Comment by qiweiii** [comment]
@Keith-CY after discussing with @FrederLu, for erc721, we need to use `approve` method to revoke if it's `Approved Type` is `approve`, so need to add this case in frontend.

**Comment by Keith-CY** [comment]
> @Keith-CY after discussing with @FrederLu, for erc721, we need to use `approve` method to revoke if it's `Approved Type` is `approve`, so need to add this case in frontend.

Sure, effective revocations are as follows:

Revoke erc20 approval: `approve(spender, 0)` to set `spender`'s allowance to 0
Revoke erc721 approval: `approve(zero address, token id)` to set spender of `token_id` an inaccessible address
Revoke erc721 approval for all: `setApprovalForAll(operator, false)`
Revoke erc1155 approval for all: `setApprovalForAll(operator, false)`

**Comment by qiweiii** [comment]
@zmcNotafraid we need a `tokenId` from `token_approvals` query inorder to revoke a erc721 token using `approve` method, please refer to: https://github.com/Magickbase/godwoken-explorer-ui/pull/610#issuecomment-1272498146
