### ISSUE TITLE
Token name is missing in Erc721Erc1155CommonUserToken

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#1034]
`udt: UDT` was returned in query `user_erc721_assets` before, but now it's been changed to `udt: Erc721Erc1155CommonUserToken` thus response turns into

```
type Erc721UserToken {
  address_hash: HashAddress
  counts: Decimal
  token_contract_address_hash: HashAddress
  token_id: Decimal
  token_type: EthType
  udt: Erc721Erc1155CommonUserToken
  value: Decimal
}
type Erc721Erc1155CommonUserToken {
  address_hash: HashAddress
  counts: Decimal
  token_contract_address_hash: HashAddress
  token_id: Decimal
  token_type: EthType
  value: Decimal
}
```

Token name and cover returned along with `UDT` not are missing and online pages are broken. It's fixed by removing `token name` from the page temporarily, but still need a hotfix to deliver token name on the page of user's erc 721 assets.

Ref: https://github.com/Magickbase/godwoken_explorer/blob/godwoken-v1-mainnet-prod/docs/schema.graphql#L495-L502

**Comment by Keith-CY** [comment]
It was introduced by the PR of adding ERC 1155(https://github.com/Magickbase/godwoken_explorer/pull/986/files#diff-4ad1e8114c1d0323ac39fb316416d16d150eaf3c7555ef1a785414cd7add85a6R590-R613). The PR has breaking changes on API of ERC 721 but is not mentioned in the message, and test cases should be added to guarantee every field required in PRD issue(https://github.com/Magickbase/godwoken_explorer/issues/689#issuecomment-1197710486) is returned.

**Comment by FrederLu** [comment]
<img width="390" alt="image" src="https://user-images.githubusercontent.com/25676576/194695040-b930e97b-5a47-4545-89fb-a7c102f869b9.png">
The id and name field information has been improved, and the interface has been verified.

**Comment by Naupio** [comment]
@FrederLu  testnet-prod was deployed

**Comment by FrederLu** [comment]
Verified.
