### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#1039]
1. the coverage is not revealed @zmcNotafraid 
![image](https://user-images.githubusercontent.com/7271329/194691842-6e8e8e7c-e715-43ab-9b64-2d4b99f59ef4.png)

2. API docs(https://magickbase.github.io/gwscan-graphql-doc/) could be appended @Naupio

**Comment by zmcNotafraid** [comment]
FIrst bug has been fixed.

**Comment by Naupio** [comment]
link: #1099
