### ISSUE TITLE
Some issues on contract account page

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#1067]
https://v1.testnet.gwscan.com/account/0xe05d380839f32bc12fb690aa6fe26b00bd982613?tab=transactions

https://user-images.githubusercontent.com/7271329/194927046-d769da28-c1c2-49df-b6af-adbaf153e38f.mov

1. Warning of switching to the correct network is unnecessary on visiting the page since the user may not call the method. The warning should be popped up when the user is visiting the `read/write` tabs and the network is changed to an unknown one.

2. I18n is incorrect

**Comment by Keith-CY** [comment]
When all connected wallets are removed, the `switch-to-network` error appears, it's not the correct message

**Comment by Keith-CY** [comment]
Call a method when network is incorrect, show ask MetaMask to connect to the correct one before sign the transaction.

Now it will send the transaction to the incorrect chain
![image](https://user-images.githubusercontent.com/7271329/194927758-f01bac00-9057-4b32-a083-bf4354554c8f.png)

**Comment by Keith-CY** [comment]
> Call a method when network is incorrect, show ask MetaMask to connect to the correct one before sign the transaction.
> 
> Now it will send the transaction to the incorrect chain ![image](https://user-images.githubusercontent.com/7271329/194927758-f01bac00-9057-4b32-a083-bf4354554c8f.png)

This one is dangerous so I added a simple patch https://github.com/Magickbase/godwoken-explorer-ui/commit/63d32397ca1bf215a09fa71f516ad8f56183ef76#diff-b8504e11f0446394f8f9c7920bccc4e9aa1a850d7c4199c8e6052aa25c289da6R128-R135

**Comment by Keith-CY** [comment]
https://user-images.githubusercontent.com/7271329/194936579-0dab6392-4eaa-4b73-9843-1d947ab7e6fd.mov

Connecting to an incorrect network is not detected

**Comment by Keith-CY** [comment]
The new features

> [#​940](https://togithub.com/wagmi-dev/wagmi/pull/940) [b6cb8f4](https://togithub.com/wagmi-dev/wagmi/commit/b6cb8f4cd15eb13073bc7e9ecb4bfa2c261c0663) Thanks [@​jxom](https://togithub.com/jxom)! - Breaking: usePrepareContractWrite now throws when a chainId is specified and the end-user is on a different chain id (the wrong network).
> [#​940](https://togithub.com/wagmi-dev/wagmi/pull/940) [b6cb8f4](https://togithub.com/wagmi-dev/wagmi/commit/b6cb8f4cd15eb13073bc7e9ecb4bfa2c261c0663) Thanks [@​jxom](https://togithub.com/jxom)! - Breaking: usePrepareSendTransaction now throws when a chainId is specified and the end-user is on a different chain id (the wrong network).
> [#​940](https://togithub.com/wagmi-dev/wagmi/pull/940) [b6cb8f4](https://togithub.com/wagmi-dev/wagmi/commit/b6cb8f4cd15eb13073bc7e9ecb4bfa2c261c0663) Thanks [@​jxom](https://togithub.com/jxom)! - The useSigner hook now accepts an optional chainId to use for signer initialization as an argument.

introduced by https://github.com/Magickbase/godwoken-explorer-ui/pull/664 could also be used to prevent the mismatch between the target chain id and the current chain id mentioned in https://github.com/Magickbase/godwoken_explorer/issues/1067#issuecomment-1273656489 @qiweiii

**Comment by FrederLu** [comment]
> > Call a method when network is incorrect, show ask MetaMask to connect to the correct one before sign the transaction.
> > Now it will send the transaction to the incorrect chain ![image](https://user-images.githubusercontent.com/7271329/194927758-f01bac00-9057-4b32-a083-bf4354554c8f.png)
> 
> This one is dangerous so I added a simple patch [Magickbase/godwoken-explorer-ui@63d3239#diff-b8504e11f0446394f8f9c7920bccc4e9aa1a850d7c4199c8e6052aa25c289da6R128-R135](https://github.com/Magickbase/godwoken-explorer-ui/commit/63d32397ca1bf215a09fa71f516ad8f56183ef76#diff-b8504e11f0446394f8f9c7920bccc4e9aa1a850d7c4199c8e6052aa25c289da6R128-R135)

@qiweiii @Keith-CY  Optimize existing processes.

Status: 
When it is detected that the user has clicked the relevant button that the network is inconsistent with the current environment, it will be divided into 2 steps：
1. MetaMask will first ask to switch the network；
2. The user clicks the button again, and then displays the confirmation signature;

Expectation: 
The user only needs to click the button once in the above operation. After MetaMask requests to switch the network, the confirmation signature interface will be displayed, saving the user the operation of clicking the button again.
