### ISSUE TITLE
Method name/id is missing in activity list of erc 1155

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#1071]
```bash
curl --request POST \
  --url https://api.v1.betanet.gwscan.com/graphql \
  --header 'Content-Type: application/json' \
  --data '{"query":"query($contract: HashAddress, $limit: Int, $before: String, $after: String) 
```

The response is
```
{
	"data": {
		"erc1155_token_transfers": {
			"entries": [
				{
					"amount": "10",
					"from_account": {
						"type": "ETH_USER"
					},
					"from_address": "0xc4e2fe8694b5b15816727e54b5cad9f622e9c6bc",
					"to_account": {
						"type": "POLYJUICE_CONTRACT"
					},
					"to_address": "0xeeb92d6b3999abdc8cc0226069d88c07f241fd4c",
					"token_id": "1",
					"transaction": {
						"hash": "0xb133a4336e80d6e805cf8308f59559e295c010ac47815e9c5562edb26829e36b",
						"method_id": "0x59098a55",
						"method_name": null
					}
				},
				{
					"amount": "10",
					"from_account": {
						"type": "ETH_USER"
					},
					"from_address": "0xc4e2fe8694b5b15816727e54b5cad9f622e9c6bc",
					"to_account": {
						"type": "POLYJUICE_CONTRACT"
					},
					"to_address": "0xeeb92d6b3999abdc8cc0226069d88c07f241fd4c",
					"token_id": "1",
					"transaction": {
						"hash": "0xd68fc7409cfe54ec6f84f78c55964a277a67c5e414d91f6d00926977ea269674",
						"method_id": "0x59098a55",
						"method_name": null
					}
				},
				{
					"amount": "1000",
					"from_account": null,
					"from_address": "0x0000000000000000000000000000000000000000",
					"to_account": {
						"type": "ETH_USER"
					},
					"to_address": "0xc4e2fe8694b5b15816727e54b5cad9f622e9c6bc",
					"token_id": "4",
					"transaction": {
						"hash": "0xd42a0020376d0b46e0cb6923bf2512a1b4c3fc663f8f24deaf06fe492e297014",
						"method_id": null,
						"method_name": null
					}
				},
				{
					"amount": "1000",
					"from_account": null,
					"from_address": "0x0000000000000000000000000000000000000000",
					"to_account": {
						"type": "ETH_USER"
					},
					"to_address": "0xc4e2fe8694b5b15816727e54b5cad9f622e9c6bc",
					"token_id": "3",
					"transaction": {
						"hash": "0xd42a0020376d0b46e0cb6923bf2512a1b4c3fc663f8f24deaf06fe492e297014",
						"method_id": null,
						"method_name": null
					}
				},
				{
					"amount": "1000",
					"from_account": null,
					"from_address": "0x0000000000000000000000000000000000000000",
					"to_account": {
						"type": "ETH_USER"
					},
					"to_address": "0xc4e2fe8694b5b15816727e54b5cad9f622e9c6bc",
					"token_id": "2",
					"transaction": {
						"hash": "0xd42a0020376d0b46e0cb6923bf2512a1b4c3fc663f8f24deaf06fe492e297014",
						"method_id": null,
						"method_name": null
					}
				},
				{
					"amount": "1000",
					"from_account": null,
					"from_address": "0x0000000000000000000000000000000000000000",
					"to_account": {
						"type": "ETH_USER"
					},
					"to_address": "0xc4e2fe8694b5b15816727e54b5cad9f622e9c6bc",
					"token_id": "1",
					"transaction": {
						"hash": "0xd42a0020376d0b46e0cb6923bf2512a1b4c3fc663f8f24deaf06fe492e297014",
						"method_id": null,
						"method_name": null
					}
				}
			],
			"metadata": {
				"after": null,
				"before": null,
				"total_count": 6
			}
		}
	}
}
```

And last 4 records are mints but don't have method_id/name as expected

```
emit TransferSingle(operator, address(0), to, id, amount);
emit TransferBatch(operator, address(0), to, ids, amounts);
```

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC1155/ERC1155.sol#L281
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC1155/ERC1155.sol#L316

**Comment by Naupio** [comment]
```
query {
  erc1155_token_transfers(input: {to_address: "0xc4e2fe8694b5b15816727e54b5cad9f622e9c6bc", limit: 1}) {
    entries {
      to_address
      to_account{
        type
        id
        eth_address
      }
      token_contract_address_hash
      token_id
      token_ids
      transaction {
        hash
        method_id
        method_name
      }
    }
    metadata {
      before
      after
      total_count
    }
  }
}
```

```
{
  "data": {
    "erc1155_token_transfers": {
      "entries": [
        {
          "to_account": {
            "eth_address": "0xc4e2fe8694b5b15816727e54b5cad9f622e9c6bc",
            "id": 21356,
            "type": "ETH_USER"
          },
          "to_address": "0xc4e2fe8694b5b15816727e54b5cad9f622e9c6bc",
          "token_contract_address_hash": "0xdda71036579c367f1dc47a95563348680929513c",
          "token_id": "4",
          "token_ids": null,
          "transaction": {
            "hash": "0xfef4f8675593442046e3ffcc9aa516503ff6b77f9e2df77801a1212ef4c6c644",
            "method_id": null,
            "method_name": null
          }
        }
      ],
      "metadata": {
        "after": "g3QAAAADZAAMYmxvY2tfbnVtYmVyYgABQIJkAAlsb2dfaW5kZXhhA2QAEHRyYW5zYWN0aW9uX2hhc2h0AAAAA2QACl9fc3RydWN0X19kACJFbGl4aXIuR29kd29rZW5FeHBsb3Jlci5DaGFpbi5IYXNoZAAKYnl0ZV9jb3VudGEgZAAFYnl0ZXNtAAAAIHrq3zkOZtm0s97k6ubR29zw5T-HG5VgKCRv8dsDb7qf",
        "before": null,
        "total_count": 8
      }
    }
  }
}
```

seems `to_account` was `eth_user` account

Does only  `polyjuice_contract` account have `method_id`

**Comment by Keith-CY** [comment]
> ```graphql
> query {
>   erc1155_token_transfers(input: {to_address: "0xc4e2fe8694b5b15816727e54b5cad9f622e9c6bc", limit: 1}) {
>     entries {
>       to_address
>       to_account{
>         type
>         id
>         eth_address
>       }
>       token_contract_address_hash
>       token_id
>       token_ids
>       transaction {
>         hash
>         method_id
>         method_name
>       }
>     }
>     metadata {
>       before
>       after
>       total_count
>     }
>   }
> }
> ```
> 
> ```json
> {
>   "data": {
>     "erc1155_token_transfers": {
>       "entries": [
>         {
>           "to_account": {
>             "eth_address": "0xc4e2fe8694b5b15816727e54b5cad9f622e9c6bc",
>             "id": 21356,
>             "type": "ETH_USER"
>           },
>           "to_address": "0xc4e2fe8694b5b15816727e54b5cad9f622e9c6bc",
>           "token_contract_address_hash": "0xdda71036579c367f1dc47a95563348680929513c",
>           "token_id": "4",
>           "token_ids": null,
>           "transaction": {
>             "hash": "0xfef4f8675593442046e3ffcc9aa516503ff6b77f9e2df77801a1212ef4c6c644",
>             "method_id": null,
>             "method_name": null
>           }
>         }
>       ],
>       "metadata": {
>         "after": "g3QAAAADZAAMYmxvY2tfbnVtYmVyYgABQIJkAAlsb2dfaW5kZXhhA2QAEHRyYW5zYWN0aW9uX2hhc2h0AAAAA2QACl9fc3RydWN0X19kACJFbGl4aXIuR29kd29rZW5FeHBsb3Jlci5DaGFpbi5IYXNoZAAKYnl0ZV9jb3VudGEgZAAFYnl0ZXNtAAAAIHrq3zkOZtm0s97k6ubR29zw5T-HG5VgKCRv8dsDb7qf",
>         "before": null,
>         "total_count": 8
>       }
>     }
>   }
> }
> ```
> 
> seems `to_account` was `eth_user` account
> 
> Does only `polyjuice_contract` account have `method_id` ?

Only 2 conditions to check if a transaction has `method id`
1. Is the `to` address in the transaction pointing to a contract
2. Is it a contract call transaction, viz. `tx.input` has more than 8 bytes

If 1 and 2 are both true, the transaction should have a `method id`

**Comment by Keith-CY** [comment]
These transfer records don't have `method id/name` indeed because the transaction(https://v1.testnet.gwscan.com/tx/0x7aeadf390e66d9b4b3dee4eae6d1dbdcf0e53f871b956028246ff1db036fba9f?tab=logs) is to deploy a contract and 4 tokens are minted by the contract, so it has no direct relation to this transaction.
