### ISSUE TITLE
How to fetch basic info of an erc 1155 token

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#1072]
On visiting `erc 721 token item` page(https://v1.gwscan.com/nft-item/0xccc9b79ae84dd4476ff95726c753628d7f77d588/34), the token collection info could be fetched from the inventory API because `udt` is there.

```
type Erc721UserToken {
  address_hash: HashAddress
  counts: Decimal
  token_contract_address_hash: HashAddress
  token_id: Decimal
  token_type: EthType
  udt: Erc7211155CommonUdt
  value: Decimal
}
```
https://github.com/Magickbase/godwoken_explorer/blob/godwoken-v1-mainnet-prod/docs/schema.graphql#L595-L603

Now I'm trying to add a similar page for erc 1155, I find that `udt` is missing
```
type Erc1155Inventory {
  contract_address_hash: HashAddress
  counts: Decimal
  token_id: Decimal
}
```
https://github.com/Magickbase/godwoken_explorer/blob/godwoken-v1-mainnet-prod/docs/schema.graphql#L414-L418

Should `udt` be added or there's another query for it? @Naupio

**Comment by Naupio** [comment]
seems missing udt field of `Erc1155Inventory`
or
Erc721UserToken's similar erc1155 api can use `erc1155_user_inventory`?

**Comment by Keith-CY** [comment]
> seems missing udt field of `Erc1155Inventory` or `Erc721UserToken`'s similar erc1155 api can use `erc1155_user_inventory`?

Is there an API to fetch erc1155 collection info as mentioned in the meeting?

**Comment by Keith-CY** [comment]
> we can get udt info use udt api mainnet-prod env example
> 
> ```graphql
> query {
>   udt(
>     input: { contract_address: "0xccc9b79ae84dd4476ff95726c753628d7f77d588" }
>   ) {
>     contract_address_hash
>     symbol
>     name
>   }
> }
> ```
> 
> result
> 
> ```
> {
>   "data": {
>     "udt": {
>       "contract_address_hash": "0xccc9b79ae84dd4476ff95726c753628d7f77d588",
>       "name": "Nervos X Oblivion",
>       "symbol": "NXO"
>     }
>   }
> }
> ```

Cool

**Comment by Keith-CY** [comment]
> we can get udt info use udt api mainnet-prod env example
> 
> ```graphql
> query {
>   udt(
>     input: { contract_address: "0xccc9b79ae84dd4476ff95726c753628d7f77d588" }
>   ) {
>     contract_address_hash
>     symbol
>     name
>   }
> }
> ```
> 
> result
> 
> ```
> {
>   "data": {
>     "udt": {
>       "contract_address_hash": "0xccc9b79ae84dd4476ff95726c753628d7f77d588",
>       "name": "Nervos X Oblivion",
>       "symbol": "NXO"
>     }
>   }
> }
> ```

This API throws 500 error if record is not found

**Comment by Naupio** [comment]
`0xccc9b79ae84dd4476ff95726c753628d7f77d588` is erc721 token

**Comment by Keith-CY** [comment]
> `0xccc9b79ae84dd4476ff95726c753628d7f77d588` is erc721 token

I was querying `0xeeb92d6b3999abdc8cc0226069d88c07f241fd4c` on testnet which is an ERC 1155, it returns. But when I change the last char, 500 is thrown

**Comment by FrederLu** [comment]
Under normal circumstances, there is no data, and 500 should not be returned directly. Tips such as no data or abnormal data can be given. I will raise an issue to follow up.

**Comment by Naupio** [comment]
link #1076

**Comment by FrederLu** [comment]
Verified.

**Comment by Keith-CY** [comment]
This issue was used to confirm how to fetch `erc 1155` token info, but a new error was mentioned(https://github.com/Magickbase/godwoken_explorer/issues/1072#issuecomment-1275841030).

I see @FrederLu has verified the fix, could we close this issue?

**Comment by FrederLu** [comment]
> This issue was used to confirm how to fetch `erc 1155` token info, but a new error was mentioned([#1072 (comment)](https://github.com/Magickbase/godwoken_explorer/issues/1072#issuecomment-1275841030)).
> 
> I see @FrederLu has verified the fix, could we close this issue?

It has been dealt with, and now it does not prompt 500, which can be closed.
