### ISSUE TITLE
[Bridged Token] Godwoken Bridge Test Token

### ISSUE THREAD

**Issue by ShookLyngs** [Magickbase/godwoken_explorer#1078]
### Token Name

Godwoken Bridge Test Token

### Description

A test token on Godwoken Bridge testnet_v1

### Symbol

TTKN

### Logo URI

https://cryptologos.cc/logos/nervos-network-ckb-logo.svg?v=002

### SUDT Script Arguments

0x58bef38794236b315b7c23fd8132d7f42676228d659b291936e8c6c7ba9f064e

### Contract Address

0x3c41edd22658b2d6cf0eb26da941d74fe45bea52

**Comment by zmcNotafraid** [comment]
https://v1.testnet.gwscan.com/token/40444 @ShookLyngs
