### ISSUE TITLE
The L2 Script Hash on the Polyjuice Creator Account page is displayed abnormally.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#1084]
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/25676576/195520788-b4d2a2ad-2e1d-4da9-9e2e-9b9a0c59ac03.png">

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/25676576/195520222-ccb1507c-4917-4d88-a9d2-5385bea94190.png">

https://godwoken-explorer-d3yje2rav-magickbase.vercel.app/account/0x829cc5785a4d8ac642ede32cb3cb5cb9dc389d5892f2fc2afc760691445be194

There is a problem with the style, and there is no tooltip, refer to the style on testnet.

**Comment by FrederLu** [comment]
Got it. Seeing that this is a problem with ui, so I put it under https://github.com/Magickbase/godwoken-explorer-ui.

**Comment by JeffreyMa597** [comment]
The PR has been submitted. Please take a look.
Ref: https://github.com/Magickbase/godwoken-explorer-ui/pull/673

**Comment by FrederLu** [comment]
> The PR has been submitted. Please take a look. Ref: [Magickbase/godwoken-explorer-ui#674](https://github.com/Magickbase/godwoken-explorer-ui/pull/674)

Pr verified.
