### ISSUE TITLE
Tooltip in NFT pages is cropped

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#1094]
https://v1.testnet.gwscan.com/nft-collection/0x4fb12d002e3541af05270f5be22f554b4fad57ed

![image](https://user-images.githubusercontent.com/7271329/196108546-598e9443-6040-4aa9-aec3-9f4cc1efd969.png)

**Comment by Keith-CY** [comment]
There're two issues

1. Tooltip of the tx hash is cropped
![image](https://user-images.githubusercontent.com/7271329/196137542-ef05354e-1239-458e-8f00-ad9cd2ce842e.png)
code: https://github.com/Magickbase/godwoken-explorer-ui/blob/develop/components/NFTActivityList/index.tsx#L123

2. Tooltip of the method doesn't work
Expected to be like
![image](https://user-images.githubusercontent.com/7271329/196137841-725daae8-4011-4914-9bb5-f59eb5d189ac.png)
but no tooltips show in fact
code: https://github.com/Magickbase/godwoken-explorer-ui/blob/develop/components/NFTActivityList/index.tsx#L140
seems that `className="tooltip"` should be added(personally speaking, the className="tooltip" is redundant cuz `data-tooltip` has already shown its purpose)

**Comment by JeffreyMa597** [comment]
The PR has been submitted. Please have a look.
https://github.com/Magickbase/godwoken-explorer-ui/pull/673
