### ISSUE TITLE
Fix:  GodwokenIndexer.Worker.CheckLostAccount block Oban default queue when rpc fail

### ISSUE THREAD

**Issue by Naupio** [Magickbase/godwoken_explorer#1097]
{"at": "2022-10-18T19:00:00.778374Z", "error": "** (MatchError) no match of right hand side value: {:error, :econnrefused}\n    (godwoken_explorer 0.1.0) lib/godwoken_explorer/account.ex:598: GodwokenExplorer.Account.batch_import_accounts_with_ids/1\n    (godwoken_explorer 0.1.0) lib/godwoken_indexer/worker/check_lost_account.ex:52: GodwokenIndexer.Worker.CheckLostAccount.perform/1\n    (oban 2.12.0) lib/oban/queue/executor.ex:128: Oban.Queue.Executor.perform/1\n    (oban 2.12.0) lib/oban/queue/executor.ex:73: Oban.Queue.Executor.call/1\n    (elixir 1.13.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2\n    (elixir 1.13.1) lib/task/supervised.ex:34: Task.Supervised.reply/4\n    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\n", "attempt": 1}

**Comment by zmcNotafraid** [comment]
node error, no need to fix.
