### ISSUE TITLE
Read metadata of ERC 721/1155 from backend API

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#1108]
Each token item of ERC 721/1155 could have its own metadata, as https://v1.testnet.gwscan.com/nft-item/0x784cd3c52813098763c371df8fbe8ed27d2c1ebd/1339?tab=metadata

Now the metadata is fetched from front-end directly so the name and cover of a token item appear slowly.

Issue https://github.com/Magickbase/godwoken_explorer/issues/967 requires a new field `metadata` to be returned within the API so we can avoid requests in the front-end to deliver info smoothly.

With the cached metadata

- Covers in token collection inventory(https://v1.testnet.gwscan.com/nft-collection/0x784cd3c52813098763c371df8fbe8ed27d2c1ebd?tab=inventory) can be shown without a batch of requests: 
![image](https://user-images.githubusercontent.com/7271329/197494796-fd425061-0200-4aff-87e1-2896fa39df49.png)
- Token item name and cover can be rendered ASAP on token item page(https://v1.testnet.gwscan.com/nft-item/0x784cd3c52813098763c371df8fbe8ed27d2c1ebd/1339?tab=metadata)
- Token metadata tab is available instantly: https://v1.testnet.gwscan.com/nft-item/0x784cd3c52813098763c371df8fbe8ed27d2c1ebd/1339?tab=metadata
![image](https://user-images.githubusercontent.com/7271329/197495157-13233122-e9dc-40e6-8869-2707cbe92e11.png)

**Comment by Keith-CY** [comment]
PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/688

**Comment by JeffreyMa597** [comment]
@Naupio 
Hi~
Please have a look at this value. we got a `null` when we request `PaginateErc1155Inventory`. 
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/22511289/199643800-ce376eaf-ff5e-40e5-ba90-d9d88ada9d7e.png">

**Comment by Naupio** [comment]
contract `0xeeb92d6b3999abdc8cc0226069d88c07f241fd4c` was deployed with `nxdomain` uri/token_uri for erc1155 interface

**Comment by JeffreyMa597** [comment]
I've used the contract_address `0xe6903e124e5bdae8784674eb625f1c212efc789e` test it by myself.

**Comment by JeffreyMa597** [comment]
PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/698
