### ISSUE TITLE
Link to erc 721 token collection could be added on token item page

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#1109]
I see a slight difference on token item page of erc 721 and erc 1155

ERC 1155
![image](https://user-images.githubusercontent.com/7271329/197495809-afda3dc1-d8b1-4750-81b9-d7a9e178e9dd.png)

ERC 721
![image](https://user-images.githubusercontent.com/7271329/197495847-9c3500ee-6f7b-474c-b716-bbcd4fdbe63a.png)

On the page of ERC 1155, the token item name(from metadata) is shown on the top and a link to the token collection with text(`token_name(token_symbol)`) is under it.

On the page of ERC 721, the token collection name is shown on the top and token item name(from metadata) is only visible in the `metadata tab`

Maybe we should use the layout of erc 1155 on the erc 721 page so a user could navigate to erc 721 token collection page from the item page.

Any idea from @Kirl70 @FrederLu @JeffreyMa597 @qiweiii

**Comment by Kirl70** [comment]
Good idea, this is more convenient for users to quickly jump to the token collection page

**Comment by FrederLu** [comment]
In this way, a closed loop of the partial process is formed, which is convenient for users to return to the token collection page to start subsequent operations.

**Comment by Keith-CY** [comment]
A link labelled with collection and navigates to collection page has been added by PR https://github.com/Magickbase/godwoken-explorer-ui/pull/688

Preview: https://www.gwscan.com/nft-item/0x2012d2b30af501c6d991b1e21aa172b9efff95a8/2
