### ISSUE TITLE
 The basic info width dimension is abnormal.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#1111]
The text display problem is ok, but now the whole module at the bottom is the wrong size. It is expected that the adjustment will involve other pages, so create a separate issue tracker.

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/25676576/197460009-df89be63-390b-429c-8be3-adf5c139aa0a.png">

<img width="810" alt="image" src="https://user-images.githubusercontent.com/25676576/197670302-9a4b05af-c195-4c8d-a95c-8921afd8a363.png">

**Comment by Keith-CY** [comment]
https://v1.gwscan.com/token/133
![image](https://user-images.githubusercontent.com/7271329/202386901-46e475d4-f82d-4179-9d68-8e8d206c195e.png)

**Comment by JeffreyMa597** [comment]
PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/726

**Comment by FrederLu** [comment]
@JeffreyMa597 
There are still problems on the test network, need to confirm.

**Comment by FrederLu** [comment]
Verified.
