### ISSUE TITLE
[Native ERC20 Token] **Token Name**

### ISSUE THREAD

**Issue by specmeup** [Magickbase/godwoken_explorer#1116]
### Token Name

$guild

### Description

$guild is the native token for the CKB Society. 

### Max Supply

700000000

### Website

ckbsociety.space

### Logo URI

https://i.ibb.co/NxHHhkz/guild-logo.png

### Contract Address

0x0a451a21a9d7fe0ce8aec816ac70b99d2bf62a1d

**Comment by zmcNotafraid** [comment]
https://v1.gwscan.com/zh-CN/token/10337 @specmeup

**Comment by specmeup** [comment]
made updates to the website URL and the logo:

Website
https://www.ckbsociety.space/

Logo URI
https://i.ibb.co/zxSJrpF/ckb-society-logo-update.jpg

**Comment by zmcNotafraid** [comment]
> made updates to the website URL and the logo:
> 
> Website https://www.ckbsociety.space/
> 
> Logo URI https://i.ibb.co/zxSJrpF/ckb-society-logo-update.jpg

Done
