### ISSUE TITLE
[General Contract] **Contract Name**

### ISSUE THREAD

**Issue by fertileglitch** [Magickbase/godwoken_explorer#1117]
### Contract Name

NervosPunkz

### Contract Address

0x348C854E36e57C2D78D6f3BD92cAE4108Ec64c34

### Compiler Version

v0.8.16+commit.07a7930e

### Website

https://nervospunkz.com/

### Logo URI

https://nervospunkz.com/wp-content/uploads/2022/01/NervosPunkzLogo3.png

**Comment by Keith-CY** [comment]
https://v1.gwscan.com/nft-collection/0x348c854e36e57c2d78d6f3bd92cae4108ec64c34

**Comment by zmcNotafraid** [comment]
@fertileglitch  Please submit contract code.

**Comment by fertileglitch** [comment]
> @fertileglitch Please submit contract code.

how and where should i submit the code to?
