### ISSUE TITLE
ERC721 chaining exception for token collections.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#1123]
https://www.gwscan.com/nft-item/0x2012d2b30af501c6d991b1e21aa172b9efff95a8/2
<img width="710" alt="image" src="https://user-images.githubusercontent.com/25676576/199406502-72f77972-b69b-4d5e-b15e-e4a35e759fce.png">
<img width="797" alt="image" src="https://user-images.githubusercontent.com/25676576/199406537-d761749e-03b7-439f-9bba-8cabe0cebfe6.png">

**Comment by Keith-CY** [comment]
It should be fixed by https://github.com/Magickbase/godwoken-explorer-ui/commit/6a91add3ee06e84beecdbf3e8bbc44fa7135712a

**Comment by FrederLu** [comment]
Yes, the mainnet jump is now normal.
