### ISSUE TITLE
Token price api

### ISSUE THREAD

**Issue by zmcNotafraid** [Magickbase/godwoken_explorer#1130]
For now， we can use `GodwokenExplorer.Chain.Cache.TokenExchangeRate.fetch_by_symbol("btc")` to get token price. Args use udt symobl column.We need to display token value in page that use price * amount.

**Comment by Naupio** [comment]
- [ ] add token price for user assert list
- [ ] use sync call replace async call token price api

**Comment by Keith-CY** [comment]
PR: https://github.com/Magickbase/godwoken_explorer/pull/1158

**Comment by Naupio** [comment]
- [ ] compatible with uan format symbol for fetching price
- [ ] price show condition: only show type with `native` record for `udt` object and show `eth-bridge-celer-mapping-godwoken-native-token` and `ckb-bridge-mapping-godoweken-native-token`

**Comment by Naupio** [comment]
need support @zmcNotafraid : 
according to our discussion with @Keith-CY 
we can add new field for udt table to distinct the type with `native` record which from.

* godwoken-native-created-token
* ckb-bridge-mapping-godoweken-native-token (show price)
* eth-celer-bridge-mapping-godwoken-native-token (show price)

**Comment by Naupio** [comment]
if udt record has uan fields( bridge token), show the price

**Comment by Naupio** [comment]
testnet-stg was deployed @FrederLu

**Comment by Naupio** [comment]
example:
```
query {
  udts(input: {limit: 1}) {
    entries {
      token_exchange_rate {
        symbol
        exchange_rate
        timestamp
      }
    }
  }
}
```

```
{
  "data": {
    "udts": {
      "entries": [
        {
          "token_exchange_rate": {
            "exchange_rate": null,
            "symbol": "pCKB.gw|gb.ckb",
            "timestamp": 1669005313736
          }
        }
      ]
    }
  }
}
```

**Comment by FrederLu** [comment]
Testnet-stg was verified.

**Comment by Naupio** [comment]
pr link: #1158

**Comment by FrederLu** [comment]
Verified.
