### ISSUE TITLE
Graphql api error

### ISSUE THREAD

**Issue by zmcNotafraid** [Magickbase/godwoken_explorer#1134]
2022-11-07 19:14:02.864 [error] #PID<0.22098.0> running GodwokenExplorerWeb.Endpoint (connection #PID<0.22096.0>, stream id 1) terminated
Server: api.v1.gwscan.com:80 (http)
Request: POST /graphql
** (exit) an exception was raised:
    ** (ArgumentError) comparison with nil is forbidden as it is unsafe. If you want to check if a value is nil, use is_nil/1 instead
        (ecto 3.7.2) lib/ecto/query/builder.ex:958: Ecto.Query.Builder.not_nil!/1
        (godwoken_explorer 0.1.0) lib/godwoken_explorer/graphql/resolovers/udt.ex:142: anonymous fn/3 in GodwokenExplorer.Graphql.Resolvers.UDT.udt/3
        (ecto 3.7.2) lib/ecto/query/builder/dynamic.ex:54: Ecto.Query.Builder.Dynamic.expand/3
        (ecto 3.7.2) lib/ecto/query/builder/dynamic.ex:32: Ecto.Query.Builder.Dynamic.fully_expand/2
        (ecto 3.7.2) lib/ecto/query/builder/filter.ex:133: Ecto.Query.Builder.Filter.filter!/7
        (godwoken_explorer 0.1.0) lib/godwoken_explorer/graphql/resolovers/udt.ex:154: GodwokenExplorer.Graphql.Resolvers.UDT.udt/3
        (absinthe 1.7.0) lib/absinthe/resolution.ex:209: Absinthe.Resolution.call/2
        (absinthe 1.7.0) lib/absinthe/phase/document/execution/resolution.ex:230: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
2022-11-08 13:38:57.834 [error] PromEx.DashboardUploader (#PID<0.3243.0>) failed to retrieve the dashboard folderId from Grafana (https://magickbase.grafana.net) because: {:error, :unknown}

**Comment by Naupio** [comment]
seems use nil data to compare` dynamic([u], ^acc and u.id == ^value)`

**Comment by Naupio** [comment]
#1146

**Comment by FrederLu** [comment]
Testnet-stg verified.

**Comment by Naupio** [comment]
testnet-prod was deployed

**Comment by FrederLu** [comment]
Testnet-prod verified.
