### ISSUE TITLE
[Native ERC20 Token] $GUILD

### ISSUE THREAD

**Issue by specmeup** [Magickbase/godwoken_explorer#1135]
### Token Name

$guild

### Description

$guild is the native token for the CKB Society.

### Max Supply

700000000

### Website

https://www.ckbsociety.space

### Logo URI

https://i.ibb.co/zxSJrpF/ckb-society-logo-update.jpg

### Contract Address

0x0a451a21a9d7fe0ce8aec816ac70b99d2bf62a1d

### Other Info

Original registration:
https://github.com/Magickbase/godwoken_explorer/issues/1116

made updates to logo and website URL:

Website
https://www.ckbsociety.space/

Logo URI
https://i.ibb.co/zxSJrpF/ckb-society-logo-update.jpg

**Comment by zmcNotafraid** [comment]
Updated. @specmeup
