### ISSUE TITLE
Truncated field misses ellipsis and label is wrapped

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#1150]
![image](https://user-images.githubusercontent.com/7271329/201574554-17c1d259-d5a3-41d3-b0b7-0ebf7f293c02.png)
https://v1.testnet.gwscan.com/account/0x93458b28c4944f5d5ac9895d8d8f257b505e4349?tab=transactions

1. `Deployer` and `Deploy Transaction` fields are truncated without ellipsis
2. `Deploy Transaction` label is wrapped

**Comment by JeffreyMa597** [comment]
PR：https://github.com/Magickbase/godwoken-explorer-ui/pull/727
