### ISSUE TITLE
GodwokenExplorer.Graphql.Workers.SmartContractRegister exist sql performance problem

### ISSUE THREAD

**Issue by zmcNotafraid** [Magickbase/godwoken_explorer#1156]
** (DBConnection.ConnectionError) tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
    (ecto_sql 3.7.2) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.7.2) lib/ecto/adapters/sql.ex:693: Ecto.Adapters.SQL.execute/5
    (ecto 3.7.2) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4
    (ecto 3.7.2) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3

**Comment by Naupio** [comment]
seems `GodwokenExplorer.Graphql.Workers.Sourcify` workers consume many db resource, I will optimize this worker with unique queue

**Comment by Naupio** [comment]
link pr #1185

**Comment by FrederLu** [comment]
Verified.
