### ISSUE TITLE
Search api return an array

### ISSUE THREAD

**Issue by zmcNotafraid** [Magickbase/godwoken_explorer#1159]
When search token name, the results may exist multiple records.

**Comment by Keith-CY** [comment]
We will add a new page of the matched token list when the API is ready. When a user types `token name` in the search field, the page will be navigated to the matched token list page.

The search result may contain various kinds of token, say, an ERC 20 named `A`, an ERC 721 named `A` and an ERC 1155 named `A`. They have different attributes so the list will only display their common attributes.

<table>
<tr>
	<td>Token
	<td>Type
	<td>Address
<tr>
	<td>icon + name
	<td>ERC20/ERC721/ERC1155
	<td>0x7538c85cae4e4673253ffd2568c1f1b48a71558a
</table>

Pagination should be supported as the current token list

**Comment by zmcNotafraid** [comment]
- [ ] remove token name search temp
 - [ ] add new api

**Comment by Naupio** [comment]
link #1161
