### ISSUE TITLE
GasLess tx support

### ISSUE THREAD

**Issue by zmcNotafraid** [Magickbase/godwoken_explorer#1163]
https://github.com/godwokenrises/godwoken/discussions/860#discussioncomment-4597649

**Comment by zmcNotafraid** [comment]
@Keith-CY tx_hash: 0xe83e9ae5d3194fa27a5485f3cf5e0abddd264dc6a04a43d7bfffd45e157db207 is a gas less tx.
it includes below fields
```
 query {
  transaction(
        input: {
          eth_hash: "0xe83e9ae5d3194fa27a5485f3cf5e0abddd264dc6a04a43d7bfffd45e157db207"
        }
      ) {
    polyjuice {
        call_contract, call_data, call_gas_limit, verification_gas_limit, max_fee_per_gas,
     max_priority_fee_per_gas, paymaster_and_data
  }
  }
}
```

**Comment by Keith-CY** [comment]
Updates in UI:
1. The transaction page will be updated for the gasless feature first
	1. `To` address of the transaction is displayed as `Gasless Entrypoint` instead of the contract address
	2. Gas Price/Fee will be marked `Gasless` instead of showing `0 pCKB`;
	3. Add a new section titled `User Operations` to show parsed `tx.data`
	    1. `Call Contract`
	    2. `Call Data`: plain text, will be parsed by ABI of the contract in future, similar to `tx.input`
	    3. `Call Gas Limit`
	    4. `Verification Gas Limit`
	    5. `Max Fee Per Gas`
	    6. `Max Priority Fee Per Gas`
	    7. `Paymaster And Data`
8. The transaction list on several pages will be updated later
    1. `To` should be displayed by `call contract` parsed from `tx.data`, similar to a native transfer, which shows `to` with `tx.input`
    2. Filtering `to` should include the `call contract`

**Comment by Keith-CY** [comment]
> Updates in UI:
> 
> 1. The transaction page will be updated if it's a gasless transaction
>    
>    1. `To` address of the transaction is displayed as `Gasless Entrypoint` instead of the contract address, similar to `Polyjuice Creator`
>    2. Gas Price/Fee will be marked `Gasless` instead of showing `0 pCKB`;
>    3. Add a new section(single column beneath the basic info section) titled `User Operations/用户操作` to show parsed `tx.data`
>       
>       1. `Call Contract`: the actual target contract address of the gasless transaction
>       2. `Call Data`: the actual `calldata` on calling the target contract, displayed in plain text, will be parsed by ABI of the target contract in the future, similar to `tx.input`
>          ![image](https://user-images.githubusercontent.com/7271329/211147016-4bc403ab-0c9b-443c-a493-e32ae68e40e1.png)
>       3. `Call Gas Limit`: the actual gas used to execute the call
>       4. `Verification Gas Limit`: the actual gas used to verify the call
>       5. `Max Fee Per Gas`: the actual gas price
>       6. `Max Priority Fee Per Gas`: reserved field, same as `max fee per gas` for now
>       7. `Paymaster`: the address of paymaster, first 20 bytes of `paymaster and data`.
>       8. `Paymaster Data`: extra data appended along with the paymaster after the paymaster address
> 2. The transaction list on several pages will be updated later
>    
>    1. `To` should be displayed by `call contract` parsed from `tx.data`, similar to a native transfer, which shows `to` with `tx.input`
>    2. Filtering `to` should include the `call contract`

Now only point 1 is going to be implemented.

<sub>All these fields could be parsed from the response of Godwoken Node(1. entrypoint could be fetched via `poly_version` and `userOps` could be parsed from `tx.data`), but we'll adopt parsed fields from the backend API because these fields are necessary for public API services.</sub>

Point 1.1 requires extra update of the backend, other sub-points are ready for front-end development as mentioned in https://github.com/Magickbase/godwoken_explorer/issues/1163#issuecomment-1373331173

Please have a review on the front-end text PRD, and any questions could be appended to this issue @qiweiii 

If there's no question, please connect to @Kirl70 to update the UI Design in https://github.com/Magickbase/visual-style-guide/

**Comment by qiweiii** [comment]
Design should be fine to add. @Kirl70 

Do we check if it's a gasless tx using response from `poly_version` or using backend API? @Keith-CY

**Comment by Keith-CY** [comment]
> Design should be fine to add. @Kirl70
> 
> Do we check if it's a gasless tx using response from `poly_version` or using backend API? @Keith-CY

Checking if the `gas price` is `0` is enough for now because `0 gas price` is only allowed in a gasless transaction. `0 gas price` normal transactions will be rejected because there'll be no rewards for miners.

After the address alias `Gasless Entrypoint` is marked by the backend(point 1.1), we can add another check in front-end:
1. `to` address has the alias `Gasless Entrypoint`
2. `gas price` is `0`

Or to say, checking if a tx is gasless by comparing `to` address with `entrypoint` in `poly_version` will be done in the backend, if it matches, alias `Gasless EntryPoint` will be included in the response

**Comment by Kirl70** [comment]
> Updates in UI:
> 
> 1. The transaction page will be updated if it's a gasless transaction
>    
>    1. `To` address of the transaction is displayed as `Gasless Entrypoint` instead of the contract address, similar to `Polyjuice Creator`
>    2. Gas Price/Fee will be marked `Gasless` instead of showing `0 pCKB`;
>    3. Add a new section(single column beneath the basic info section) titled `User Operations/用户操作` to show parsed `tx.data`
>       
>       1. `Call Contract`: the actual target contract address of the gasless transaction
>       2. `Call Data`: the actual `calldata` on calling the target contract, displayed in plain text, will be parsed by ABI of the target contract in the future, similar to `tx.input`
>          ![image](https://user-images.githubusercontent.com/7271329/211147016-4bc403ab-0c9b-443c-a493-e32ae68e40e1.png)
>       3. `Call Gas Limit`: the actual gas used to execute the call
>       4. `Verification Gas Limit`: the actual gas used to verify the call
>       5. `Max Fee Per Gas`: the actual gas price
>       6. `Max Priority Fee Per Gas`: reserved field, same as `max fee per gas` for now
>       7. `Paymaster`: the address of paymaster, first 20 bytes of `paymaster and data`.
>       8. `Paymaster Data`: extra data appended along with the paymaster after the paymaster address
> 2. The transaction list on several pages will be updated later
>    
>    1. `To` should be displayed by `call contract` parsed from `tx.data`, similar to a native transfer, which shows `to` with `tx.input`
>    2. Filtering `to` should include the `call contract`

Regarding a-h, should I add to the original or just replace the original content? @Keith-CY

**Comment by Keith-CY** [comment]
> 3\. User Operations/用户操作

Add a new section titled `User Operations/用户操作`, placed beneath the `basic info` section.

So there'll be three sections if a transaction is gasless
1. overview
2. basic info
3. user operations

**Comment by FrederLu** [comment]
Verified.
