### ISSUE TITLE
data of erc 1155 tokens are incorrect

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#1164]
ERC 1155 List page: https://www.gwscan.com/multi-token-collections
Type counts are all 0 since the thrid record
![image](https://user-images.githubusercontent.com/7271329/203097003-20f48252-d4b9-4244-9f61-c5d7271a464b.png)

Visit the Nervape Item(NAI) page: https://www.gwscan.com/multi-token-collection/0xf780a8e4e9a5eaec25bd7baba88b9071c949e259
There're many records of minting 0 token
![image](https://user-images.githubusercontent.com/7271329/203097220-d12d4e3c-85df-4ce9-bd36-371270a9ca22.png)
And it's erc1155 inventory is empty
![image](https://user-images.githubusercontent.com/7271329/203097371-6fa7b124-11fd-4db4-9af2-e6795f2286d7.png)

While visiting the nft page of this contract(https://www.gwscan.com/nft-collection/0xf780a8e4e9a5eaec25bd7baba88b9071c949e259?tab=inventory), the inventory is correct
![image](https://user-images.githubusercontent.com/7271329/203097559-94d06404-248e-44db-a975-73a412832a16.png)

**Comment by Keith-CY** [comment]
Any update?

**Comment by Naupio** [comment]
address with '0xf780a8e4e9a5eaec25bd7baba88b9071c949e259' by use rpc call godwoken node check it is 'erc1155' contract

**Comment by Naupio** [comment]
> Any update?

address with '0xf780a8e4e9a5eaec25bd7baba88b9071c949e259' by use rpc call godwoken node check it is 'erc1155' contract

**Comment by Keith-CY** [comment]
Could be a problem from https://github.com/Magickbase/godwoken_explorer/blob/godwoken-v1-mainnet-prod/lib/godwoken_explorer/udt.ex#L427

```elixir
        result == "0x0000000000000000000000000000000000000000000000000000000000000000"
```

which should be

```elixir
        result == "0x0000000000000000000000000000000000000000000000000000000000000001"
```

**Comment by Naupio** [comment]
link pr: #1189

**Comment by Naupio** [comment]
need reprocess history data

**Comment by Naupio** [comment]
history data was updated @FrederLu

**Comment by FrederLu** [comment]
The data displayed on the page is abnormal.
https://www.gwscan.com/multi-token-collection/0xf780a8e4e9a5eaec25bd7baba88b9071c949e259?tab=activity

![Image](https://user-images.githubusercontent.com/25676576/205845251-6abbe39a-f29c-4216-893f-7d3ab6cfbb37.png)

**Comment by Naupio** [comment]
`0xf780a8e4e9a5eaec25bd7baba88b9071c949e259` is erc1155 contract  https://www.gwscan.com/nft-collection/0xf780a8e4e9a5eaec25bd7baba88b9071c949e259

**Comment by Naupio** [comment]
`0xf780a8e4e9a5eaec25bd7baba88b9071c949e259` is erc721 contract  https://www.gwscan.com/nft-collection/0xf780a8e4e9a5eaec25bd7baba88b9071c949e259

**Comment by FrederLu** [comment]
The data in the holders tab does not correspond to the Holder Count of Stats.
https://www.gwscan.com/nft-collection/0xf780a8e4e9a5eaec25bd7baba88b9071c949e259?tab=holders

![Image](https://user-images.githubusercontent.com/25676576/205851510-c7648d30-9f55-4eea-b869-de3f2d226609.png)

![Image](https://user-images.githubusercontent.com/25676576/205851604-0a94f916-8953-49b7-9fbd-9e8a8d0a9247.png)

**Comment by Naupio** [comment]
seems need fix `udt_balance` and `current_udt_balance` table's invalid data tooo

**Comment by Naupio** [comment]
@FrederLu  inconsistent holder count was fixed after updating the udt_balance and current_udt_balance invalid data

**Comment by FrederLu** [comment]
Verified.
