### ISSUE TITLE
Token item link in erc 1155 transfers is incorrect

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#1165]
Page: https://www.gwscan.com/tx/0x52f7aebd10d50c64c9ff396185ecd6558d17d3a6eb087803b08d700a7af2512a?tab=erc1155Records
![image](https://user-images.githubusercontent.com/7271329/203099864-43808ba8-9882-49d3-98b5-6c25dce40903.png)

The link points to `nft-item/{contract_address}/{token_id}`, where `nft-item` is for erc 721 and `multi-token-item/{contract_address}/{token_id}` is for erc 1155

**Comment by JeffreyMa597** [comment]
PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/739

**Comment by FrederLu** [comment]
Verified.
