### ISSUE TITLE
 There are exceptions displayed on the transaction info and token pages.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#1168]
1、The color of the ellipsis is found to be abnormal.
https://v1.testnet.gwscan.com/token/375
![Image](https://user-images.githubusercontent.com/25676576/203706648-9856f51b-6ba2-43ee-8ae7-adbe93d4fa52.png)

2、Data left alignment problem occurs when the `Overview` of `Transaction Info` is compatible with the mobile terminal.
https://v1.testnet.gwscan.com/tx/0x021a2050e171c632d1f0c57636cfc143d235af1c6275cbcfcf1ed39530dcf460
<img width="766" alt="image" src="https://user-images.githubusercontent.com/25676576/203708722-612cb21c-8b74-4b67-9e90-5292d46d590c.png">
https://v1.testnet.gwscan.com/tx/0xd08d9d797e7be90be664945a587cf1b5cc66092469b8febad4413894f3135f65
<img width="778" alt="image" src="https://user-images.githubusercontent.com/25676576/203708869-6c0745c1-af14-4868-a55d-38ffb5639b74.png">

**Comment by JeffreyMa597** [comment]
PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/752
