### ISSUE TITLE
Support .bit resolution

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#1170]
.bit is a did service running on CKB which is similar to [ENS](https://ens.domains/) but much more powerful.

In this feature, only the domain function of .bit will be considered so we can learn the design from **ENS on etherscan.io**

### Display

If an address has a .bit domain
1. show the .bit domain prior to the address
Some details on page https://etherscan.io/address/0xd8da6bf26964af9d7eed9e03e53415d37aa96045
![image](https://user-images.githubusercontent.com/7271329/205018857-80b177aa-06b5-49b2-a5e2-a56d6c73cab4.png)
![image](https://user-images.githubusercontent.com/7271329/205018902-e833a40a-da9a-4f6b-a2c5-ae621e88f18b.png)
Some details on the transaction page
![image](https://user-images.githubusercontent.com/7271329/205019476-21e6e8c4-a9cd-422f-a094-9846e5e05bd6.png)

2. show the .bit domain on the account page
Some details on page https://etherscan.io/address/0xd8da6bf26964af9d7eed9e03e53415d37aa96045
![image](https://user-images.githubusercontent.com/7271329/205019089-75400220-0ccb-4e83-ac58-91f6f0991879.png)

The .bit domain will be displayed on the account page and a .bit page(e.g. https://dear.bit.cc/) will be opened in a new tab by clicking on it

PS: the tooltip on hovering the domain varies on different pages, some display `domain(address)` and some display `address`, on gwscan it could be simply `address`

### Search
If a .bit domain is found by searching, gwscan will navigate to the account page directly, which is different from etherscan.io, on etherscan there's a [ens lookup` page](https://etherscan.io/enslookup-search?search=vitalik.eth), we'll not add a page

Ref: 
- .bit on ckb explorer: https://github.com/Magickbase/ckb-explorer-public-issues/issues/8
- .bit on godwoken bridge: https://testnet.bridge.godwoken.io/#/v1/deposit/pending

**Comment by Naupio** [comment]
we can add three step to do this featrue:
- [ ] add new field for `db schema`/`graphql scheme` and simple trigger for store data(if not exist) while api call
- [ ] add real time update strategy for on chain account
- [ ] add not chain account with this feat

**Comment by Keith-CY** [comment]
There're mainly 2 points about adding .bit domain
1. display: display .bit domain if possible, and add the .bit domain on the account page;
2. search .bit domain: if a .bit domain is typed in the search field and a record is found, the related account page will be navigated to;

The UI design will be updated in https://github.com/Magickbase/visual-style-guide/issues/15

@FrederLu please have a review and any question could be added in this issue.

**Comment by Keith-CY** [comment]
UI has been updated at https://github.com/Magickbase/visual-style-guide/issues/15 @JeffreyMa597 could you take over of the UI work

**Comment by zmcNotafraid** [comment]
bit api docs: https://github.com/dotbitHQ/das-account-indexer/blob/main/API.md#get-reverse-record-info

**Comment by JeffreyMa597** [comment]
> UI has been updated at https://github.com/Magickbase/visual-style-guide/issues/15 @JeffreyMa597 could you take over of the UI work.

Got it.

**Comment by zmcNotafraid** [comment]
@JeffreyMa597  staging has deployed this feature.

![image](https://user-images.githubusercontent.com/12708910/207482233-bb9e93fe-107a-4de3-961d-8cbbf22970cb.png)

**Comment by JeffreyMa597** [comment]
@Kirl70 There seems to be a lack of presence on mobile. Do we need to consider that?

**Comment by Kirl70** [comment]
> @Kirl70 There seems to be a lack of presence on mobile. Do we need to consider that?

The display on mobile is the same as on PC.
Design Draft:

https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=2494%3A18632&t=SDkHlXi5FP0lV4Zg-1
<img width="545" alt="image" src="https://user-images.githubusercontent.com/106060898/207749668-9a28d691-2bd5-4dc4-b427-f30fbe152e13.png">

**Comment by Keith-CY** [comment]
I found that .bit could have a custom avatar, e.g. https://bit.cc/bestcase.bit, the url is set in `profile.avatar` field(https://github.com/dotbitHQ/cell-data-generator/blob/master/data/record_key_namespace.txt#L8) and could be parsed with SDK https://github.com/dotbitHQ/dotbit.js

The default logo/icon could be replaced with the custom one if possible @JeffreyMa597 , this feature could be done by another PR after some technical investigation

**Comment by JeffreyMa597** [comment]
PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/805

**Comment by Keith-CY** [comment]
There's been a small change since the issue was open. The .bit account page was moved from `https://dear.bit.cc` to `https://data.did.id/dear.bit` @JeffreyMa597 @FrederLu 

Ref: https://docs.did.id/projects/data.did.id

**Comment by JeffreyMa597** [comment]
@Kirl70 Please help to confirm or design the display style of `domain` icon on the home page. It may conflict with the style of some other display if we align the text on the left, such as `ployjuce...`.
All of them are aligned on the left maybe better?

<img width="455" alt="image" src="https://user-images.githubusercontent.com/22511289/209465731-6e9ed996-49ac-456c-92d5-5b96b0e6b53e.png">
<img width="707" alt="image" src="https://user-images.githubusercontent.com/22511289/209465907-c56312cd-ce81-4714-b51d-ca6715d72fa0.png">

**Comment by Kirl70** [comment]
Change the address uniformly to left-aligned. 
Example of effect:
<img width="587" alt="image" src="https://user-images.githubusercontent.com/106060898/209467017-21965526-8430-47a2-9ac8-55bfcfb5f8eb.png">

<img width="407" alt="image" src="https://user-images.githubusercontent.com/106060898/209467069-53344387-1568-4727-8651-47ea69fe60b3.png">

**Comment by Keith-CY** [comment]
PR of supporting .bit has been merged and deployed on mainnet because there're 2 approvals.

But I just found 2 issues
1. searching `magickbase.bit` went to the token filter page, it's possible to recognize a `.bit` domain on searching because it ends with `.bit`
2. the `.bit domain` tag on the account page should be a link to .bit account page, e.g. https://data.did.id/magickbase.bit, but it's plain text now.
![image](https://user-images.githubusercontent.com/7271329/210868900-c806fc6d-22dc-40f8-b3a6-009b5c2d2296.png)

Ref:
- feature request on navigating to .bit page: https://github.com/Magickbase/godwoken_explorer/issues/1170#issue-1464097758
- .bit account page: https://github.com/Magickbase/godwoken_explorer/issues/1170#issuecomment-1361680168

**Comment by Keith-CY** [comment]
Another issue, as designed in UI
![image](https://user-images.githubusercontent.com/7271329/210869930-db87bcb6-0aa8-4f68-83c5-e44462ad8e54.png)
`.bit Name` is displayed on hovering .bit icon, now the value of .bit name is displayed. It could be a misunderstanding in communication.
![image](https://user-images.githubusercontent.com/7271329/210870173-9316a5b7-9114-4acf-b301-570619282733.png)
IMO, showing `magickbase.bit` on hovering .bit icon is redundant because `magickbase.bit` sits next to the icon

**Comment by Keith-CY** [comment]
1. https://v1.gwscan.com/token/133?tab=holders&id=133&page=13 
in the holder list, `magickbase.bit` is not displayed
![image](https://user-images.githubusercontent.com/7271329/210871624-fe6d84f2-dc3e-4b34-8db3-04f9306e1684.png)

2. https://v1.gwscan.com/nft-collection/0x73c0e2a4b765ed81f63759d1fcf2c4dcd2925f4a?tab=inventory
in the inventory, owner of item#2375 is not displayed by .bit name
![image](https://user-images.githubusercontent.com/7271329/210871999-aac4fe0b-5378-447c-9b65-8d61a14d892a.png)


3. https://v1.gwscan.com/nft-item/0x73c0e2a4b765ed81f63759d1fcf2c4dcd2925f4a/2375
From the inventory page mentioned above, we can visit the item page of item#2375 and found `owner` is not displayed with .bit name, while `to` in the history is displayed correctly
![image](https://user-images.githubusercontent.com/7271329/210871922-487aeb08-f23c-4f12-b54c-ac4c8960494b.png)

**Comment by JeffreyMa597** [comment]
> Another issue, as designed in UI ![image](https://user-images.githubusercontent.com/7271329/210869930-db87bcb6-0aa8-4f68-83c5-e44462ad8e54.png) `.bit Name` is displayed on hovering .bit icon, now the value of .bit name is displayed. It could be a misunderstanding in communication. ![image](https://user-images.githubusercontent.com/7271329/210870173-9316a5b7-9114-4acf-b301-570619282733.png) IMO, showing `magickbase.bit` on hovering .bit icon is redundant because `magickbase.bit` sits next to the icon

I'll remove this hover.

**Comment by Keith-CY** [comment]
> > Another issue, as designed in UI ![image](https://user-images.githubusercontent.com/7271329/210869930-db87bcb6-0aa8-4f68-83c5-e44462ad8e54.png) `.bit Name` is displayed on hovering .bit icon, now the value of .bit name is displayed. It could be a misunderstanding in communication. ![image](https://user-images.githubusercontent.com/7271329/210870173-9316a5b7-9114-4acf-b301-570619282733.png) IMO, showing `magickbase.bit` on hovering .bit icon is redundant because `magickbase.bit` sits next to the icon
> 
> I'll remove this hover.

It's fine to show `.bit Name` because .bit icon is not known by all users.

**Comment by JeffreyMa597** [comment]
@zmcNotafraid @Naupio Could you please help to handle these missing parameters in these APIs? 
<img width="852" alt="image" src="https://user-images.githubusercontent.com/22511289/211249142-f5da02de-962f-47ad-a50c-5f863dc19eb2.png">

**Comment by JeffreyMa597** [comment]
PR:https://github.com/Magickbase/godwoken-explorer-ui/pull/857

**Comment by Naupio** [comment]
graphql had `account_udts` api and it also have `account` object subfield which include bit_alias

**Comment by Naupio** [comment]
`erc721_erc1155_holder_item` has `account` object too

**Comment by JeffreyMa597** [comment]
> graphql has `account_udts` api and it also has `account` object subfield which include bit_alias

@Naupio  I mean the HTTP request API was named `account_udts`,  it was used to query the data source of `holders`. 
<img width="800" alt="image" src="https://user-images.githubusercontent.com/22511289/211720666-48bce8da-a00c-4056-949e-49934b97869e.png">

and the `udt_id ` and `page` are used as the query parameters. They are different from the query parameters of graphql request API `account_udts`. 
<img width="800" alt="image" src="https://user-images.githubusercontent.com/22511289/211720565-c75d3c6e-741d-43bc-97d7-eadb09b43f87.png">

If there already exists this API, please let me know. Thanks a lot.

**Comment by JeffreyMa597** [comment]
> `erc721_erc1155_holder_item` has `account` object too

updated.
<img width="800" alt="image" src="https://user-images.githubusercontent.com/22511289/211722830-773c4536-5150-4a7e-8c07-737e7c82c079.png">

**Comment by Naupio** [comment]
erc721_inventory/erc1155_user_inventory add account object https://github.com/Magickbase/godwoken_explorer/issues/1273
