### ISSUE TITLE
feat: add minted count sorter for erc721_udts

### ISSUE THREAD

**Issue by Naupio** [Magickbase/godwoken_explorer#1173]
- [x] add new created_count/burnt_count (use for calculate minted_count) field for udt table
- [x] add auto wroker to update erc721 udt's created_count/burnt_count 
- [x] add unit testing for worker
- [x] add process history data trigger function
- [x] add erc721 minted sorter
- [x] unit testing for api

**Comment by Naupio** [comment]
pr link: https://github.com/Magickbase/godwoken_explorer/pull/1279

**Comment by Naupio** [comment]
testnet-prod was deployed @FrederLu

**Comment by FrederLu** [comment]
Verified.
