### ISSUE TITLE
[bug] finished withdrawal `state` from api.v1.gwscan.com/api/withdrawal_histories is still `pending`

### ISSUE THREAD

**Issue by Flouse** [Magickbase/godwoken_explorer#1187]
![image](https://user-images.githubusercontent.com/1297478/205198182-f6dd1a0f-21d4-41a2-a27b-30e734397e4f.png)
https://api.v1.gwscan.com/api/withdrawal_histories?owner_lock_hash=0xccec02450b770b50690565a3c97da86995e27b9a54c6e66aecf6fe1821a4f506&page=1

From the [owner_lock_hash](https://explorer.nervos.org/address/0xccec02450b770b50690565a3c97da86995e27b9a54c6e66aecf6fe1821a4f506), we could see that the withdrawal has arrived.
But the the withdrawal `state` from the GwScan API are still `pending`.

**Comment by zmcNotafraid** [comment]
It was caused by our ckb indexer data error.Now it's fixed.
