### ISSUE TITLE
Add token price or display token value in usd

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#1197]
GwScan is going to show users' assets in `usd`(us dollar), so there are going to have 4 updates.

1. price will be displayed on the token detail page, just below the `Total supply` field: https://v1.gwscan.com/token/111
2. a switch icon could be added in the `balance` column of erc 20 asset list on the account page to switch the displaying format of token balance(`amount` <=> `USD`). The column name turns to `USD` when the displaying format is `usd`: https://v1.gwscan.com/account/0xe7970ba16e4922e332ad8ca3650eed7d52cad4d0?tab=assets
3. add a toggle icon in the ERC 20 Transfer list(value column) on the account page: https://v1.gwscan.com/account/0xe7970ba16e4922e332ad8ca3650eed7d52cad4d0?tab=erc20
4. add a switch icon in the ERC 20 Transfer list(value column) on the token page: https://v1.gwscan.com/token/111

Note 1: `price` will be updated periodically so better to append a `(i)` with the `update at yyyy-MM-dd hh:mm:ss` message
Note 2: not every token has `price` info, so the `price` field could be hidden if the token doesn't have a price
Note 3: similar to note 2, if a token doesn't have a price, then the `value/balance` in assets list should be `-` when it's displayed in `usd`

UI has been updated at https://github.com/Magickbase/visual-style-guide/issues/14
API has been added by https://github.com/Magickbase/godwoken_explorer/pull/1158

Ref: https://github.com/Magickbase/godwoken_explorer/issues/1130

**Comment by qiweiii** [comment]
@Keith-CY  @Naupio, for the 

> Note 1: price will be updated periodically so better to append a (i) with the update at yyyy-MM-dd hh:mm:ss message

https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=67%3A1144&t=rcVb3GVFmSOhyYYf-1
![](https://user-images.githubusercontent.com/106060898/205494492-e0d4456b-68b6-4be6-a032-032c635b640a.png)

the update time is not provided by API, may need to add it

**Comment by Naupio** [comment]
token exchange rate object has timestamp subfield for display updated time
```elixir
  object :token_exchange_rate do
    field :symbol, :string, description: "Token symbol name."
    field :exchange_rate, :decimal, description: "Token exchange rate."
    field :timestamp, :integer, description: "Token last fetch timestamp(millisecond)."
  end
```

**Comment by qiweiii** [comment]
@Keith-CY in erc20 transfer list and asset list's `USD` column, do we need to calculate the USD value by multiplying with `exchange rate`? if this is the case, how many decimal place should I keep?

**Comment by Keith-CY** [comment]
> @Keith-CY in erc20 transfer list and asset list's `USD` column, do we need to calculate the USD value by multiplying with `exchange rate`? if this is the case, how many decimal place should I keep?

Sure, $$usd = price * amount$$ and the precision is 2.
