### ISSUE TITLE
Making the tooltip display the sentence without wrapping.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#1199]
Download button prompt message：
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/25676576/205485158-4b1edd3f-b8ed-4aad-971a-df56ed395356.png">

Contract page identification prompt information：
<img width="741" alt="image" src="https://user-images.githubusercontent.com/25676576/205485198-d2bf4927-7337-417a-8658-20d21ae91582.png">
<img width="920" alt="image" src="https://user-images.githubusercontent.com/25676576/205485204-553bc724-b58a-4bd8-8aae-992918632a1b.png">

All prompt information on the home page：
<img width="712" alt="image" src="https://user-images.githubusercontent.com/25676576/205485221-6837fee5-7d32-4129-8265-2d8df8f65473.png">
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/25676576/205485230-727ae0b0-bd98-45d6-b09a-c996ea70b2d5.png">

Is the above hint optimized to display sentences without wrapping?

**Comment by Keith-CY** [comment]
PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/872
