### ISSUE TITLE
Bug: raise error when call smart_contracts api with cursor of null field(name field of smart_contract)

### ISSUE THREAD

**Issue by Naupio** [Magickbase/godwoken_explorer#1214]

**Comment by Naupio** [comment]
testnet-stg was deployed
```
query {
  smart_contracts(
    input: {
      after: "g3QAAAACZAACaWRhGmQABG5hbWVtAAAAAA=="
      sorter: [
        { sort_type: ASC, sort_value: ID }
        { sort_type: ASC, sort_value: NAME }
      ]
    }
  ) {
    entries {
      name
      account_id
      account {
        eth_address
      }
    }
    metadata {
      total_count
      after
      before
    }
  }
}

```
{
  "data": {
    "smart_contracts": {
      "entries": [
        {
          "account": {
            "eth_address": "0x21ca43b2d62d625f7ea7536581524beee911592f"
          },
          "account_id": 60303,
          "name": ""
        },
        {
          "account": {
            "eth_address": "0x403a0e592d73e63e9bf2c5f9f5571f25ae58dadd"
          },
          "account_id": 60306,
          "name": ""
        },
        {
          "account": {
            "eth_address": "0x80db9456e2184d5c10b77fe8fc2f531f6742c5f3"
          },
          "account_id": 60301,
          "name": ""
        },
        {
          "account": {
            "eth_address": "0x23aaf6820b41e7d5a7ece8572338592fdb6340b6"
          },
          "account_id": 60305,
          "name": ""
        },
        {
          "account": {
            "eth_address": "0x9418fd9b280075bf47caa6970f1f0626691fa78d"
          },
          "account_id": 60300,
          "name": ""
        },
        {
          "account": {
            "eth_address": "0xa1007730e06447e7d59c1e97514d4217a19dff76"
          },
          "account_id": 60298,
          "name": ""
        },
        {
          "account": {
            "eth_address": "0x31d56c1cdc01dd6a5684b0f1e2341f538af711ba"
          },
          "account_id": 60299,
          "name": ""
        },
        {
          "account": {
            "eth_address": "0x9b9d2a162fea2ab9b2834ff4f35c14b008e2d7b5"
          },
          "account_id": 60294,
          "name": ""
        },
        {
          "account": {
            "eth_address": "0x6e4d391858baae67b5308b2620b4c40535fea110"
          },
          "account_id": 60296,
          "name": ""
        },
        {
          "account": {
            "eth_address": "0x1c7962e9cde166e734ed05fe6754491cb9e0faba"
          },
          "account_id": 60292,
          "name": ""
        },
        {
          "account": {
            "eth_address": "0xf206aeca0aa1039eb46782142a4f3ffda306c26b"
          },
          "account_id": 60293,
          "name": ""
        },
        {
          "account": {
            "eth_address": "0x12883f99d56530a521decdd77d675a0f3bbcdd19"
          },
          "account_id": 60297,
          "name": ""
        },
        {
          "account": {
            "eth_address": "0x54e4295f22fc90f5fa0141356bac2a0ba0d7c8f4"
          },
          "account_id": 60291,
          "name": ""
        },
        {
          "account": {
            "eth_address": "0xa1834198056e9a87d0ec782c5fe4a1512b30dc06"
          },
          "account_id": 60295,
          "name": ""
        },
        {
          "account": {
            "eth_address": "0x614a51ae23dfb0e60e89875f3e541b38e10487d9"
          },
          "account_id": 60288,
          "name": ""
        },
        {
          "account": {
            "eth_address": "0x069cb988f0295e4e4aaa884bda3173417a13f669"
          },
          "account_id": 60290,
          "name": ""
        },
        {
          "account": {
            "eth_address": "0x6e7a30d4fe4466cb78ff81c061b25f3af34081c4"
          },
          "account_id": 60289,
          "name": ""
        },
        {
          "account": {
            "eth_address": "0x3f1dcbc6a90bf6ecf6ab412f434b71b9cee8cff6"
          },
          "account_id": 60286,
          "name": ""
        },
        {
          "account": {
            "eth_address": "0xbfdb80642d8dd769f5b5662a91b99082adaba81c"
          },
          "account_id": 60284,
          "name": ""
        },
        {
          "account": {
            "eth_address": "0x82bcbc27e39c6b159e1c6aaa5349880cc2c13f7a"
          },
          "account_id": 60285,
          "name": ""
        }
      ],
      "metadata": {
        "after": "g3QAAAACZAACaWRhLWQABG5hbWVtAAAAAA==",
        "before": "g3QAAAACZAACaWRhGmQABG5hbWVtAAAAAA==",
        "total_count": 10000
      }
    }
  }
}
```

```

**Comment by FrederLu** [comment]
Verified.
