### ISSUE TITLE
The background color of the tooltip needs to be `#000000`.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#1216]
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/25676576/206907041-899660e5-aafd-4358-9e87-6206e04ffb70.png">
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/25676576/206907325-04b00c21-2a51-445b-8fe6-e45b72c5f8d8.png">
<img width="720" alt="image" src="https://user-images.githubusercontent.com/25676576/206907596-99977a00-6e0b-49cf-9b02-59ba462c0f20.png">
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/25676576/206907074-bc44f0ea-4649-4fb6-b0d0-a3ccc39be2c5.png">

The light color appears in the individual list, which can be unified as `#000000`, if it is global, it can be modified at one time.

**Comment by JeffreyMa597** [comment]
PR:https://github.com/Magickbase/godwoken-explorer-ui/pull/784
