### ISSUE TITLE
Tooltips are not visible on mobile.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#1219]
<img width="738" alt="image" src="https://user-images.githubusercontent.com/25676576/206908845-5b8a1855-fd87-41b8-b60f-0985b125d7ef.png">
<img width="341" alt="image" src="https://user-images.githubusercontent.com/25676576/207793158-8e62a248-39b3-4864-bddd-de5d02ccca90.png">

The tooltips here have a relatively large impact.
In fact, other tooltips on the page have problems on the mobile terminal, so they can be dealt with in a unified manner.

**Comment by Keith-CY** [comment]
![image](https://user-images.githubusercontent.com/7271329/207790863-9e2b3cfb-5b39-47d8-bd37-689deaaad0c1.png)

The tooltip of token price is visible on my phone, while the tooltip of assets in the list is invisible

**Comment by qiweiii** [comment]
Not only on this page. All material ui tooltip may have this issue.
I tried to use our tooltip classname, but cannot make it stay on top inside lists.
So need to try to fix this in components/Tooltip
