### ISSUE TITLE
Wrong format eth address also display page

### ISSUE THREAD

**Issue by zmcNotafraid** [Magickbase/godwoken_explorer#1225]
correct eth_address: 0x79fa5e95c5cc7f5d110a464ee9ea40780b93ac0a
we decrease one char: 0x79fa5e95c5cc7f5d110a464ee9ea40780b93ac0.
But also display account page when visit [url](v1.testnet.gwscan.com/account/0x79fa5e95c5cc7f5d110a464ee9ea40780b93ac0)
![image](https://user-images.githubusercontent.com/12708910/208011648-e21f37b4-4011-4dce-8d0a-26b4180239d0.png)

**Comment by JeffreyMa597** [comment]
@zmcNotafraid Please give me a full screenshot containing some more information, such as `URL`, etc.

**Comment by JeffreyMa597** [comment]
> When you visit https://v1.testnet.gwscan.com/account/0x79fa5e95c5cc7f5d110a464ee9ea40780b93ac0. It's not a correct eth address,but also can display.

@Naupio @zmcNotafraid 
The graphql request is success, but we got an error. 

<img width="1356" alt="image" src="https://user-images.githubusercontent.com/22511289/208032105-cef3a573-8a74-4e7b-9e9d-6a9522f7ee67.png">

**Comment by Naupio** [comment]
the input field of script hash is a invalid type, not compatible of `script_hash` type which is `hash_full`

```
message | "Argument  \"input\" has invalid value {script_hash: $script_hash, address:  $address}.\nIn field \"script_hash\": Expected type \"HashFull\", found  $script_hash."
```

**Comment by Naupio** [comment]
@JeffreyMa597  hash full is `A 32-byte [KECCAK-256](https://en.wikipedia.org/wiki/SHA-3) hash.`

**Comment by JeffreyMa597** [comment]
@Kirl70 Please help to design an error message.

**Comment by Kirl70** [comment]
> @Kirl70 Please help to design an error message beside the eth_address. Thx

Design Draft:

PC https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=9158%3A32271&t=9cVjv7wlAYVixl66-1
<img width="920" alt="image" src="https://user-images.githubusercontent.com/106060898/208116651-5172cd7b-96fd-485c-8c71-af832686379c.png">

Mobile https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=9156%3A31592&t=9cVjv7wlAYVixl66-1
<img width="217" alt="image" src="https://user-images.githubusercontent.com/106060898/208116996-4c2aa6fc-0a15-4411-8312-ed9425450dbb.png">

**Comment by JeffreyMa597** [comment]
@zmcNotafraid  @Naupio Please have a look at this issue. Thx. 
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/22511289/209837502-48dec306-cb8a-4c85-95e7-494579f4b5a5.png">
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/22511289/209837591-adcec60c-ea4b-465a-a919-a4a14705cf97.png">

**Comment by Naupio** [comment]
testnet-stg `account` api return an `account_or_address` type which is union type

**Comment by JeffreyMa597** [comment]
PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/860

**Comment by JeffreyMa597** [comment]
@zmcNotafraid 
I wondered whether it is expected or not when we type the wrong address but can get transaction data.

<img width="1330" alt="image" src="https://user-images.githubusercontent.com/22511289/211787252-e7a8041e-47e2-4b1e-b139-2e3977bd14fb.png">

**Comment by FrederLu** [comment]
Verified.
