### ISSUE TITLE
To add an eth_hash to the polyjuice_creator object

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#1229]
In order to solve the problem that the front end requests no data when using `to_eth_address` with script hash in filtering.seems backend doesn't support this kind of hash address in from_eth_address or to_eth_address.

![Image](https://user-images.githubusercontent.com/25676576/209748366-31db0035-c1a7-4920-b4dd-78f1b952694c.png)

https://github.com/Magickbase/godwoken-explorer-ui/pull/740#issuecomment-1358849161

**Comment by Naupio** [comment]
@FrederLu 
when transcation type is `polyjuice_creator`, seems not have eth_hash

**Comment by Naupio** [comment]
this feature no need more
