### ISSUE TITLE
 `To` does not show the .bit alias for internal transactions.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#1240]
In the transaction list, both from/to are `0xcc0af0af911dd40853b8c8dfee90b32f8d1ecad6`, but to does not display the .bit alias.
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/25676576/209639943-8e0340b1-41c0-413a-bc74-fbcc619b6c5e.png">
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/25676576/209640813-ab85b045-08ef-43b9-9349-9cad105bf3e1.png">

**Comment by zmcNotafraid** [comment]
@JeffreyMa597  Transaction type with polyjuice have an `native_transfer_address` object and has an attribute `bit_alias`

**Comment by zmcNotafraid** [comment]
- [ ] token_transfer type needs merge to mainnet

**Comment by JeffreyMa597** [comment]
Have been used in this PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/805

**Comment by FrederLu** [comment]
After the internal transaction is found through verification, `To` still does not display the .bit name on the page (alias has been set).
Please confirm again.

**Comment by zmcNotafraid** [comment]
```
query {
      transaction(
        input: {
          eth_hash: "0x792b9e5a374fca613c8b1006685b3da803382953453f9d703abbf6b303d3cee9"
        }
      ) {
        polyjuice {
          native_transfer_account {
            eth_address
            bit_alias
          }
        }
      }
    }
```
@JeffreyMa597  You need to use `bit_alias` instead of to_account address in transaction list page if bit_alias is not null.

**Comment by JeffreyMa597** [comment]
Have been used in this PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/857

**Comment by FrederLu** [comment]
Stagingverified.
