### ISSUE TITLE
two transactions have been pending confirmation longtime

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#1248]
https://v1.testnet.gwscan.com/zh-CN/address/0xe05d380839f32bc12fb690aa6fe26b00bd982613
![image](https://user-images.githubusercontent.com/32102187/210060670-90346f75-389a-435d-a81a-0f89d1fb7e67.png)

**Comment by Keith-CY** [comment]
These 2 transactions were in mempool but discarded finally, so they could be removed from the (pending)transaction list

**Comment by zmcNotafraid** [comment]
![image](https://user-images.githubusercontent.com/12708910/210289024-18056260-c31d-49b0-aa9b-495878b68bce.png)
The data was created long ago.So remove them.
