### ISSUE TITLE
Loading of account overview is displayed periodically

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#1255]
https://user-images.githubusercontent.com/7271329/210551677-22c29976-3558-42d8-9e64-0bc0d895b733.mov

It only happens in testnet production

Only the loading on mount is necessary, and values could be updated seamlessly without a loading on refreshing

**Comment by JeffreyMa597** [comment]
PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/843

**Comment by FrederLu** [comment]
verified.
