### ISSUE TITLE
Price of `YOK` is incorrect

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#1260]
![image](https://user-images.githubusercontent.com/7271329/210872910-898e386c-9cd7-49c1-89f3-cfcec8eebb26.png)
Yokai is not tracked by coinmarkcap

**Comment by zmcNotafraid** [comment]
- KOI sames as YOK

**Comment by Keith-CY** [comment]
Will add a checkbox of showing price in admin panel
