### ISSUE TITLE
The `value` displayed a wrong number in transaction list page.

### ISSUE THREAD

**Issue by JeffreyMa597** [Magickbase/godwoken_explorer#1263]
The `value` displayed a wrong number in transaction list page. 
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/22511289/210927891-c41f21df-0bdb-4aeb-8663-99fdaf1d8201.png">

**Comment by JeffreyMa597** [comment]
PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/850

**Comment by FrederLu** [comment]
verified.
