### ISSUE TITLE
HNFT

### ISSUE THREAD

**Issue by huntingnft** [Magickbase/godwoken_explorer#1266]
### Token Name

HNFT

### Description

HuntingNFT is an original GameFi project initiated by Nervos global community volunteers. By combining infrastructures such as UniPass, Godwoken, YokaiSwap, NervosDao, etc in the Nervos ecosystem, combined with the team's original GameFi design and keep exploring, it aims to create more P2E GameFi and value that are deployed on Nervos public and cross chain. HuntingNFT has received a grant from Nervos Foundation now.

### Max Supply

1000000000

### Website

https://huntingnft.cc/

### Logo URI

https://huntingnft.cc/hnft.png

### Contract Address

0x6ebddbe3dfd546f527f31bb8902662c7cc1de347

### Code Format

None

**Comment by Keith-CY** [comment]
Token info has been updated on https://v1.gwscan.com/zh-CN/token/11113
