### ISSUE TITLE
 The page prompts Cannot read property (read 'type') of undefined.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#1271]
https://v1.testnet.gwscan.com/account/0xd1667cbf1cc60da94c1cf6c9cfb261e71b6047f7?tab=bridged
<img width="777" alt="image" src="https://user-images.githubusercontent.com/25676576/211504865-96d0c6b6-65e4-41a0-9569-987690a58d02.png">
<img width="785" alt="image" src="https://user-images.githubusercontent.com/25676576/211505073-f4f71afb-7443-46da-92f0-5a857ea3b60b.png">
The test environment will prompt `Cannot read properties of undefined (reading 'type')` when the network is abnormal.

**Comment by Keith-CY** [comment]
It's possibly caused by a network issue that an empty data is returned, the error is thrown because empty data is not handled properly

**Comment by JeffreyMa597** [comment]
<img width="1522" alt="image" src="https://user-images.githubusercontent.com/22511289/220392153-99c89ebe-324f-4fec-8656-ece9b46ee8cb.png">
The page didn't crash.
