### ISSUE TITLE
Query account eth address by bit alias

### ISSUE THREAD

**Issue by zmcNotafraid** [Magickbase/godwoken_explorer#1272]
query from das indexer. Support multiple query once.

**Comment by zmcNotafraid** [comment]
das indexer request don't support multiple request: https://github.com/dotbitHQ/das-account-indexer/blob/aab86e1a8a278224e0eb497fef5e3674a0cc24f8/http_server/handle/account_info.go#L50

**Comment by Keith-CY** [comment]
Querying address by .bit name has been supported on testnet

```sh
## .bit name
curl -X "POST" "https://api.v1.betanet.gwscan.com/graphql" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
	"query": "query{search_bit_alias(input:{bit_alias:\\"freder.bit\\"})}",
	"variables": {}
}'
```
please update in the front-end @JeffreyMa597

**Comment by JeffreyMa597** [comment]
@Keith-CY  Have been tracked in this PR. 
https://github.com/Magickbase/godwoken-explorer-ui/pull/857

**Comment by FrederLu** [comment]
Verified.
