### ISSUE TITLE
Holder data will not be updated after burning tokens.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#1284]
After the ERC 721 token is destroyed, the holder data is not updated.
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/25676576/212882908-e75fa8fd-51a1-4637-b8b6-4c2bcf021e53.png">
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/25676576/212883466-9b75209e-d0fa-4458-9996-a8c787ce28ba.png">

**Comment by Naupio** [comment]
contract address `0xf02de15eb840d5db74d2c457640421ed74ad08c5`

**Comment by Naupio** [comment]
link blockscout version
https://gw-explorer.nervosdao.community/address/0x78c88768b72DB425836aE8abe93d35593F0d680c
https://gw-explorer.nervosdao.community/token/0x78c88768b72DB425836aE8abe93d35593F0d680c/inventory

**Comment by Naupio** [comment]
@zmcNotafraid 
erc721 balances_of rpc api will return the owner's token_id count which we use to check save value in udt_balance table.
in this scenario, if a user minted two or more nft(ex: nft-1 nft-2) and then burnt nft-1 token, the balance_of api will return value with 1 which in our architecture will cause return invalid owner of nft-1, blocksout also has this error

we can fix this error with adding new table to save current erc721 owner state, and update it will token transfer log, not need use balance_of api any more(only erc721 token transfer)

I will fix with this sub-step:
1. add new table for store erc721 owner state which replace current_udt_balance table
2. change update balance step of erc721 transfter
3. add task to process history data

**Comment by Keith-CY** [comment]
> @zmcNotafraid erc721 balances_of rpc api will return the owner's token_id count which we use to check save value in udt_balance table. in this scenario, if a user minted two or more nft(ex: nft-1 nft-2) and then burnt nft-1 token, the balance_of api will return value with 1 which in our architecture will cause calculate invalid owner of nft-1, blocksout also has this error
> 
> we can fix this error with adding new table to save current erc721 owner state, and update it will token transfer log, not need use balance_of api any more(only erc721 token transfer)
> 
> I will fix with this sub-step:
> 
> 1. add new table for store erc721 owner state which replace current_udt_balance table
> 2. change update balance step of erc721 transfter
> 3. add task to process history data
> 4. reimplement erc721  related graphql api

Is there a similar issue of erc1155 token?

**Comment by Naupio** [comment]
> > @zmcNotafraid erc721 balances_of rpc api will return the owner's token_id count which we use to check save value in udt_balance table. in this scenario, if a user minted two or more nft(ex: nft-1 nft-2) and then burnt nft-1 token, the balance_of api will return value with 1 which in our architecture will cause calculate invalid owner of nft-1, blocksout also has this error
> > we can fix this error with adding new table to save current erc721 owner state, and update it will token transfer log, not need use balance_of api any more(only erc721 token transfer)
> > I will fix with this sub-step:
> > 
> > 1. add new table for store erc721 owner state which replace current_udt_balance table
> > 2. change update balance step of erc721 transfter
> > 3. add task to process history data
> > 4. reimplement erc721  related graphql api
> 
> Is there a similar issue of erc1155 token?

erc1155 use different sync strategy, so it doesn't has the same problem

**Comment by Naupio** [comment]
testnet-stg was deployed @FrederLu 
fix pr link: #1344 

optimize pr link: #1345

**Comment by Naupio** [comment]
example link: https://godwoken-explorer-ui-development.vercel.app/nft-collection/0x78c88768b72db425836ae8abe93d35593f0d680c?tab=holders

**Comment by Naupio** [comment]
need process history data

**Comment by FrederLu** [comment]
The Testnet env is verified.
