### ISSUE TITLE
The assets interface data is not updated when an nft item is burnt

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#1286]
After the token is destroyed, the assets interface data is not updated.
<img width="505" alt="image" src="https://user-images.githubusercontent.com/25676576/212896435-56d0e6b4-c8b0-46aa-be18-f87418de8075.png">

https://godwoken-explorer-2c6ln4cjd-magickbase.vercel.app/account/0xcc0af0af911dd40853b8c8dfee90b32f8d1ecad6?tab=erc-721-assets
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/25676576/212896074-2ea89d9f-3da5-41c0-a67f-c81a5169a9fc.png">

https://godwoken-explorer-2c6ln4cjd-magickbase.vercel.app/nft-item/0xf02de15eb840d5db74d2c457640421ed74ad08c5/8
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/25676576/212895959-4dd3f907-54ef-418c-9cfa-0b4d9b925969.png">

**Comment by Naupio** [comment]
pr link: #1334

**Comment by FrederLu** [comment]
When 2 tokens are minted through one contract, the first token cannot be burned.
https://v1.testnet.gwscan.com/zh-CN/account/0x1a9a8e69246896ac1720c1f407309c142c5c3cdc?tab=erc-721-assets
![Image](https://user-images.githubusercontent.com/25676576/221104174-d11389e5-87bd-4230-b6c2-28a93081782b.png)
![Image](https://user-images.githubusercontent.com/25676576/221104211-5c50f439-b5d5-45ea-b05d-02dfcf82c482.png)

**Comment by Naupio** [comment]
pr link: https://github.com/Magickbase/godwoken_explorer/pull/1349

**Comment by FrederLu** [comment]
Testnet env is verified.
