### ISSUE TITLE
feat: bit api enhancement 

### ISSUE THREAD

**Issue by Naupio** [Magickbase/godwoken_explorer#1288]
dot bit api: https://github.com/dotbitHQ/das-account-indexer/blob/main/API.md

- [x] refactor search bit alias api with  https://github.com/dotbitHQ/das-account-indexer/blob/main/API.md#get-account-records-info-v2
- [x] add reverse search bit api
- [x] refactor bit api http client to telsa with mint adpator
- [x] add batch fetch api
- [x] add reverse batch fetch api
- [x] add unit testing code with mock

**Comment by Naupio** [comment]
pr link: https://github.com/Magickbase/godwoken_explorer/pull/1290

**Comment by Naupio** [comment]
example1:
```graphql
    query{
      batch_fetch_addresses_by_aliases(
        input: {
          bit_aliases: ["freder.bit"]
        }
      )
      {
        address
        bit_alias
      }
    }
```

example2:
```graphql
    query{
      batch_fetch_aliases_by_addresses(
        input: {
          addresses: ["0xcc0af0af911dd40853b8c8dfee90b32f8d1ecad6"]
        }
      )
      {
        address
        bit_alias
      }
    }
```

**Comment by zmcNotafraid** [comment]
did indexer doesn't support multiple params, research result: https://github.com/Magickbase/godwoken_explorer/issues/1272#issuecomment-1378313766

**Comment by Naupio** [comment]
> did indexer doesn't support multiple params, research result: [#1272 (comment)](https://github.com/Magickbase/godwoken_explorer/issues/1272#issuecomment-1378313766)
seems work
```graphql
query {
  batch_fetch_addresses_by_aliases(input: { bit_aliases: ["freder.bit", "hello.bit"] }) {
    address
    bit_alias
  }
}
```
```
{
  "data": {
    "batch_fetch_addresses_by_aliases": [
      {
        "address": "0xcc0af0af911dd40853b8c8dfee90b32f8d1ecad6",
        "bit_alias": "freder.bit"
      },
      {
        "address": "0x38401c6364bfd05c45ceefccc3b75e33fa815815",
        "bit_alias": "hello.bit"
      }
    ]
  }
}
```

**Comment by zmcNotafraid** [comment]
> > did indexer doesn't support multiple params, research result: [#1272 (comment)](https://github.com/Magickbase/godwoken_explorer/issues/1272#issuecomment-1378313766)
> 
> seems work
> 
> ```graphql
> query {
>   batch_fetch_addresses_by_aliases(input: { bit_aliases: ["freder.bit", "hello.bit"] }) {
>     address
>     bit_alias
>   }
> }
> ```
> 
> ```json
> {
>   "data": {
>     "batch_fetch_addresses_by_aliases": [
>       {
>         "address": "0xcc0af0af911dd40853b8c8dfee90b32f8d1ecad6",
>         "bit_alias": "freder.bit"
>       },
>       {
>         "address": "0x38401c6364bfd05c45ceefccc3b75e33fa815815",
>         "bit_alias": "hello.bit"
>       }
>     ]
>   }
> }
> ```

my mistake. I see that you use `/v1/batch `... api. So you need to check `batch_fetch_aliases_by_addresses `api again

**Comment by Naupio** [comment]
reverse example
```graphql
query {
  batch_fetch_aliases_by_addresses(
    input: {
      addresses: [
    "0xcc0af0af911dd40853b8c8dfee90b32f8d1ecad6",
    "0x38401c6364bfd05c45ceefccc3b75e33fa815815"
      ]
    }
  ) {
    address
    bit_alias
  }
}
```
```json
{
  "data": {
    "batch_fetch_aliases_by_addresses": [
      {
        "address": "0xcc0af0af911dd40853b8c8dfee90b32f8d1ecad6",
        "bit_alias": "freder.bit"
      },
      {
        "address": "0x38401c6364bfd05c45ceefccc3b75e33fa815815",
        "bit_alias": "mybit.bit"
      }
    ]
  }
}
```

**Comment by Naupio** [comment]
add  reverse serch bit_alias api
```graphql
      query{
        reverse_search_bit_alias(
          input: {
            address: "0xcc0af0af911dd40853b8c8dfee90b32f8d1ecad6"
          }
        )
      }
```

**Comment by Naupio** [comment]
when testing the dot bit api, we found that
```
https://data.did.id/hello.bit
https://data.did.id/mybit.bit
```
are binding in the same address

and then we testing reverse api found that the 'hello.bit' binding address will return 'mybit.bit' 

![image](https://user-images.githubusercontent.com/12268276/215388110-fd2c954e-6832-467c-bbbc-deb5c558c82a.png)

**Comment by Naupio** [comment]
testnet-prod was deployed

**Comment by FrederLu** [comment]
Verified.
