### ISSUE TITLE
「Order by txn desc」needed when loading Registered Contracts list

### ISSUE THREAD

**Issue by yixyxiu** [Magickbase/godwoken_explorer#1293]
Now, this Registered Contracts list is sorted by id in asc order by default, however, when one looks at this list, one would prefer to see what contracts have more transactions.
![Registered Contracts](https://user-images.githubusercontent.com/87553548/213915822-194f95c9-b2c7-4479-a5d5-3ec5727c2777.png)

**Comment by Keith-CY** [comment]
This feature is going to be delivered by PR https://github.com/Magickbase/godwoken-explorer-ui/pull/735
