### ISSUE TITLE
Deploy tx of an contract was not recognized

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#1310]
Contract https://v1.gwscan.com/account/0x734ba3e711a22a383c1a26dbe5d529cfb793c3bf
![image](https://user-images.githubusercontent.com/7271329/216773897-7a60a0b0-dd93-4d86-8b9c-1b584ef84bc1.png)

**Comment by Keith-CY** [comment]
This contract is probably deployed by a contract factory

**Comment by zmcNotafraid** [comment]
deploy tx hash: https://v1.testnet.gwscan.com/zh-CN/tx/0x952d4918add14076a0a09bbb31acb11b47da92347f0ffc8b214c8c0fd31f7629
