### ISSUE TITLE
bug:unable to parse gasless transactions

### ISSUE THREAD

**Issue by sunchengzhu** [Magickbase/godwoken_explorer#1329]
Recent gasless transactions cannot be parsed as `User Operations`, such as [this transaction](https://v1.betanet.gwscan.com/tx/0xc2e2c0141231ae0d544956ef977d8ca328d44134c431c57f71dcb47f71a86fcd).
[The gasless transaction more than one month ago](https://v1.testnet.gwscan.com/tx/0xe83e9ae5d3194fa27a5485f3cf5e0abddd264dc6a04a43d7bfffd45e157db207) was successfully parsed.

**Comment by FrederLu** [comment]
Hi,
Seeing that the link to the page with the problem you reported is https://v1.betanet.gwscan.com/tx/0xc2e2c0141231ae0d544956ef977d8ca328d44134c431c57f71dcb47f71a86fcd, I suggest you visit https://v1.testnet.gwscan.com/tx/0xc2e2c0141231ae0d544956ef977d8ca328d44134c431c57f71dcb47f71a86fcd.

**Comment by sunchengzhu** [comment]
> Hi, @sunchengzhu Seeing that the link to the page with the problem you reported is https://v1.betanet.gwscan.com/tx/0xc2e2c0141231ae0d544956ef977d8ca328d44134c431c57f71dcb47f71a86fcd, I suggest you visit https://v1.testnet.gwscan.com/tx/0xc2e2c0141231ae0d544956ef977d8ca328d44134c431c57f71dcb47f71a86fcd.

Sorry, it was my mistake. I configured wrong blockchain explorer url on metamask.
