### ISSUE TITLE
The tokenid displayed in the active tab is abnormal.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#1335]
The `Token ID` in the page should be unique, and the interface data is normal.
https://v1.testnet.gwscan.com/zh-CN/nft-collection/0xb78e53b2f06e9e1d302ee6e35a482f586d4cc4e3?tab=activity
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/25676576/220510621-92fb9042-3ad7-4796-a465-7236ffbb44ab.png">

**Comment by JeffreyMa597** [comment]
PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/915
