### ISSUE TITLE
Some pages are displayed abnormally online. 

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#1353]
https://v1.gwscan.com/zh-CN/nft-collection/0x9cdda01e00a5a425143f952ee894ff99b5f7999f
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/25676576/224258081-3549bb60-cb7f-448c-9ae3-73bb061274e0.png">

These links are also abnormal：
https://v1.gwscan.com/zh-CN/nft-collection/0x348c854e36e57c2d78d6f3bd92cae4108ec64c34
https://v1.gwscan.com/zh-CN/multi-token-collection/0x42b28e2dc1843a636347c1d521d08711ac18b2fb

**Comment by JeffreyMa597** [comment]
PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/926

**Comment by FrederLu** [comment]
Verified.

**Comment by FrederLu** [comment]
The previous prompt was fixed, but another prompt appeared on the same page.
https://v1.gwscan.com/zh-CN/nft-collection/0x9cdda01e00a5a425143f952ee894ff99b5f7999f

![Image](https://user-images.githubusercontent.com/25676576/227835593-0d9149c4-7f66-4042-8035-b3df8a5a4407.png)

**Comment by Naupio** [comment]
fixed: 
<img width="1318" alt="image" src="https://user-images.githubusercontent.com/12268276/233520716-ad4cb83f-1b18-47ac-95c4-026bc657df83.png">
