### ISSUE TITLE
Cannot read properties of undefined (reading 'account') 

### ISSUE THREAD

**Issue by Flouse** [Magickbase/godwoken_explorer#1398]
<img width="918" alt="image" src="https://user-images.githubusercontent.com/1297478/229260494-2989d549-7df7-4ad0-aae7-c1284a7d669a.png">
https://v1.gwscan.com/account/0xbff03d3d83caeeea070e547b97d92f8f6fd48177?tab=erc-1155-assets

## related issue
- https://github.com/Magickbase/godwoken_explorer/issues/355

**Comment by FrederLu** [comment]
This is a known issue and we are working to fix it.
https://github.com/Magickbase/godwoken_explorer/issues/1353
