### ISSUE TITLE
[Native ERC20 Token] **BOBUCK**

### ISSUE THREAD

**Issue by specmeup** [Magickbase/godwoken_explorer#1424]
### Token Name

$bobuck

### Description

**What are $bobuck's?**
$bobuck's, or $bobuck, is the official currency of the Build-Off, an event that brings developers together to build decentralized applications (dApps) on the Nervos Network. The token is intended to incentivize and reward both developers and users for building and contributing to the Nervos ecosystem. 

**A lightning fast L2 native token issued on the Nervos Network.** 
As a utility token, $bobuck  can be used for various purposes, such as payment, transaction fees, staking, and voting rights for governance decisions. Its total inflated supply makes it affordable for longer, which is ideal for a wide range of DAPP use cases. As part of the Build-Off requirements, developers should integrate $bobuck and $ckb into their dApps to create economic incentives for users and drive adoption and usage of their applications.

**Tokenomics:**
$bobuck's total supply is 1 trillion tokens. 40% of the supply, or 400 billion tokens, will be allocated to an Initial Coin Offering (ICO) through a decentralized exchange (DEX), which will be announced at a later date. Another 40% of the supply, or 400 billion tokens, will be added to match the funds raised during the ICO. This approach ensures a fair distribution of the token and provides an opportunity for early adopters to participate in the ecosystem.

10% of the total supply, or 100 billion tokens, will be allocated to the development and marketing team, ensuring the long-term sustainability of the project and its success in the competitive cryptocurrency market. 10% of the total supply, or 100 billion tokens, will be allocated to airdrops and Build Off-related dynamics, which will help to incentivize users to participate in the platform and contribute to its growth.

Whether you're a developer looking to build on Nervos or a user seeking to benefit from the platform's services, The Build OFF can help you achieve your goals within the Nervos ecosystem.

### Max Supply

1000000000000

### Website

https://buildoff.site

### Logo URI

https://i.ibb.co/54RWG9Q/build-off-buck.png

### Contract Address

0x26dbf02d12721f2579d8a6dbdc60a318608e6d57

### Code Format

None

**Comment by zmcNotafraid** [comment]
https://v1.gwscan.com/zh-CN/token/12150 @specmeup

**Comment by zmcNotafraid** [comment]
> Need to update the reference on the description from L1 to L2

So what is your layer1 sudt's script args or script hash?

**Comment by specmeup** [comment]
> > Need to update the reference on the description from L1 to L2
> 
> Please submit layer1 sudt's script args or script hash?

No need, what I meant was that i´ve updated the "description", should be just a matter of publishing.
