### ISSUE TITLE
[Native ERC20 Token] **Trans INU**

### ISSUE THREAD

**Issue by specmeup** [Magickbase/godwoken_explorer#1438]
### Token Name

trans

### Description

Trans INU is a community-driven project launched on the Nervos Network, designed to bring vibrancy and dynamism to the network ecosystem. With its token symbol, $trans, the project aims to foster a thriving community that actively engages with the network and contributes to its growth and development.

Trans INU serves as a catalyst for collaboration and innovation, bringing together individuals from diverse backgrounds to share their expertise and ideas. By leveraging the blockchain technology of the Nervos Network, this project empowers community members to connect, exchange knowledge, and collectively contribute to the network's evolution.

$trans represents more than just a cryptocurrency; it embodies the spirit of collaboration and collective progress. By actively participating in the Trans INU ecosystem, individuals not only have the potential for financial growth but also play a vital role in shaping the future of the Nervos Network.

Through its engaging and dynamic nature, Trans INU injects excitement and vitality into the blockchain space. By fostering a community-driven approach, the project encourages active participation, innovation, and the exploration of new possibilities within the network.

Join Trans INU today and become an integral part of a dynamic global community that thrives on collaboration and collective progress. Together, we can shape the future of the Nervos Network, driving its growth, and creating an ecosystem that embraces innovation and community-driven initiatives. Let's embark on this transformative journey with $trans, and together, we'll make a lasting impact on the network and reshape the future of blockchain technology.

### Max Supply

250000000000000

### Website

http://www.transinu.me

### Logo URI

https://i.ibb.co/qdQKG7B/8-i-AVv1q-Tr-Cb-Jrctp.png

### Contract Address

0xab7843a30989ddf7a1b07204db73eef6d7c5d345

### Code Format

None

**Comment by zmcNotafraid** [comment]
https://v1.gwscan.com/zh-CN/token/12175

**Comment by specmeup** [comment]
Made changes to "Logo URL" and "Description".

**Comment by specmeup** [comment]
Update rerquested on issue https://github.com/Magickbase/godwoken_explorer/issues/1445
