### ISSUE TITLE
[Native ERC20 Token] RUN

### ISSUE THREAD

**Issue by 57u** [Magickbase/godwoken_explorer#1450]
### Token Name

RUN

### Description

The original CKB meme, $RUN. #RUNCKB

### Website

https://run.ckbees.app

### Logo URI

https://ipfs-2.thirdwebcdn.com/ipfs/QmXcuz3bwjjF9GA4F9R9F2P2MqqTTba6LnCaqDw5fTKf9u/runckb.png

### Contract Address

0x36B4e2660A17777B3819E13cC55D541e8bfb87d8

### Code Format

solidity single file (Default)

**Comment by zmcNotafraid** [comment]
https://v1.gwscan.com/zh-CN/token/12187 @57u
