### ISSUE TITLE
[Native ERC20 Token - UPDATE] **Trans🐾INU** #1445

### ISSUE THREAD

**Issue by specmeup** [Magickbase/godwoken_explorer#1460]
### Token Name

trans

### Description

Former token of the transinu project. Total supply burned. 
Read article for more insight: https://medium.com/@transinu/trans-token-discontinued-making-way-for-transinu-de5302c02d5f

### Max Supply

250000000000000

### Website

http://www.transinu.me

### Logo URI

https://i.ibb.co/vw3wBRx/terminated.png

### Contract Address

0xab7843a30989ddf7a1b07204db73eef6d7c5d345

### Code Format

None

### Other Info

update description an logo

**Comment by zmcNotafraid** [comment]
Updated.
