### ISSUE TITLE
[Native ERC20 Token] **transinu**

### ISSUE THREAD

**Issue by specmeup** [Magickbase/godwoken_explorer#1461]
### Token Name

transinu

### Description

Welcome to the world of Transinu, a transformative community project that unites individuals with a common goal: collaboration.

### Max Supply

250000000000000

### Website

 http://www.transinu.me

### Logo URI

https://i.ibb.co/687CRSb/trans-token-nervos.png

### Contract Address

 0x1318ced749b29f2b11ed5dec9035de9a39a5b8f7

### Code Format

None

**Comment by zmcNotafraid** [comment]
@specmeup Info has updated.
