### ISSUE TITLE
[Native ERC20 Token] **LOLCKB**

### ISSUE THREAD

**Issue by specmeup** [Magickbase/godwoken_explorer#1462]
### Token Name

Nervos' Fun-Tastic Token

### Description

The Nervos' Fun-tastic Token - Will be listed on YokaiSwap, with minimal liquidity and airdropped to every single holder of pCKB. Brace yourself for a hilariously entertaining journey in the realm of Nervos! 

### Max Supply

100000000000000

### Website

N/A

### Logo URI

https://ibb.co/y6WGWnv][img]https://i.ibb.co/1r8h8fy/LOLCKB.png

### Contract Address

 0x28048f6517621e612dfbe248311c47a1baa4e2c5

### Code Format

None

**Comment by zmcNotafraid** [comment]
Updated at https://v1.gwscan.com/token/12313
