### ISSUE TITLE
Register NFT collection (EGGSLYS)

### ISSUE THREAD

**Issue by specmeup** [Magickbase/godwoken_explorer#1464]
**Collection name:** Eggsly Hero

**Description:**
"Eggsly Hero" is an extraordinary NFT collection that showcases a league of courageous and charming Eggslys ready to embark on epic adventures. Each Eggsly Hero is adorned with a variety of captivating traits, including stylish headbands, majestic crests, expressive beaks, trendy glasses, captivating eyes, and delightful colored dots on their shells. These brave Eggslies, with their colorful personalities and unwavering determination, stand as beacons of hope and inspiration in a world filled with limitless possibilities. Join them in their quest for excitement, friendship, and triumph as they redefine what it means to be a hero, one cracked shell at a time.

**Total supply:** 878

**Website:** [eggsly.fun](https://eggsly.fun)

**Logo:** ![Eggsly Hero Logo](https://i.ibb.co/ZMm4vBK/Eggs-gif.gif)

**Contract address:** 0xb2c71399630198080bB7E291F0Eb8cE2a78cc913

**Comment by zmcNotafraid** [comment]
Updated at https://v1.gwscan.com/zh-CN/nft-collection/0xb2c71399630198080bb7e291f0eb8ce2a78cc913?tab=activity
