### ISSUE TITLE
SubDID is resolved to its parent DataDID page

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#1465]
Visiting https://v1.gwscan.com/account/0x0ad1e5ed9dcf2af5753060a7e34eeec80e608897 we can see the `.bit alias` is `ckbees#run.bit`, it's linked to page https://data.did.id/ckbees#run.bit, which will be resolved the same as https://data.did.id/ckbees, but `ckbees` doesn't have an alias to address 0x0ad1e5ed9dcf2af5753060a7e34eeec80e608897, while https://data.did.id/run.ckbees.bit does.

So I guess `ckbees#run.bit` points to `ckbees`'s subdid `run.ckbees.bit`, and the link should be changed to https://data.did.id/run.ckbees.bit

**Comment by zmcNotafraid** [comment]
```
curl -X POST https://indexer-v1.did.id/v1/sub/account/list -d'{"account":"ckbees.bit","page":1,"size":20}'
{"errno":0,"errmsg":"","data":{"account":"ckbees.bit","account_id_hex":"0xb3d0842e7fb28a2ceacfd04ed6a623be74f7bb83","enable_sub_account":1,"sub_account_total":1,"sub_account_list":[{"account":"run.ckbees.bit","account_id_hex":"0x45248da1c175632ec1cecd8e58ea70a5d69cf408","create_at_unix":1687613929,"expired_at_unix":1719149929,"owner_algorithm_id":5,"owner_key":"0x0ad1e5ed9dcf2af5753060a7e34eeec80e608897","manager_algorithm_id":5,"manager_key":"0x0ad1e5ed9dcf2af5753060a7e34eeec80e608897"}]}}%
```
From das indexer sub account api, we can found that ckbees.bit have one sub did named `run.ckbees.bit`

**Comment by Keith-CY** [comment]
> ```
> curl -X POST https://indexer-v1.did.id/v1/sub/account/list -d'{"account":"ckbees.bit","page":1,"size":20}'
> {"errno":0,"errmsg":"","data":{"account":"ckbees.bit","account_id_hex":"0xb3d0842e7fb28a2ceacfd04ed6a623be74f7bb83","enable_sub_account":1,"sub_account_total":1,"sub_account_list":[{"account":"run.ckbees.bit","account_id_hex":"0x45248da1c175632ec1cecd8e58ea70a5d69cf408","create_at_unix":1687613929,"expired_at_unix":1719149929,"owner_algorithm_id":5,"owner_key":"0x0ad1e5ed9dcf2af5753060a7e34eeec80e608897","manager_algorithm_id":5,"manager_key":"0x0ad1e5ed9dcf2af5753060a7e34eeec80e608897"}]}}%
> ```
> 
> From das indexer sub account api, we can found that ckbees.bit have one sub did named `run.ckbees.bit`

How does `ckbees#run.bit` come if the subdid is returned as `run.ckbees.bit`

**Comment by JeffreyMa597** [comment]
> > https://github.com/dotbitHQ/das-account-indexer/blob/d2ea452f3c011493b5085fb80be464410338f283/http_server/handle/reverse_record.go#L174
> > ```
> > curl -X POST https://indexer-v1.did.id/v1/sub/account/list -d'{"account":"ckbees.bit","page":1,"size":20}'
> > {"errno":0,"errmsg":"","data":{"account":"ckbees.bit","account_id_hex":"0xb3d0842e7fb28a2ceacfd04ed6a623be74f7bb83","enable_sub_account":1,"sub_account_total":1,"sub_account_list":[{"account":"run.ckbees.bit","account_id_hex":"0x45248da1c175632ec1cecd8e58ea70a5d69cf408","create_at_unix":1687613929,"expired_at_unix":1719149929,"owner_algorithm_id":5,"owner_key":"0x0ad1e5ed9dcf2af5753060a7e34eeec80e608897","manager_algorithm_id":5,"manager_key":"0x0ad1e5ed9dcf2af5753060a7e34eeec80e608897"}]}}%
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > From das indexer sub account api, we can found that ckbees.bit have one sub did named `run.ckbees.bit`
> 
> How does `ckbees#run.bit` come if the subdid is returned as `run.ckbees.bit` @JeffreyMa597

@Keith-CY The domain string we got from the API was `ckbees#run.bit`.  Maybe `xxx.bit` and `xxx#run.bit` will both appear in our interface, so I'll handle it in frontEnd.

<img width="1398" alt="image" src="https://github.com/Magickbase/godwoken_explorer/assets/22511289/a7b63190-70c8-40a3-b052-d6e08dfac5f4">

**Comment by JeffreyMa597** [comment]
PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/954

**Comment by zmcNotafraid** [comment]
When we invoke das indexer api from backend,it returns account_alias with `#`, but account not format.So we can save account to our db.
```
 curl -X POST https://indexer-v1.did.id/v1/batch/reverse/record -d'{"batch_key_info":[{"type": "blockchain","key_info":{"coin_type": "60","key": "0x0ad1e5ed9dcf2af5753060a7e34eeec80e608897"}}]}'

{"errno":0,"errmsg":"","data":{"list":[{"account":"run.ckbees.bit","account_alias":"ckbees#run.bit","err_msg":""}]}}% 
```

**Comment by Keith-CY** [comment]
> When we invoke das indexer api from backend,it returns account_alias with `#`, but account is not format.So we can save account to our db.
> 
> ```
>  curl -X POST https://indexer-v1.did.id/v1/batch/reverse/record -d'{"batch_key_info":[{"type": "blockchain","key_info":{"coin_type": "60","key": "0x0ad1e5ed9dcf2af5753060a7e34eeec80e608897"}}]}'
> 
> {"errno":0,"errmsg":"","data":{"list":[{"account":"run.ckbees.bit","account_alias":"ckbees#run.bit","err_msg":""}]}}% 
> ```

So the SubDID is returned in different formats by different APIs? It's a bit weird, I'll confirm it with .bit team

**Comment by Keith-CY** [comment]
> > When we invoke das indexer api from backend,it returns account_alias with `#`, but account is not format.So we can save account to our db.
> > ```
> >  curl -X POST https://indexer-v1.did.id/v1/batch/reverse/record -d'{"batch_key_info":[{"type": "blockchain","key_info":{"coin_type": "60","key": "0x0ad1e5ed9dcf2af5753060a7e34eeec80e608897"}}]}'
> > 
> > {"errno":0,"errmsg":"","data":{"list":[{"account":"run.ckbees.bit","account_alias":"ckbees#run.bit","err_msg":""}]}}% 
> > ```
> 
> So the SubDID is returned in different formats by different APIs? It's a bit weird, I'll confirm it with .bit team

Ah I see `run.ckbees.bit` and `ckbees#run.bit` are both returned in the API

**Comment by zmcNotafraid** [comment]
<img width="458" alt="image" src="https://github.com/Magickbase/godwoken_explorer/assets/12708910/6a12dcc9-fdf5-4d94-918b-060b6f7d002b">
