### ISSUE TITLE
 $RUN EXCLUSIVE COLLECTORS CARDS

### ISSUE THREAD

**Issue by 57u** [Magickbase/godwoken_explorer#1472]
### Contract Name

 $RUN EXCLUSIVE COLLECTORS CARDS

### Contract Address

0x000226bf319a64c4b80e73cd8f1a5f58f09d2093

### Compiler Version

0.8.11

### Website

https://run.ckbees.app

### Logo URI

https://bafybeih3qvdly24imkuufsqcxu4rgqasdqhcgd4pwcl5of3dwhkje7au7q.ipfs-public.thirdwebcdn.com/RUN_CARD_CROP.png

### Other Info

These $RUN exclusive supporters cards are airdropped to all wallets that made a minimum purchase in the 8 phases of $RUN. Collecting all 8 will earn a very special NFT - a rhodium (ikr!) ultimate supporter card!

**Comment by zmcNotafraid** [comment]
Token's logo and website have updated.To submit contract code please use 
`Verify By Sourcify`  from https://v1.gwscan.com/account/0x000226bf319a64c4b80e73cd8f1a5f58f09d2093?search=0x000226bf319a64c4b80e73cd8f1a5f58f09d2093

**Comment by 57u** [comment]
Thank you.

Is it possible to change the name? It should be: 
$RUN EXCLUSIVE COLLECTORS CARDS

**Comment by zmcNotafraid** [comment]
> Thank you.
> 
> Is it possible to change the name? It should be: $RUN EXCLUSIVE COLLECTORS CARDS

Name has changed too.

**Comment by 57u** [comment]
Hi, sorry for re-opening this, but the IPFS provider has changed the way assets are accessed.

The RUN CARD LOGO is now at: 

https://bafybeih3qvdly24imkuufsqcxu4rgqasdqhcgd4pwcl5of3dwhkje7au7q.ipfs.dweb.link/RUN_CARD_CROP.png

**Comment by zmcNotafraid** [comment]
> Hi, sorry for re-opening this, but the IPFS provider has changed the way assets are accessed.
> 
> The RUN CARD LOGO is now at:
> 
> https://bafybeih3qvdly24imkuufsqcxu4rgqasdqhcgd4pwcl5of3dwhkje7au7q.ipfs.dweb.link/RUN_CARD_CROP.png

Updated.
