### ISSUE TITLE
[Update details on Native ERC20 Token] **ovum**

### ISSUE THREAD

**Issue by specmeup** [Magickbase/godwoken_explorer#1473]
### Token Name

OVUM

### Description

Ovum serves as the native token within the Eggsly project. 
The acquisition of ovum is limited to two primary methods: owning an Eggsly NFT or possessing an Eggsly .bit sub did.

To obtain ovum, one must either possess an Eggsly NFT, which represents a unique and valuable digital item, or own an Eggsly .bit sub did, a specialized digital identifier associated with the project. These ownerships grant individuals the right to claim ovum tokens, thus providing access to the Eggsly ecosystem.

Additionally, ovum tokens will be available for trading on decentralized exchanges (DEX), enabling users to buy, sell, and trade them with other participants within the Eggsly community. This offers an opportunity for users to engage in a vibrant marketplace.

Moreover, Eggsly offers exclusive NFT drops that can only be acquired using ovum tokens. These limited-edition NFTs represent unique and highly sought-after digital artworks or collectibles, providing users with an opportunity to expand their digital collections and participate in the Eggsly project's exclusive offerings.

### Max Supply

1000000000

### Website

 https://eggsly.fun/

### Logo URI

https://i.ibb.co/JFXpvHy/Eggsly-Token.png

### Contract Address

0xc883765768ec7f6816fa17f944610613b7a6159f

### Code Format

None

**Comment by zmcNotafraid** [comment]
Updated.
