### ISSUE TITLE
[Native ERC20 Token] GAME

### ISSUE THREAD

**Issue by 57u** [Magickbase/godwoken_explorer#1506]
### Token Name

GAME

### Description

$GAME is the in-game currency for games on CKBees NFTs & Games parlour

### Max Supply

833500000000

### Website

ckbees.app

### Logo URI

https://ckbees.app/GAME-LOGO.png

### Contract Address

0x3B0384CC7E8Dffea88B0007cf9bc1C1A1f359c1c

### Code Format

None

**Comment by zmcNotafraid** [comment]
Updated @57u
