### ISSUE TITLE
[Native ERC20 Token] $RUN

### ISSUE THREAD

**Issue by 57u** [Magickbase/godwoken_explorer#1579]
### Token Name

$RUN

### Description

The token is already registered and listed in GWScan, i need to update the URL of the image please. I am the creator of $RUN on GW (https://v1.gwscan.com/account/0x36b4e2660a17777b3819e13cc55d541e8bfb87d8)

https://bafybeiej4o7r56nmzwjx3ohgaxwfpfyxruzeadvva5oxgaiugdjnqrk5rq.ipfs.dweb.link/runckb.png

### Max Supply

1,360,922,222

### Website

https://run.ckbees.app

### Logo URI

https://bafybeiej4o7r56nmzwjx3ohgaxwfpfyxruzeadvva5oxgaiugdjnqrk5rq.ipfs.dweb.link/runckb.png

### Contract Address

0x36b4e2660a17777b3819e13cc55d541e8bfb87d8

### Code Format

None

### Other Info

I have updated the max token supply in the field in this form, i will be doing burns going forward so this will drop of course. The number i intered is the max supply as of today, there will be no more minted.

**Comment by zmcNotafraid** [comment]
Logo URI and max supply have updated.
