### ISSUE TITLE
Return ckb value along with udt value in deposit/withdraw record

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#178]
Each deposit/withdraw comes with at least 400 ckb, but they are not revealed in the records, which leads to a mismatch on balance. To fix it, ckb value should be returned in each record.

**Comment by zmcNotafraid** [comment]
For now if you deposit or withdrawal a sudt, it will cover the ckb value,so only udt balance return。We will fix it and support both ckb and sudt balance

**Comment by zmcNotafraid** [comment]
@Keith-CY  **https://api.gwscan.com/api/deposit_withdrawals?eth_address=0x62bb1f76baa0e39c66554d30805369133a805b52**
return a new key: `capacity`, it is not parsed by decimal

**Comment by zmcNotafraid** [comment]
old data has not fixed.
