### ISSUE TITLE
v1:Transaction Count is inconsistent with the nonce

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#282]
`Transaction Count`  is inconsistent with the `nonce`. I don't know what the `Transaction Count` and `nonce` here mean
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/32102187/158927296-317e91c8-5fe4-403f-8103-d6b85c6c86b3.png">

**Comment by zmcNotafraid** [comment]
Transaction count means the user send transactions count (a transaction from account is this user).
User nonce is get from godwoken RPC method: gw_get_nonce
