### ISSUE TITLE
v1: Cannot find token information through Bridged Token List

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#284]
url:https://v1.aggron.gwscan.com/tokens/bridge
click address
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/32102187/158930212-bfe189af-c786-4f0d-9a5c-a4f7cf8bb233.png">
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/32102187/158930053-16771d41-a03a-4254-a576-feb81a2ab5ec.png">

**Comment by zmcNotafraid** [comment]
@Keith-CY  maybe some data is not suitable for the frontend.
API:  https://api.v1.aggron.gwscan.com/api/udts/1

**Comment by Keith-CY** [comment]
This token is not registered on testnet so its `type script` is missing, which leads to this error.

Fixed with [commit](https://github.com/nervina-labs/godwoken-explorer-ui/commit/7764df100618a12ccc61461ced19eb2b818db69c) by removing the `type script` field.
