### ISSUE TITLE
v1: how could I get the tx_hash of a created contract?

### ISSUE THREAD

**Issue by Flouse** [Magickbase/godwoken_explorer#309]
something like this:
![image](https://user-images.githubusercontent.com/1297478/160217964-9140ff6a-1395-4afc-8159-99025225e76c.png)

https://etherscan.io/address/0x4da0c48376c277cdbd7fc6fdc6936dee3e4adf75
![image](https://user-images.githubusercontent.com/1297478/160217893-bed2f760-8851-4231-88a4-6f28cfddfcd9.png)

required for sourcify verification in case when constructor arguments were passed

**Comment by Keith-CY** [comment]
For now, we only provide a way to [submit contract registration](https://github.com/nervina-labs/godwoken_explorer/issues/new?assignees=Keith-CY&labels=Contract+Registration&template=register-a-general-contract.yml&title=%5BGeneral+Contract%5D+%2A%2AContract+Name%2A%2A) and then verify the source code manually. After verification, we will append contract info in its page.

In the next version, we will implement contract verification automation, with that we will save all contract creation transactions and compare their bytecodes with known contract libraries, then mark the recognized ones.

**Comment by zmcNotafraid** [comment]
Repeated with https://github.com/Magickbase/godwoken_explorer/issues/243
