### ISSUE TITLE
Alpha Release

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#320]
Readme should be enriched

**Comment by Keith-CY** [comment]
Any update?

**Comment by Keith-CY** [comment]
Would be released once `deploy with docker` is done.

**Comment by Keith-CY** [comment]
Any update?

**Comment by Naupio** [comment]
I will update the README file today.

**Comment by Keith-CY** [comment]
> I will update the README file today.

A draft PR can be posted first.
