### ISSUE TITLE
[v1] Transaction Count is inconsistent with the number of transactions

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#346]
url:https://v1.aggron.gwscan.com/account/0x40711adc577de17232dd6f997022f68be6be8560?search=0x40711adc577de17232dd6f997022f68be6be8560
Transaction Count is inconsistent with the number of transactions
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/32102187/162362762-27ae07ba-c4a9-47d1-80d8-26de337cb9f7.png">

**Comment by gpBlockchain** [comment]
https://v1.aggron.gwscan.com/account/0x934f1ebcb57ce1d9985a4c4f8811d17b04342067?tab=transactions
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/32102187/162364914-69a3255c-37df-4e5c-9909-ee182baa8593.png">

**Comment by zmcNotafraid** [comment]
> url:https://v1.aggron.gwscan.com/account/0x40711adc577de17232dd6f997022f68be6be8560?search=0x40711adc577de17232dd6f997022f68be6be8560 Transaction Count is inconsistent with the number of transactions <img alt="image" width="1211" src="https://user-images.githubusercontent.com/32102187/162362762-27ae07ba-c4a9-47d1-80d8-26de337cb9f7.png">

Fixed.Because transaction count has cahce and it's async.

**Comment by zmcNotafraid** [comment]
> https://v1.aggron.gwscan.com/account/0x934f1ebcb57ce1d9985a4c4f8811d17b04342067?tab=transactions <img alt="image" width="1195" src="https://user-images.githubusercontent.com/32102187/162364914-69a3255c-37df-4e5c-9909-ee182baa8593.png">

Above transactions nonce are 1, 2, 3, so last transaction nonce is 3, after calculate transaction count = 3 + 1

**Comment by Keith-CY** [comment]
> > [v1.aggron.gwscan.com/account/0x934f1ebcb57ce1d9985a4c4f8811d17b04342067?tab=transactions](https://v1.aggron.gwscan.com/account/0x934f1ebcb57ce1d9985a4c4f8811d17b04342067?tab=transactions) <img alt="image" width="1195" src="https://user-images.githubusercontent.com/32102187/162364914-69a3255c-37df-4e5c-9909-ee182baa8593.png">
> 
> Above transactions nonce are 1, 2, 3, so last transaction nonce is 3, after calculate transaction count = 3 + 1

I'm kind of confused about `transaction count = 3 + 1`, obviously there're only 3 txns in the list.

**Comment by zmcNotafraid** [comment]
> > > [v1.aggron.gwscan.com/account/0x934f1ebcb57ce1d9985a4c4f8811d17b04342067?tab=transactions](https://v1.aggron.gwscan.com/account/0x934f1ebcb57ce1d9985a4c4f8811d17b04342067?tab=transactions) <img alt="image" width="1195" src="https://user-images.githubusercontent.com/32102187/162364914-69a3255c-37df-4e5c-9909-ee182baa8593.png">
> > 
> > 
> > Above transactions nonce are 1, 2, 3, so last transaction nonce is 3, after calculate transaction count = 3 + 1
> 
> I'm kind of confused about `transaction count = 3 + 1`, obviously there're only 3 txns in the list.

This logic is from blockscout. 

> We have to increment +1 in the last nonce result because it works like an array position, the first
  nonce has the value 0. When last nonce is nil, it considers that the given address has 0 transactions.

https://github.com/blockscout/blockscout/blob/0a4a7dba5c35558052715f97751fd6163b16894f/apps/explorer/lib/explorer/chain.ex#L312

**Comment by Keith-CY** [comment]
> > > > [v1.aggron.gwscan.com/account/0x934f1ebcb57ce1d9985a4c4f8811d17b04342067?tab=transactions](https://v1.aggron.gwscan.com/account/0x934f1ebcb57ce1d9985a4c4f8811d17b04342067?tab=transactions) <img alt="image" width="1195" src="https://user-images.githubusercontent.com/32102187/162364914-69a3255c-37df-4e5c-9909-ee182baa8593.png">
> > > 
> > > 
> > > Above transactions nonce are 1, 2, 3, so last transaction nonce is 3, after calculate transaction count = 3 + 1
> > 
> > 
> > I'm kind of confused about `transaction count = 3 + 1`, obviously there're only 3 txns in the list.
> 
> This logic is from blockscout.
> 
> > We have to increment +1 in the last nonce result because it works like an array position, the first
> > nonce has the value 0. When last nonce is nil, it considers that the given address has 0 transactions.
> 
> [blockscout/blockscout@`0a4a7db`/apps/explorer/lib/explorer/chain.ex#L312](https://github.com/blockscout/blockscout/blob/0a4a7dba5c35558052715f97751fd6163b16894f/apps/explorer/lib/explorer/chain.ex#L312)

I've got the point.

In ethereum, the first tx of an account has `nonce: 0`, e.g. https://etherscan.io/tx/0x3564c77e5be70c3aaa6fcbbbb93eba09eb1103e039656c2af169d2de96f8f680 is the first txn of 0x438a7fd2b46f7f970b580fccf494febdc366619e

In godwoken, however, the first txn of an account has `nonce: 1`, e.g. https://v1.aggron.gwscan.com/tx/0x14e676070138d11e745cf4dc58d645bdd4a2c99af4483f90023815503e6bc792 is the first txn of 0x934f1ebcb57ce1d9985a4c4f8811d17b04342067

So with logic of blockscout, the txn count should be `nonce + 1` since txn's nonce starts from 0.

Is it designed to start nonce from 1? @Flouse

**Comment by Flouse** [comment]
> In godwoken, however, the first txn of an account has nonce: 1, e.g. https://v1.aggron.gwscan.com/tx/0x14e676070138d11e745cf4dc58d645bdd4a2c99af4483f90023815503e6bc792 is the first txn of 0x934f1ebcb57ce1d9985a4c4f8811d17b04342067

This account's first txn may be not a Polyjuice transaction, so the first Polyjuice txn of the account is nonce 1.

---

Let's see another account: [0x1cb9c569d3f9682a685ef32371b6cfea2a738b51](https://v1.aggron.gwscan.com/account/0x1cb9c569d3f9682a685ef32371b6cfea2a738b51)
https://v1.aggron.gwscan.com/tx/0xa91883d70007c8da4fea8704d51cf1169f560e9d872d7a2e3738872619da6cdf
The nonce of its first txn is 0.

**Comment by Keith-CY** [comment]
> > In godwoken, however, the first txn of an account has nonce: 1, e.g. [v1.aggron.gwscan.com/tx/0x14e676070138d11e745cf4dc58d645bdd4a2c99af4483f90023815503e6bc792](https://v1.aggron.gwscan.com/tx/0x14e676070138d11e745cf4dc58d645bdd4a2c99af4483f90023815503e6bc792) is the first txn of 0x934f1ebcb57ce1d9985a4c4f8811d17b04342067
> 
> This account's first txn may be not a Polyjuice transaction, so the first Polyjuice txn of the account is nonce 1.
> 
> Let's see another account: [0x1cb9c569d3f9682a685ef32371b6cfea2a738b51](https://v1.aggron.gwscan.com/account/0x1cb9c569d3f9682a685ef32371b6cfea2a738b51) [v1.aggron.gwscan.com/tx/0xa91883d70007c8da4fea8704d51cf1169f560e9d872d7a2e3738872619da6cdf](https://v1.aggron.gwscan.com/tx/0xa91883d70007c8da4fea8704d51cf1169f560e9d872d7a2e3738872619da6cdf) The nonce of its first txn is 0.

So the txn of nonce 0 is lost in the list @zmcNotafraid

**Comment by classicalliu** [comment]
> > > In godwoken, however, the first txn of an account has nonce: 1, e.g. https://v1.aggron.gwscan.com/tx/0x14e676070138d11e745cf4dc58d645bdd4a2c99af4483f90023815503e6bc792 is the first txn of 0x934f1ebcb57ce1d9985a4c4f8811d17b04342067
> > 
> > 
> > This account's first txn may be not a Polyjuice transaction, so the first Polyjuice txn of the account is nonce 1.
> > Let's see another account: [0x1cb9c569d3f9682a685ef32371b6cfea2a738b51](https://v1.aggron.gwscan.com/account/0x1cb9c569d3f9682a685ef32371b6cfea2a738b51) https://v1.aggron.gwscan.com/tx/0xa91883d70007c8da4fea8704d51cf1169f560e9d872d7a2e3738872619da6cdf The nonce of its first txn is 0.
> 
> I query from database and found no nonce is 0 transaction. If it is not a polyjuice transaction, can I fetch from `gw_get_block_by_number` rpc method? @Flouse

Yes, get block transactions from `gw_get_block_by_number` and get transaction details from `gw_get_transaction` (maybe not needed, infos included in `block.transactions`) & `gw_get_transaction_receipt`

**Comment by zmcNotafraid** [comment]
> 
I compare each block's transactions count with tranactioins tables count.It's equal and no missing tx.So how could I know what is this account's nonce 0 tx?

**Comment by classicalliu** [comment]
> > 
> 
> I compare each block's transactions count with tranactioins tables count.It's equal and no missing tx.So how could I know what is this account's nonce 0 tx?

Which account's first nonce not equals to 0 ?

**Comment by Flouse** [comment]
> Which account's first nonce not equals to 0 ?

https://v1.aggron.gwscan.com/account/0x934f1ebcb57ce1d9985a4c4f8811d17b04342067?id=0x934f1ebcb57ce1d9985a4c4f8811d17b04342067&page=3

**Comment by zmcNotafraid** [comment]
Thanks! I have understanded that withdrawal request is also cause nonce increment
