### ISSUE TITLE
[v1] deploy contract hash not sort 

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#349]
deploy account url:https://v1.aggron.gwscan.com/account/0x5d0666bae2a0116ffb37e2d5684a3b432c3b7e73
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/32102187/162380053-23671d9a-ca74-49e4-922b-eaff5f3d909b.png">
block url :https://v1.aggron.gwscan.com/block/0x0e4b181a784f3c8d2668f4e0b49ba231ff2f0865555a3dbce02378b1ee2a34f9
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/32102187/162380119-3bdb0169-88b2-4003-bea9-29d25d4d0a7b.png">

**Comment by zmcNotafraid** [comment]
Fixed.
