### ISSUE TITLE
Tokens registered recently have no total supply

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#351]
![image](https://user-images.githubusercontent.com/7271329/162577801-7e867b83-2321-4699-8fa9-902f0a489933.png)

**Comment by Keith-CY** [comment]
Native ERC20 Tokens' total supply could be updated periodically, but also should be updated just after setting token info.

**Comment by zmcNotafraid** [comment]
Now after regrester from backend admin, if you don't fill supply, we will get supply from contract
