### ISSUE TITLE
点击任意区块然后依次点击”交易“和”桥接转账“，页面有刷新和卡顿

### ISSUE THREAD

**Issue by xiefei1024** [Magickbase/godwoken_explorer#357]
<img width="1770" alt="image" src="https://user-images.githubusercontent.com/101535604/162877318-206acab2-e28a-486f-bfda-55985c14b862.png">

**Comment by xiefei1024** [comment]
马上 刚刚没找到录屏软件

**Comment by Keith-CY** [comment]
> ```
>         录屏见附件
> ```
> 
>  2022-04-12.2.33.18.mov

从录屏里看不出刷新, 不过根据操作我猜想你的预期是
底部的两个 tab 按钮是只切换底部的数据展示, 不需要页面回到顶部
不知道禁用刷新是否指的这种效果

**Comment by xiefei1024** [comment]
我没懂你的意思了 我的理解是 在交易和桥接之间 切换，页面不应该懂 就是切换这两个下面的列表即可
这是我的理解哈 不一定对 感觉用户体验更好

**Comment by Keith-CY** [comment]
> 我没懂你的意思了 我的理解是 在交易和桥接之间 切换，页面不应该抖动或者刷新 切换的时候就切换这两个下面的列表即可 这是我的理解哈 不一定对 感觉用户体验更好

了解, 这个确实可以优化, 代码更新后我关联到这个 issue

**Comment by Keith-CY** [comment]
We can disable scroll with config https://nextjs.org/docs/api-reference/next/link#disable-scrolling-to-the-top-of-the-page

**Comment by Keith-CY** [comment]
Please visit https://www.gwscan.com/token/49056?tab=transfers and switch between `transfers` and `holders`, the tab header should be in the same position.
