### ISSUE TITLE
[v0]Supply is not equal the sum of the holders' balance

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#362]
https://gwscan.com/zh-CN/token/49361?tab=holders
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/32102187/163142556-b1f5be1b-d095-4d02-b422-a044147925d0.png">
#### expected
Supply is equal the sum of the holders' balance

**Comment by zmcNotafraid** [comment]
When we recalculate this token's supply and holder. We found some address deposit token but no transaction record for spend this token.So maybe some transaction is missed.

**Comment by zmcNotafraid** [comment]
We bind wrong contract address  to WBTC.Now it's fixed.
