### ISSUE TITLE
need link to the token message 

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#363]
env:https://gwscan.com/account/0xe730b1416cee49e71047a5162f318d968456b986?tab=assets
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/32102187/163145638-105492ba-8181-4204-bd91-0bb8ae79c561.png">
#### expected
1. click WBTC，Jump to the token page

**Comment by Keith-CY** [comment]
token id could be retrieved from graphql query and set token name a link to token page

**Comment by Keith-CY** [comment]
This feature is add by PR https://github.com/Magickbase/godwoken-explorer-ui/pull/217

**Comment by Keith-CY** [comment]
Preview https://v1.betanet.gwscan.com/zh-CN/account/0xb99de8d636be333ec5c8ce1476e9b6fe7877f02a?tab=assets
