### ISSUE TITLE
[v0] balance display precision not equal token'Decimal

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#364]
env:https://gwscan.com/account/0xe730b1416cee49e71047a5162f318d968456b986?tab=assets
WBTC|Eth: https://gwscan.com/token/49361
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/32102187/163146403-5bf33b76-594b-439f-98f0-d284312cb068.png">
<img width="981" alt="image" src="https://user-images.githubusercontent.com/32102187/163147092-f5680560-1fe7-4218-be81-bcc95f172111.png">

**Comment by Keith-CY** [comment]
Seems the precision of values is set to 20, which should not be assumed because some token might use a decimal greater than 20, and then the value would be truncated. We should return them with their own precision, respectively. @zmcNotafraid

**Comment by zmcNotafraid** [comment]
All data has fixed

**Comment by zmcNotafraid** [comment]
This trailing zero is added by postgresql calcuate decimal. We use `trim_scale  `to remove the trailing zero
