### ISSUE TITLE
Hot/cold data should be explicitly annotated

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#365]
![image](https://user-images.githubusercontent.com/7271329/163155562-b594df5c-0d83-4f18-b7a0-109d3e8d6646.png)

There are 7776 transactions in total but only 47 transactions are listed. The reason is that all transactions are grouped into hot/cold data, and transactions in 5 days are marked hot and will be listed while other transactions are marked cold that won't be listed.

This is efficient but some kind of confusing so we should annotate which data are limited to show.

Please add APIs below that only return hot data. @zmcNotafraid

**Comment by Keith-CY** [comment]
Also cc @gpBlockchain

**Comment by zmcNotafraid** [comment]
1. erc20 的转账列表，如果数据大于 100_000  条，就返回最近的100_000 条。
2. 账户的交易列表，最近100_000 条数据
3. 全部交易列表，最近 500_000 条数据

**Comment by Keith-CY** [comment]
All Transactions: https://www.gwscan.com/txs
Transactions of an account: https://www.gwscan.com/account/0x98d6fc98b3c26b9dd3b7e4bac3e11ceb3e7171da
Transfers of an account: https://www.gwscan.com/account/0xa6f58c6ffb5d3ef4c57b3ceadf975e22c7ea5c8f?tab=erc20
