### ISSUE TITLE
[v0] query account address not equal displayed account address

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#366]
url: https://aggron.gwscan.com/account/0x26e18bccd567686bfc7f790cc56f65bb1fdfaec2
![image](https://user-images.githubusercontent.com/32102187/163159407-3523633d-3aec-432b-80c9-905192a86ba0.png)

**Comment by Keith-CY** [comment]
The response of https://api.aggron.gwscan.com/api/accounts/0x26e18bccd567686bfc7f790cc56f65bb1fdfaec2 has `eth_addr` `0x3b9636c518d7fe100c56b5d2f087f7b77fb77327`

**Comment by zmcNotafraid** [comment]
0x26e18bccd567686bfc7f790cc56f65bb1fdfaec2 is a short address ,but 0x3b9636c518d7fe100c56b5d2f087f7b77fb77327 is eth address

**Comment by Keith-CY** [comment]
It's kind of weird. I remember that query with gw_hash will return an error, and the page will ask users to use eth hash to visit the page.

But it returns account info now.

**Comment by Keith-CY** [comment]
Short address is deprecated in v0 so it won't appear in v1.1 and further. Maybe we can close this issue @gpBlockchain
