### ISSUE TITLE
[v0] tx url need log message

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#368]
url :https://aggron.gwscan.com/tx/0xe892174cb9c1fecc24ac815e6592c5b5b3194f43d7467804cc319139d8d88ba3
need log event like pic
![image](https://user-images.githubusercontent.com/32102187/163164327-e8c5331d-d837-4e9c-9d72-797eb5ead479.png)

**Comment by Keith-CY** [comment]
Logs are in design, but it's an advanced function that would be supported later. I'll update here once logs are listed.

**Comment by Keith-CY** [comment]
I just found the designed functionalities of gwscan are public, the events(logs) function is listed on the last 3rd.

**Comment by zmcNotafraid** [comment]
We will add this feature at  https://github.com/Magickbase/godwoken_explorer/issues/494
