### ISSUE TITLE
[v0,v1]register contracts page missing registration link

### ISSUE THREAD

**Issue by BourneNeo** [Magickbase/godwoken_explorer#371]
there isn't any registration means indicated on register contracts page, should put a link there.
![image](https://user-images.githubusercontent.com/18527271/163298226-b09b0a00-a0cc-4a98-9a61-98e47a583f1c.png)

**Comment by Keith-CY** [comment]
We hide the link to registration info since it is a temporary usage and finally the registration will be done by an API like https://docs.etherscan.io/api-endpoints/contracts#verify-source-code or a GUI in GwScan https://etherscan.io/verifyContract

But it's still a good idea to add a link to the original registration, even after we use an API we still need a page to show the original data.

We'll do it later.

**Comment by gpBlockchain** [comment]
> We hide the link to registration info since it is a temporary usage and finally the registration will be done by an API like https://docs.etherscan.io/api-endpoints/contracts#verify-source-code or a GUI in GwScan https://etherscan.io/verifyContract
> 
> But it's still a good idea to add a link to the original registration, even after we use an API we still need a page to show the original data.
> 
> We'll do it later.

will support  truffle-plugin-verify？

**Comment by Keith-CY** [comment]
> > We hide the link to registration info since it is a temporary usage and finally the registration will be done by an API like [docs.etherscan.io/api-endpoints/contracts#verify-source-code](https://docs.etherscan.io/api-endpoints/contracts#verify-source-code) or a GUI in GwScan [etherscan.io/verifyContract](https://etherscan.io/verifyContract)
> > But it's still a good idea to add a link to the original registration, even after we use an API we still need a page to show the original data.
> > We'll do it later.
> 
> will support truffle-plugin-verify？

I'm afraid not, our backend is based on elixir, which is similar to [blockscout](https://github.com/blockscout/blockscout), that means we probably use toolkit that blockscout uses.
