### ISSUE TITLE
Deposit/WIthdrawal API responds slowly

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#373]
API: https://api.aggron.gwscan.com/api/deposit_withdrawals?udt_id=1
![image](https://user-images.githubusercontent.com/7271329/163310243-653a786b-d450-4fb8-8e0f-8608b2e57f48.png)
![image](https://user-images.githubusercontent.com/7271329/163310985-1f675c97-3a2e-447f-8edf-77587779899e.png)
![image](https://user-images.githubusercontent.com/7271329/163311035-48f6f5b5-0f66-43c2-bffe-f7a4f0c7f990.png)

**Comment by Keith-CY** [comment]
Sometimes it breaks

**Comment by gpBlockchain** [comment]
slowly : https://www.gwscan.com/account/0x0000000000000000000000000000000000000000?tab=erc20

**Comment by Keith-CY** [comment]
> slowly : [gwscan.com/account/0x0000000000000000000000000000000000000000?tab=erc20](https://www.gwscan.com/account/0x0000000000000000000000000000000000000000?tab=erc20) <img alt="image" width="1098" src="https://user-images.githubusercontent.com/32102187/163560078-10e92f44-4c14-4afd-b840-09c9dc04f1ab.png">

This request(https://api.gwscan.com/api/transfers?eth_address=0x0000000000000000000000000000000000000000) is pending

![image](https://user-images.githubusercontent.com/7271329/163561840-c7dcb269-708b-4388-b3b0-13c52a48767a.png)

**Comment by zmcNotafraid** [comment]
0x0000000000000000000000000000000000000000 address have 4 million token_transfer data.So it's very slow

**Comment by zmcNotafraid** [comment]
The api include udt model caused performance slowly.
