### ISSUE TITLE
[v0] ckb balance is not updated synchronously with bridged transfer

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#374]
https://aggron.layerview.io/account/0xc5f4992141c41e2bd778819d671e13a10bdd3b12?tab=bridged
### step
1. Transfer 9935.999 ckb one week ago
2. Now transfer 10000ckb
3. check ckb'balance
4. wait for the balance to arrive
### response
1. Bridge records do not have information from a week ago
2. The bridge record shows that the transfer is 10000ckb, but the balance of ckb is still 9935.999
3. after half an hour
4. the balance of ckb is 19935.999

**Comment by zmcNotafraid** [comment]
Now we query ckb balance is directly use gw rpc method: gw_get_balance. So maybe gw calculate balance is slow?

**Comment by Keith-CY** [comment]
Since we call `gw_get_balance` on the fly, the `ckb balance` should equal to on-chain data exactly.

Any idea on this? @flouse
