### ISSUE TITLE
[v1]Does the bridge transaction deposit need to display L1 block

### ISSUE THREAD

**Issue by Dawn-githup** [Magickbase/godwoken_explorer#388]
[https://v1.aggron.gwscan.com/account/0xcf5dccb5ceaddaeebf36affd16d5a4bd1ffa5193?tab=bridged](https://v1.aggron.gwscan.com/account/0xcf5dccb5ceaddaeebf36affd16d5a4bd1ffa5193?tab=bridged)

![image](https://user-images.githubusercontent.com/77844990/163542305-5983acb1-1a4e-473c-95c8-967589a7cc6b.png)

**Comment by zmcNotafraid** [comment]
Here shows the layer2 block number not layer1. Current we can't get layer2 block number of deposit from rpc.

**Comment by Keith-CY** [comment]
There was a feature required to godwoken that an API could be added to listen to deposit events.

Did we have an issue yet? @flouse

**Comment by jjyr** [comment]
Nope, we haven't figure out a way to handle that, we decided to delay the feature.

By my understanding, the explorer extract the deposit cells from CKB transactions. If we adjust this behavior, to extracts deposit cell from CKB transaction which submits the Godwoken blocks, we can get the layer2 block number.

**Comment by Keith-CY** [comment]
> Nope, we haven't figure out a way to handle that, we decided to delay the feature.
> 
> By my understanding, the explorer extract the deposit cells from CKB transactions, so we only now the CKB block number. But if we adjust this behavior, if the explorer extracts deposit cell from CKB transactions which submits the Godwoken blocks(the deposits cell will be used as the inputs in these transaction), we can also get the layer2 block number from the CKB transaction.

Got it, we can decode layer2 block info in the txn that **gathers deposit cells and mints new tokens**, this txn should be submitted by the aggregator.

Could you append a link to show us how the layer 2 info is encoded?

**Comment by jjyr** [comment]
You can search the rollup cell to identify submits block transactions. The inputs of the transaction includes bunch of deposits cells, withdrawal cells and custodian cells.

The first witness is a encoded L2Block message:

https://github.com/nervosnetwork/godwoken/blob/0.10/crates/types/schemas/godwoken.mol#L98
