### ISSUE TITLE
fetch script hash with RPC gw_get_script_hash_by_short_address return "Method not found"

### ISSUE THREAD

**Issue by BourneNeo** [Magickbase/godwoken_explorer#390]
when trying fetch script hash with RPC gw_get_script_hash_by_short_address ,it returns "Method not found":

https://github.com/nervosnet/godwoken_explorer/wiki/How-to-register-a-bridge-token#:~:text=use%20the%20eth%20address%20of%20the%20contract%20to%20fetch%20script%20hash%20with%20RPC%20gw_get_script_hash_by_short_address

![image](https://user-images.githubusercontent.com/18527271/163751683-f0d56a18-4581-48ad-96cb-4e7f076c4f9b.png)

**Comment by Keith-CY** [comment]
Method `gw_get_script_hash_by_short_address` is deprecated in godwoken v1, I've found a similar method [gw_get_script_hash_by_short_script_hash](https://github.com/nervosnetwork/godwoken/blob/v1.0.0-rc1/docs/RPC.md#method-gw_get_script_hash_by_short_script_hash) in v1, but it requires `short script hash`, how can we get the `short script hash` @zmcNotafraid

**Comment by zmcNotafraid** [comment]
> when trying fetch script hash with RPC gw_get_script_hash_by_short_address ,it returns "Method not found":
> 
> https://github.com/nervosnet/godwoken_explorer/wiki/How-to-register-a-bridge-token#:~:text=use%20the%20eth%20address%20of%20the%20contract%20to%20fetch%20script%20hash%20with%20RPC%20gw_get_script_hash_by_short_address
> 
> ![image](https://user-images.githubusercontent.com/18527271/163751683-f0d56a18-4581-48ad-96cb-4e7f076c4f9b.png)

We will update the register bridge token flow for godwoken v1 soon.No need to pass bridge_account_id, only need to pass bridge_account eth_address

**Comment by zmcNotafraid** [comment]
If you want to registry udt, you can submit a issue at https://github.com/Magickbase/godwoken_explorer/issues/new/choose. And we will submit it to backend.

**Comment by zmcNotafraid** [comment]
We update wiki for bridge token: https://github.com/Magickbase/godwoken_explorer/wiki/How-to-register-a-bridge-token. You dont need to find account id anymore
