### ISSUE TITLE
[Bridged Token] **Token Name**

### ISSUE THREAD

**Issue by BourneNeo** [Magickbase/godwoken_explorer#393]
### Token Name

CKB

### Description

CKB

### Symbol

CKB

### Decimals

8

### Logo URI

None

### SUDT Script Arguments

0x0000000000000000000000000000000000000000000000000000000000000000

### Contract Address

0x9D9599c41383D7009C2093319d576AA6F89A4449

**Comment by zmcNotafraid** [comment]
This udt has alreaday registred at: https://gwscan.com/zh-CN/token/1.
