### ISSUE TITLE
[V1] [Bridged Token] **Token Name**

### ISSUE THREAD

**Issue by BourneNeo** [Magickbase/godwoken_explorer#397]
### Token Name

MyToken

### Description

sudt

### Symbol

MTK

### Decimals

18

### Max Supply

9999999999

### Logo URI

https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fwww.jiuwa.net%2Fpic%2F20180310%2F1520660931118598.png&refer=http%3A%2F%2Fwww.jiuwa.net&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1653025194&t=421f8011964c7d152ed31f04413b7b14

### SUDT Script Arguments

0x5a07b93cc3774d9fb72c3f75574fbc7c2bb21eb556009fde9f22e52e4d780c17

### Contract Address

0xED8Aaa7Dc0c2b5E3cAEb2EF762493A39feABE7dF

**Comment by zmcNotafraid** [comment]
Registed at: https://v1.aggron.gwscan.com/zh-CN/token/18616 @BourneNeo
