### ISSUE TITLE
[v1] contracts page crashed after successfully registered a contract

### ISSUE THREAD

**Issue by BourneNeo** [Magickbase/godwoken_explorer#398]
![image](https://user-images.githubusercontent.com/18527271/164365396-0d818831-3381-4bea-9c5c-cbe36ab5d28e.png)

![image](https://user-images.githubusercontent.com/18527271/164365511-9b2930fc-7420-4253-bff7-174befb598f3.png)

**and if refreshed**
![image](https://user-images.githubusercontent.com/18527271/164365632-593cc2ec-959e-41c2-869c-8ac8ae389b86.png)

**Comment by Keith-CY** [comment]
Ah, I realize that `compiler version` and `compiler format file` are used on the page, since they are mandatory in mainnet, so `null` value is not handled.

Set `compiler version` `0.6.12+commit.27d51765`
Set `compiler file format` `solidity single file (Default)`

should fix this.

**Comment by BourneNeo** [comment]
> 0.6.12+commit.27d51765

should updated  in registration instruction doc

**Comment by BourneNeo** [comment]
> Ah, I realize that `compiler version` and `compiler format file` are used on the page, since they are mandatory in mainnet, so `null` value is not handled.
> 
> Set `compiler version` `0.6.12+commit.27d51765` Set `compiler file format` `solidity single file (Default)`
> 
> should fix this.

should updated in registration instruction doc

**Comment by BourneNeo** [comment]
> > Ah, I realize that `compiler version` and `compiler format file` are used on the page, since they are mandatory in mainnet, so `null` value is not handled.
> > Set `compiler version` `0.6.12+commit.27d51765` Set `compiler file format` `solidity single file (Default)`
> > should fix this.
> 
> should updated in registration instruction doc

I guess should give an example in these inputbox each
![image](https://user-images.githubusercontent.com/18527271/164368409-a075a6d5-9394-4c8c-a342-17f8ef6480b9.png)

**Comment by Keith-CY** [comment]
Document updated in https://github.com/Magickbase/godwoken_explorer/wiki/How-to-register-a-bridge-token

**Comment by Keith-CY** [comment]
Actually the `compiler file format` is selectable in token submission form and `compiler version` has an example in textfield label. https://github.com/Magickbase/godwoken_explorer/issues/new?assignees=Keith-CY&labels=Contract+Registration&template=register-a-general-contract.yml&title=%5BGeneral+Contract%5D+%2A%2AContract+Name%2A%2A

**Comment by BourneNeo** [comment]
> Actually the `compiler file format` is selectable in token submission form and `compiler version` has an example in textfield label. https://github.com/Magickbase/godwoken_explorer/issues/new?assignees=Keith-CY&labels=Contract+Registration&template=register-a-general-contract.yml&title=%5BGeneral+Contract%5D+%2A%2AContract+Name%2A%2A

didn't get any better, maybe give an example, or put an quotation style in the 1st comment like this "solidity single file (Default)" ?
![image](https://user-images.githubusercontent.com/18527271/164371030-fd3776ac-8986-457e-8a13-d413bc67fc13.png)
![image](https://user-images.githubusercontent.com/18527271/164371168-9d9a4a88-44b6-4027-8a3b-6ae0e45102ed.png)

**Comment by Keith-CY** [comment]
A contract named `ss` has an empty `compiler_version`
![image](https://user-images.githubusercontent.com/7271329/164391463-e7f4936c-c940-4fa9-8a4b-f08799984ed1.png)

**Comment by BourneNeo** [comment]
> 

you can see look up 
can you please help point out what exactly I should put in the **Compiler Version** and **Compiler File Format** box ? An example would better.
