### ISSUE TITLE
[v1,v0]should v0 and v1 page be completely separated? really a big literally **mis-LEADING**

### ISSUE THREAD

**Issue by BourneNeo** [Magickbase/godwoken_explorer#399]
https://user-images.githubusercontent.com/18527271/164370499-c56b8ac5-4c56-47d0-8624-8edf24e7f938.mp4

**Comment by Keith-CY** [comment]
PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/153

**Comment by BourneNeo** [comment]
will the switching feature exist in the official online version?

**Comment by Keith-CY** [comment]
> will the switching feature exist in the official online version?

It will, this [PR](https://github.com/Magickbase/godwoken-explorer-ui/pull/158) restore the chain type switch but only `testnet` is allowed in godwoken v1.

**Comment by BourneNeo** [comment]
still on v1 page choose "testnet" jump to v0 page

https://user-images.githubusercontent.com/18527271/167319819-1d5a8194-6fda-41e6-b25b-f66df2ae6af4.mp4

**Comment by Keith-CY** [comment]
Fixed by redeploying with latest environment variables @BourneNeo
