### ISSUE TITLE
[v1]query contract detail page return invalid json response body

### ISSUE THREAD

**Issue by BourneNeo** [Magickbase/godwoken_explorer#401]
**both these 2 **
![image](https://user-images.githubusercontent.com/18527271/164416916-9fc903b5-29c1-4248-a69d-b910cfa62751.png)

![image](https://user-images.githubusercontent.com/18527271/164417161-dff0d7b6-e1ed-4664-a622-8ef538970ae3.png)

https://api.v1.aggron.gwscan.com/api/accounts/0x4211bfecc0ae4fb6361b6937079c416979d2fc46

**Comment by zmcNotafraid** [comment]
Two contract is repeated.
