### ISSUE TITLE
[v1] token view Cannot read properties of null (reading 'toLocaleString')

### ISSUE THREAD

**Issue by Flouse** [Magickbase/godwoken_explorer#402]
## URL
https://v1.aggron.gwscan.com/token/2558?tab=holders

<img width="853" alt="image" src="https://user-images.githubusercontent.com/1297478/164728456-d9e69c65-e7ca-4d7d-a39f-eebd7478b31c.png">

**Comment by zmcNotafraid** [comment]
Fixed. Some tx count return null.
