### ISSUE TITLE
[Native ERC20 Token] **testERC20**

### ISSUE THREAD

**Issue by Flouse** [Magickbase/godwoken_explorer#403]
### Token Name

testERC20

### Description

testERC20 Token on Godwoken testnet_v1.0

### Logo URI

https://cryptologos.cc/logos/tether-usdt-logo.svg?v=002

### Contract Address

0x4528EeD933D497cE11467E85382Ef2395aEb1ec1

### Code Format

solidity single file (Default)

### Deployment Transaction Hash

0xf70393b9fbbecaa7881242ba79a3eb244f553b1db1343cc2380c89d1e2643e86

### Compiler Version

0.8.6

### Contract Source Code

```Solidity
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract testERC20 is ERC20("testERC20","testERC20") {
  constructor() {
    // _mint(msg.sender, type(uint256).max);
    _mint(msg.sender, 10000);
  }
}
```

**Comment by Keith-CY** [comment]
This token is minted in v1

**Comment by zmcNotafraid** [comment]
Created at: https://v1.aggron.gwscan.com/token/20059
