### ISSUE TITLE
[Bridged Token] **GodwokenToken**

### ISSUE THREAD

**Issue by Flouse** [Magickbase/godwoken_explorer#404]
### Token Name

GodwokenToken

### Description

sUDT_ERC20_Proxy contract

### Symbol

GWK

### Decimals

18

### Logo URI

https://cryptologos.cc/logos/multi-collateral-dai-dai-logo.svg?v=002

### SUDT Script Arguments

0x5c7253696786b9eddd34e4f6b6e478ec5742bd36569ec60c1d0487480ba4f9e3

### Contract Address

0x6A5938a6Ca09eaF524456421fd418dDabc42444D

### Other Info

Only for test

**Comment by Keith-CY** [comment]
This token is bridged to v1

**Comment by zmcNotafraid** [comment]
@Flouse  这个是不是没有充值成功，账户里找不到这个udt （0x5c7253696786b9eddd34e4f6b6e478ec5742bd36569ec60c1d0487480ba4f9e3）

**Comment by Flouse** [comment]
### 这里有显示充值成功的记录：
https://explorer.nervos.org/aggron/address/0x5c7253696786b9eddd34e4f6b6e478ec5742bd36569ec60c1d0487480ba4f9e3

### 看看这个 [Action Run](https://github.com/Flouse/layer2-evm-documentation/runs/6132977043?check_suite_focus=true#step:10:81) 里的几个地址？
- https://v1.aggron.gwscan.com/account/0x8291507afda0bba820efb6dfa339f09c9465215c?tab=assets
- https://v1.aggron.gwscan.com/account/0x0c1efcca2bcb65a532274f3ef24c044ef4ab6d73?tab=assets

**Comment by zmcNotafraid** [comment]
> 0x5c7253696786b9eddd34e4f6b6e478ec5742bd36569ec60c1d0487480ba4f9e3

收到，确认了下数据没问题，是我把script args 看成script hash 了，已经找到了

**Comment by zmcNotafraid** [comment]
Created At: https://v1.aggron.gwscan.com/token/11243
