### ISSUE TITLE
query account's  ERC20 TRANSFERS page return invalid json response body 

### ISSUE THREAD

**Issue by BourneNeo** [Magickbase/godwoken_explorer#410]
![image](https://user-images.githubusercontent.com/18527271/165012276-b8ca1c9d-3de3-4bda-8965-babcffe6f393.png)

![image](https://user-images.githubusercontent.com/18527271/165012217-c2bc8252-4fba-451d-a4ba-7ba515f979d5.png)
https://api.v1.aggron.gwscan.com/api/transfers?eth_address=0x56a079b315daebd310ba9a8b45a1302856b2aa70

**Comment by zmcNotafraid** [comment]
fixed.
