### ISSUE TITLE
[v0] Internal Server Error.

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#420]
url:https://gwscan.com/zh-CN/token/1?tab=holders
<img width="963" alt="image" src="https://user-images.githubusercontent.com/32102187/165058019-39c0feb2-f251-492b-9715-b7b3478fe5d4.png">
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/32102187/165058552-1c8782d1-7871-4bd4-8f05-0e130bdf3e35.png">

**Comment by zmcNotafraid** [comment]
https://api.gwscan.com/api/account_udts?udt_id=27221
