### ISSUE TITLE
searching failed got a browser notice "failed to fetch" and console message "net::ERR_CONNECTION_CLOSED" 

### ISSUE THREAD

**Issue by BourneNeo** [Magickbase/godwoken_explorer#424]
![image](https://user-images.githubusercontent.com/18527271/165214054-14f1098e-0fbc-4348-91a5-288c5027c368.png)
https://api.v1.aggron.gwscan.com/api/search?keyword=0x67f3a43a0ca9b3f63d6d108266cf756668bee231b0c9ede4c55ad371b2be02ca

**Comment by Keith-CY** [comment]
Is this issue reproducible?
