### ISSUE TITLE
[v1] query l2 native token holders page return Cannot read properties of undefined (reading 'toLocaleString'),refreshing return Internal Server Error.

### ISSUE THREAD

**Issue by BourneNeo** [Magickbase/godwoken_explorer#425]
![image](https://user-images.githubusercontent.com/18527271/165240202-8145ec9e-31b0-43f8-92d4-bdd26da3b729.png)

![image](https://user-images.githubusercontent.com/18527271/165239733-2611548a-0ffe-4a67-b72c-45672baa1330.png)
![image](https://user-images.githubusercontent.com/18527271/165239930-dcde123b-2a9b-4a98-be0c-36b48040b53e.png)

https://v1.aggron.gwscan.com/_next/data/Z7wHcxK9CxOV1UFX8-Hz6/en-US/token/20059.json?tab=holders&id=20059

**Comment by Keith-CY** [comment]
![image](https://user-images.githubusercontent.com/7271329/165242549-461c5d10-3eaf-48bf-967b-6dbda955194e.png)

`tx_count` is missing in the response of holder list @zmcNotafraid

**Comment by zmcNotafraid** [comment]
fixed
