### ISSUE TITLE
[v0,v1]deploy tx  should show deploy contractAddress

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#426]
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/32102187/165240615-3805befd-d4fd-4259-84fe-1905e65e6572.png">

**Comment by zmcNotafraid** [comment]
https://api.v1.aggron.gwscan.com/api/txs/0xc01d8f64c4180e0ba8ea0e08c742ab244533dfdc87d41f6c1cff5ff88847f423
return created_contract_address_hash

**Comment by Keith-CY** [comment]
PR of front-end: https://github.com/Magickbase/godwoken-explorer-ui/pull/167

**Comment by Keith-CY** [comment]
https://v1.aggron.gwscan.com/tx/0xc01d8f64c4180e0ba8ea0e08c742ab244533dfdc87d41f6c1cff5ff88847f423
