### ISSUE TITLE
[v1] eth address Registry not show index 

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#439]
https://v1.aggron.gwscan.com/tx/0x0a082ed8f1e92b431541f6028aecf33bd610d3cffd096aa1a2b2f63a43b23a8b
<img width="948" alt="image" src="https://user-images.githubusercontent.com/32102187/165692225-fcc30adb-7512-4308-bda2-58865ca13e1c.png">

**Comment by Keith-CY** [comment]
Is this tx packaged in blocks returned from godwoken-web3? @zmcNotafraid

**Comment by Keith-CY** [comment]
Hide `index`

**Comment by Keith-CY** [comment]
PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/172
