### ISSUE TITLE
[v0] click page:1376 ,but show 1276

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#441]
https://gwscan.com/zh-CN/token/1?tab=holders&id=1&page=1376
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/32102187/165705416-dbbdf323-57ee-424a-a9bb-4b7b26f946ca.png">

https://gwscan.com/_next/data/BsgiYXQluYKjjpN5_FwsS/zh-CN/token/1.json?tab=holders&id=1&page=1376
<img width="800" alt="image" src="https://user-images.githubusercontent.com/32102187/165704982-153275d4-a198-4c8b-903d-21422ec20fc2.png">

**Comment by gpBlockchain** [comment]
https://www.gwscan.com/_next/data/BsgiYXQluYKjjpN5_FwsS/en-US/account/0xf17fa46ca29fc8e8d563961c755bec2a7bae5745.json?id=0xf17fa46ca29fc8e8d563961c755bec2a7bae5745&page=9

https://www.gwscan.com/_next/data/BsgiYXQluYKjjpN5_FwsS/en-US/account/0xf17fa46ca29fc8e8d563961c755bec2a7bae5745.json?id=0xf17fa46ca29fc8e8d563961c755bec2a7bae5745&page=10
result is same

**Comment by Keith-CY** [comment]
The `page_size` is also deserved a notice, it's 8 but not 10

**Comment by Keith-CY** [comment]
API: https://api.gwscan.com/api/account_udts?udt_id=1&page=1376

**Comment by Keith-CY** [comment]
Now I visit page 1064 https://gwscan.com/zh-CN/token/1?page=1064&tab=holders&id=1 , it will fallback to the last page 1062 @gpBlockchain
