### ISSUE TITLE
[v0] get account by account addresses deployment_ tx_ Hash is empty

### ISSUE THREAD

**Issue by Dawn-githap** [Magickbase/godwoken_explorer#442]
example:
test-net(https://api.aggron.gwscan.com/graphql) ,get account by account addresses、deployment_ tx_ Hash is empty

expect result:
request-example:

    query {
    account(input: {address: "0xc5e133e6b01b2c335055576c51a53647b1b9b624"}){
      id
      type
      smart_contract{
        id
        name
        deployment_tx_hash
      }
    }
  }
result-example:

    {
    "data": {
      "account": {
        "id": 3014,
        "smart_contract": {
          "deployment_tx_hash": "0x0000000000",
          "id": 1,
          "name": "YOKAI"
        },
        "type": "POLYJUICE_CONTRACT"
      }
    }
  }
but now:
request example:

    query {
    account(input: {address: "0xc5e133e6b01b2c335055576c51a53647b1b9b624"}){
      id
      type
      smart_contract{
        id
        name
        deployment_tx_hash
      }
    }
  }
result example:
```
{
  "data": {
    "account": {
      "id": 3014,
      "smart_contract": {
        "deployment_tx_hash": null,
        "id": 1,
        "name": "YokaiSwap Token"
      },
      "type": "POLYJUICE_CONTRACT"
    }
  }
}
```

**Comment by Naupio** [comment]
deployment_tx_Hash field was need login dashboard (backend admin) to edit 

link : (`https://api.aggron.gwscan.com/admin`)[https://api.aggron.gwscan.com/admin]

@Dawn-githap
