### ISSUE TITLE
[v1] native token detail page failed showing transfer data

### ISSUE THREAD

**Issue by BourneNeo** [Magickbase/godwoken_explorer#444]
0x335434ef0179a4208cc1a3801eeddbc52e1edadda9d615361ab9771267112a48
0xa8607805ee4deb29ec7d983769dfadc71580aeae1fbea9d25aa8a723a63e60d5
![image](https://user-images.githubusercontent.com/18527271/165723790-936fac1a-6966-4de2-8ea0-aaae475edeb3.png)

**Comment by Keith-CY** [comment]
It seems that API returns inconsistent data

https://api.aggron.gwscan.com/api/transfers?tx_hash=0xa8607805ee4deb29ec7d983769dfadc71580aeae1fbea9d25aa8a723a63e60d5
returns `transfer count = 1` while list is empty

https://api.v1.aggron.gwscan.com/api/udts/20582 returns `transfer count = 0` but the list has three records
![image](https://user-images.githubusercontent.com/7271329/165786976-0391de2b-3feb-4cc9-9b9d-bee0273da862.png)

@zmcNotafraid
