### ISSUE TITLE
[v0] Contract Account erc20 transfer'address not equal contract address 

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#447]
https://www.gwscan.com/account/0xb02c930c2825a960a50ba4ab005e8264498b64a0?tab=erc20
If the from or to of the erc20 transfer is the contract address, it will be different from the displayed contract address

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/32102187/165760924-2c23fe27-a671-48b2-8748-fe63bd7ad513.png">

**Comment by Keith-CY** [comment]
Is this related to `short_address` and `eth_address` in godwoken v0? `0xb02c930C2825A960A50ba4Ab005e8264498b64a0` is decoded from the transaction's input data and it equals to the contract address. @zmcNotafraid

**Comment by zmcNotafraid** [comment]
> 

V0 should use short_address. I confused with v1. Fixed now
