### ISSUE TITLE
[v1] native token name changed when displayed on the page

### ISSUE THREAD

**Issue by BourneNeo** [Magickbase/godwoken_explorer#453]
![image](https://user-images.githubusercontent.com/18527271/165896603-ec10a303-f40e-40e6-8493-da720f9e3814.png)

![image](https://user-images.githubusercontent.com/18527271/165896496-040ddf1a-310f-4437-8c78-eba10500b791.png)

**Comment by zmcNotafraid** [comment]
In usual, the token name‘s initial should be capital.
