### ISSUE TITLE
[v1] native token detail page failed show total transfer count

### ISSUE THREAD

**Issue by BourneNeo** [Magickbase/godwoken_explorer#454]
![image](https://user-images.githubusercontent.com/18527271/165898552-5543be5b-6a56-47e4-a3aa-d96ffd53e72d.png)

https://v1.aggron.gwscan.com/zh-CN/token/20582?tab=transfers

**Comment by zmcNotafraid** [comment]
> ![image](https://user-images.githubusercontent.com/18527271/165898552-5543be5b-6a56-47e4-a3aa-d96ffd53e72d.png)

Plese leave the url, we need to check data

**Comment by BourneNeo** [comment]
> > ![image](https://user-images.githubusercontent.com/18527271/165898552-5543be5b-6a56-47e4-a3aa-d96ffd53e72d.png)
> 
> Plese leave the url, we need to check data

url added
