### ISSUE TITLE
[v1] Click on the upper and lower pages, there will be problems with transfer list

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#463]
https://v1.aggron.gwscan.com/zh-CN/token/11243?page=2&tab=transfers&id=11243
#### step 
1. click Prev
2. click Next

#### response 
1. before click Prev ,
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/32102187/166869585-3680670d-82f2-472f-be8d-ede1f4425cc8.png">
2. after click next
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/32102187/166869663-ae1317c6-b704-4167-8fd2-5313a8a0e262.png">

**Comment by gpBlockchain** [comment]
https://user-images.githubusercontent.com/32102187/166870494-5c65e1ca-6635-46d3-9d83-4ab7ee443af1.mov

**Comment by Keith-CY** [comment]
Please return `log_index` within the transfer list so that front-end can differ two transfers with `tx hash + log index`

**Comment by zmcNotafraid** [comment]
> Please return `log_index` within the transfer list so that front-end can differ two transfers with `tx hash + log index`

Return log_index:integer now

**Comment by Keith-CY** [comment]
Front-end PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/183

**Comment by Keith-CY** [comment]
Fixed @gpBlockchain

**Comment by Keith-CY** [comment]
Please have a review @gpBlockchain
