### ISSUE TITLE
[v0]graphql failed to recognize addresse with mixed case letters

### ISSUE THREAD

**Issue by BourneNeo** [Magickbase/godwoken_explorer#466]
![image](https://user-images.githubusercontent.com/18527271/166878320-071beaac-3cd6-44d0-b705-4c849985d495.png)

![image](https://user-images.githubusercontent.com/18527271/166878273-a8728d0d-2ae0-41ac-ba8b-92bfd9555320.png)

**Comment by Keith-CY** [comment]
@xiefei1024 could we close this issue?

**Comment by xiefei1024** [comment]
please close
