### ISSUE TITLE
[v1] Holder did not update account

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#467]
transfer token to contract account 
https://v1.aggron.gwscan.com/tx/0x397728d6800690c826ad481cd9967e62c12b15e7df6e70a219325883b22fd32c
https://v1.aggron.gwscan.com/tx/0x72542c02b04a4f2fc77f753a0b1477c1ef4d353c239024fee53af4b841afe484
check holder
https://v1.aggron.gwscan.com/token/11243?tab=holders
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/32102187/166881777-9893a92d-c777-4e8f-a6dd-6e494e97ab0e.png">

**Comment by gpBlockchain** [comment]
https://v1.aggron.gwscan.com/account/0x6a5938a6ca09eaf524456421fd418ddabc42444d?tab=erc20 asset is empty
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/32102187/166882448-7e122743-a44a-4fda-ac20-856e89b84d07.png">

**Comment by zmcNotafraid** [comment]
When I query 0x6a5938a6ca09eaf524456421fd418ddabc42444d's token balance with eth_call rpc method. I got this error:
```
[
  error: %{
    code: -32099,
    data: %{
      "failed_reason" => %{
        "message" => "sender doesn't have enough funds to send tx",
        "status_code" => "0x5c",
        "status_type" => "SUDT_ERROR_INSUFFICIENT_BALANCE"
      }
    },
    message: "sudt_error_insufficient_balance: sender doesn't have enough funds to send tx"
  }
]
```
That's why it doesn't have token balance
