### ISSUE TITLE
[v1] in same block,Transactions are not ordered by time

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#469]
in same block ,Transactions are not ordered by time
https://v1.aggron.gwscan.com/token/21289?tab=transfers
<img width="1364" alt="image" src="https://user-images.githubusercontent.com/32102187/166903784-1ba1ebfb-2bbf-43e4-8b14-5c08b96a6607.png">
https://v1.aggron.gwscan.com/tx/0x8c868faedb3ed672de5cccc4a6a3d4cd86487aa2d6e8be550c184d4585a4790a
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/32102187/166904765-9cbf447d-8eda-4553-b2f4-83cad35cc86c.png">

**Comment by zmcNotafraid** [comment]
For first API, It's sort by block_number desc first, then sort by transaction log index. So for 137024 block, first 0x8c's log index is 128, secondd 137024 block's 0x8c log index is 127.

**Comment by gpBlockchain** [comment]
> For first API, It's sort by block_number desc first, then sort by transaction log index. So for 137024 block, first 0x8c's log index is 128, secondd 137024 block's 0x8c log index is 127.

I think it should be sorted in this order:`blockNumber` >`transactionIndex`>`logIndex` 
The following is a log of information
```
{"address":"0x366110aba00a4cb025039239c0b85bd13a757500","blockHash":"0x0dbaa8dbd8b3abdf5fe34634c8d2df1889047157645a73c8d3d4ce43f00cd920","blockNumber":"0x21740","transactionIndex":"0x2","transactionHash":"0xe952e18f0ad5c2f844287fef1655266326e9244f9cb364e1f08344b3614d12ac","data":"0x0000000000000000000000000000000000000000000000000000000000000037","logIndex":"0x6e","topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef","0x0000000000000000000000000c1efcca2bcb65a532274f3ef24c044ef4ab6d73","0x000000000000000000000000000000000000000000000000000000006273a28c"],"removed":false}
```

**Comment by zmcNotafraid** [comment]
> 

For current token_transfers table, we do not record transaction index, so it's hard to achieve  this function

**Comment by Naupio** [comment]
token transfer api support custom sorter to do this function,
here is an example:
```graphql
    query {
      token_transfers(
        input: {
          from_address: "0x966b30e576a4d6731996748b48dd67c94ef29067"
          to_address: "0xbd6250d17fc557dfe39a9eb3882c421d4c7f6413"
          start_block_number: 90
          end_block_number: 909999
          age_range_end: "2022-05-08T05:19:26.237000Z"
          limit: 1
          combine_from_to: true
          sorter: [
            { sort_type: ASC, sort_value: BLOCK_NUMBER }
            { sort_type: ASC, sort_value: TRANSACTION_HASH }
            { sort_type: ASC, sort_value: LOG_INDEX }
          ]
        }
      ) {
        entries {
          block {
            timestamp
          }
          transaction_hash
          block_number
          to_account {
            eth_address
          }
          to_address
          from_account {
            eth_address
          }
        }
        metadata {
          total_count
          before
          after
        }
      }
    }
```
