### ISSUE TITLE
[v1] assert balance display error

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#470]
https://v1.aggron.gwscan.com/account/0x0c1efcca2bcb65a532274f3ef24c044ef4ab6d73?tab=assets
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/32102187/166906241-78b89301-f9f6-4c8e-a6db-9b0b0dc0eeb5.png">

**Comment by zmcNotafraid** [comment]
Fixed.

**Comment by gpBlockchain** [comment]
我通过合约查询的结果
Test Tether USD: 28999999.99999 , 浏览器显示为29,000,000
？token ,从用户角度无法得知该token的具体信息
godwoken Token : 0.000000000000000103 浏览器显示为 0.00000000000000016
usdc token: 685 ,浏览器显示为 685
 
![image](https://user-images.githubusercontent.com/32102187/168245820-ad9a084d-16c7-4486-b885-b6e8ab748432.png)

所以我这边得确认3个问题:
1. 用户资产余额在什么时候会以四舍五入的方式展示
2. 我如何去确认 ？token 为哪种资产
3. godwoken Token 余额为何展示错误

**Comment by zmcNotafraid** [comment]
> @zmcNotafraid 我通过合约查询的结果 Test Tether USD: 28999999.99999 , 浏览器显示为29,000,000 ？token ,从用户角度无法得知该token的具体信息 godwoken Token : 0.000000000000000103 浏览器显示为 0.00000000000000016 usdc token: 685 ,浏览器显示为 685
> 
> ![image](https://user-images.githubusercontent.com/32102187/168245820-ad9a084d-16c7-4486-b885-b6e8ab748432.png)
> 
> 所以我这边得确认3个问题:
> 
> 1. 用户资产余额在什么时候会以四舍五入的方式展示
> 2. 我如何去确认 ？token 为哪种资产
> 3. godwoken Token 余额为何展示错误

1 和 3 不会四舍五入展示，token 展示错误只能说是有些token 的更新动作我们没有捕捉到，目前只有在用户通过erc20 转账的时候才会更新token，但是不确定是否有其他更新token 的动作
2. 这种token 都是用户从layer1 充值过来，但是没有绑定对应的合约，所以我们也无从得知这个token 是什么，除非发行方提供相关信息

**Comment by gpBlockchain** [comment]
> > @zmcNotafraid 我通过合约查询的结果 Test Tether USD: 28999999.99999 , 浏览器显示为29,000,000 ？token ,从用户角度无法得知该token的具体信息 godwoken Token : 0.000000000000000103 浏览器显示为 0.00000000000000016 usdc token: 685 ,浏览器显示为 685
> > ![image](https://user-images.githubusercontent.com/32102187/168245820-ad9a084d-16c7-4486-b885-b6e8ab748432.png)
> > 所以我这边得确认3个问题:
> > 
> > 1. 用户资产余额在什么时候会以四舍五入的方式展示
> > 2. 我如何去确认 ？token 为哪种资产
> > 3. godwoken Token 余额为何展示错误
> 
> 1. 正常我们不会让他四舍五入展示，但是目前确实是通过sql 直接计算的结果有问题
> 2. 这种token 都是用户从layer1 充值过来，但是没有绑定对应的合约，所以我们也无从得知这个token 是什么，除非发行方提供相关信息
> 3. token 展示错误可能是有些token 的更新动作我们没有捕捉到，目前只有在用户通过erc20 转账的时候才会更新token，但是不确定是否有其他更新token 的动作

1.  那要修复sql计算出错吗？
2. 那这种token展示算bug吗，不知道是否要处理这个问题？
3. godwoken 代币为桥接代币,我转移他的方式必然有event Transfer 事件产生,不知道是否需要进一步定位为什么没有捕获到的原因？我看到holder页面展示的godwoken余额是正确的
![image](https://user-images.githubusercontent.com/32102187/168255706-be52e9a7-19a5-41ea-9e16-a41e7823670a.png)

**Comment by zmcNotafraid** [comment]
> > > @zmcNotafraid 我通过合约查询的结果 Test Tether USD: 28999999.99999 , 浏览器显示为29,000,000 ？token ,从用户角度无法得知该token的具体信息 godwoken Token : 0.000000000000000103 浏览器显示为 0.00000000000000016 usdc token: 685 ,浏览器显示为 685
> > > ![image](https://user-images.githubusercontent.com/32102187/168245820-ad9a084d-16c7-4486-b885-b6e8ab748432.png)
> > > 所以我这边得确认3个问题:
> > > 
> > > 1. 用户资产余额在什么时候会以四舍五入的方式展示
> > > 2. 我如何去确认 ？token 为哪种资产
> > > 3. godwoken Token 余额为何展示错误
> > 
> > 
> > 
> > 1. 正常我们不会让他四舍五入展示，但是目前确实是通过sql 直接计算的结果有问题
> > 2. 这种token 都是用户从layer1 充值过来，但是没有绑定对应的合约，所以我们也无从得知这个token 是什么，除非发行方提供相关信息
> > 3. token 展示错误可能是有些token 的更新动作我们没有捕捉到，目前只有在用户通过erc20 转账的时候才会更新token，但是不确定是否有其他更新token 的动作
> 
> 1. 那要修复sql计算出错吗？
> 2. 那这种token展示算bug吗，不知道是否要处理这个问题？
> 3. godwoken 代币为桥接代币,我转移他的方式必然有event Transfer 事件产生,不知道是否需要进一步定位为什么没有捕获到的原因？我看到holder页面展示的godwoken余额是正确的
>    ![image](https://user-images.githubusercontent.com/32102187/168255706-be52e9a7-19a5-41ea-9e16-a41e7823670a.png)

1. 会修复，我不在用sql 计算，改用后台代码计算
2. 这种其实展示不展示是一个产品问题，目前是展示的，因为用户充值进来了，虽然没有绑定对应的合约，但确实是一个token，只是我们不知道他的任何信息。这个可以讨论下 @Keith-CY 
3.  这个问题我需要在对比下数据，现在不能下结论

**Comment by Keith-CY** [comment]
关于第 2 点是否展示未知类型的 token 记录, 其他区块链产品上的选择大都是展示的(用户往往在不知情的情况下收到 token, 比如空投), 用户资产列表中需要展示真实持有的资产, 那么转入的记录必然也要展示出来, 否则无法对上记录.

用户无法获知得到的是哪种 token, 我们可以做一下优化, 在 token 的条目中增加跳转到对应合约账户的链接, 虽然没有 token 信息, 但是用户可以通过合约信息确认 token 来源.

这个功能已经有 issue, 且 graphql 接口已经支持, 我正在逐步将 graphql 接入浏览器.

**Comment by Keith-CY** [comment]
Token 跳转到对应页面的 issue, 有些许区别但是目的一致 https://github.com/Magickbase/godwoken_explorer/issues/363
