### ISSUE TITLE
[v1] Asset information will not be displayed without registration and contract address

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#471]
#### contract 
transfer assert tx: 
https://v1.aggron.gwscan.com/account/0x6a5938a6ca09eaf524456421fd418ddabc42444d?tab=assets
<img width="972" alt="image" src="https://user-images.githubusercontent.com/32102187/166907514-bdc14893-e2ca-40ad-9a1f-3bb9583a0a4b.png">

https://v1.aggron.gwscan.com/tx/0x4a405d64b5adbd18e89ded1d68cf55ff0e8df58418a50baef3925666128eea43
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/32102187/166907445-bb61283a-1696-4429-b1d2-f90416f10e0d.png">

#### without registration
transfer assert tx: https://v1.aggron.gwscan.com/tx/0x1d99e442c96b67e8d8f63221a1035a2407534a4ea7d1cf9b16f92f1963d029ea
https://v1.aggron.gwscan.com/account/0x000000000000000000000000000000006273a254
<img width="974" alt="image" src="https://user-images.githubusercontent.com/32102187/166907580-b2b77c6c-1170-442d-9304-95576d301198.png">

**Comment by zmcNotafraid** [comment]
0x000000000000000000000000000000006273a254 this address is not exist in our database.

**Comment by zmcNotafraid** [comment]
We fetch 0x6a5938a6ca09eaf524456421fd418ddabc42444d address's by eth_call rpc method and got this error.
```
[
  error: %{
    code: -32099,
    data: %{
      "failed_reason" => %{
        "message" => "sender doesn't have enough funds to send tx",
        "status_code" => "0x5c",
        "status_type" => "SUDT_ERROR_INSUFFICIENT_BALANCE"
      }
    },
    message: "sudt_error_insufficient_balance: sender doesn't have enough funds to send tx"
  }
]
```
So maybe contract address can't get balance of itself

**Comment by gpBlockchain** [comment]
> We fetch 0x6a5938a6ca09eaf524456421fd418ddabc42444d address's by eth_call rpc method and got this error.
> 
> ```
> [
>   error: %{
>     code: -32099,
>     data: %{
>       "failed_reason" => %{
>         "message" => "sender doesn't have enough funds to send tx",
>         "status_code" => "0x5c",
>         "status_type" => "SUDT_ERROR_INSUFFICIENT_BALANCE"
>       }
>     },
>     message: "sudt_error_insufficient_balance: sender doesn't have enough funds to send tx"
>   }
> ]
> ```
> 
> So maybe contract address can't get balance of itself

这边调用失败算是兼容性问题, 我这边测试了一下使用未注册账户，合约账号去调用eth_call 和 eth_estimateGas 方法,这边确认下godwoken 是否修复使用未注册账户或合约账户调用 eth_call 方法和 eth_estimateGas 不会报错，要不然这边查询asset的from 就不能使用 未注册的账户或合约账户

以下为设计的测试用例和测试结果

#### test invoke method
```
function public_func() public view returns(uint256) {
        return 1;
    }
```
#### test case  
1. test `eth_call` invoke `public_func` method  use from is contract address
2. test `eth_estimateGas` invoke  `public_func` method use from is contract address 
3. test `eth_call invoke` invoke `public_func` method  use unregistered address
4. test `eth_estimateGas` invoke `public_func` method  use unregistered address

#### hardhat ,bsc,eth (step 1,2 response )
```
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_call',
  params: [
    {
      from: '0x59B69f407e020fD4d9AcA7Be96299fDba9C44F2e',
      to: '0x59B69f407e020fD4d9AcA7Be96299fDba9C44F2e',
      data: '0x2a9e9ea8'
    },
    'latest'
  ],
  id: 29
}
jsonRpcResponse: {
  jsonrpc: '2.0',
  id: 29,
  result: '0x0000000000000000000000000000000000000000000000000000000000000001'
}
result: 0x0000000000000000000000000000000000000000000000000000000000000001
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_estimateGas',
  params: [
    {
      from: '0x59B69f407e020fD4d9AcA7Be96299fDba9C44F2e',
      to: '0x59B69f407e020fD4d9AcA7Be96299fDba9C44F2e',
      data: '0x2a9e9ea8'
    }
  ],
  id: 30
}
jsonRpcResponse: { jsonrpc: '2.0', id: 30, result: '0x5307' }
```
#### godwoken v1.1 response (step 1,2 response )
```
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_call',
  params: [
    {
      from: '0x0da803A251bc3263a12635FEcE52660Bc78380F1',
      to: '0x0da803A251bc3263a12635FEcE52660Bc78380F1',
      data: '0x2a9e9ea8'
    },
    'latest'
  ],
  id: 17
}
jsonRpcResponse: {
  jsonrpc: '2.0',
  id: 17,
  result: '0x0000000000000000000000000000000000000000000000000000000000000001'
}
result: 0x0000000000000000000000000000000000000000000000000000000000000001
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_estimateGas',
  params: [
    {
      from: '0x0da803A251bc3263a12635FEcE52660Bc78380F1',
      to: '0x0da803A251bc3263a12635FEcE52660Bc78380F1',
      data: '0x2a9e9ea8'
    }
  ],
  id: 18
}
jsonRpcResponse: { jsonrpc: '2.0', id: 18, result: '0xbf' }
result: 0xbf
```
#### godwoken v1.0 response (step 1,2 response )
```
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_call',
  params: [
    {
      from: '0xd98a4D4B29D535813DBc2bbf0540411f036C1200',
      to: '0xd98a4D4B29D535813DBc2bbf0540411f036C1200',
      data: '0x2a9e9ea8'
    },
    'latest'
  ],
  id: 17
}
jsonRpcResponse: {
  jsonrpc: '2.0',
  id: 17,
  error: {
    code: -32099,
    message: "sudt_error_insufficient_balance: sender doesn't have enough funds to send tx",
    data: { failed_reason: [Object] }
  }
}
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_estimateGas',
  params: [
    {
      from: '0xfce2797C0887901f78976579598Ac160a4EDa1F4',
      to: '0xfce2797C0887901f78976579598Ac160a4EDa1F4',
      data: '0x2a9e9ea8'
    }
  ],
  id: 18
}
jsonRpcResponse: {
  jsonrpc: '2.0',
  id: 18,
  error: {
    code: -32099,
    message: "sudt_error_insufficient_balance: sender doesn't have enough funds to send tx"
  }
}
```
#### godwoken v1.1 response (step 3,4 response )
```
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_call',
  params: [
    {
      from: '0x8974eD1cfA93B1E28E11005E3eA88AF814521131',
      to: '0xb22CAe7ba2C7865302F86dcfDeD29Ef6Ef9B0Cc3',
      data: '0x2a9e9ea8'
    },
    'latest'
  ],
  id: 17
}
jsonRpcResponse: {
  jsonrpc: '2.0',
  id: 17,
  error: {
    code: -32099,
    message: 'from id not found by from address: 0x8974eD1cfA93B1E28E11005E3eA88AF814521131, have you deposited?'
  }
}
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_estimateGas',
  params: [
    {
      from: '0x8974eD1cfA93B1E28E11005E3eA88AF814521131',
      to: '0xb22CAe7ba2C7865302F86dcfDeD29Ef6Ef9B0Cc3',
      data: '0x2a9e9ea8'
    }
  ],
  id: 18
}
jsonRpcResponse: {
  jsonrpc: '2.0',
  id: 18,
  error: {
    code: -32099,
    message: 'UNPREDICTABLE_GAS_LIMIT: from id not found by from address: 0x8974eD1cfA93B1E28E11005E3eA88AF814521131, have you deposited?'
  }
}

```
#### godwoken v1.0 response (step 3,4 response )

```
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_call',
  params: [
    {
      from: '0x8974eD1cfA93B1E28E11005E3eA88AF814521131',
      to: '0xDC78629A358B417d046f9161F34a1c43016C9c51',
      data: '0x2a9e9ea8'
    },
    'latest'
  ],
  id: 17
}
jsonRpcResponse: {
  jsonrpc: '2.0',
  id: 17,
  error: { code: -32099, message: 'from id not found!' }
}
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_estimateGas',
  params: [
    {
      from: '0x8974eD1cfA93B1E28E11005E3eA88AF814521131',
      to: '0xDC78629A358B417d046f9161F34a1c43016C9c51',
      data: '0x2a9e9ea8'
    }
  ],
  id: 18
}
jsonRpcResponse: {
  jsonrpc: '2.0',
  id: 18,
  error: { code: -32099, message: 'from id not found!' }
}


```

#### 测试结果总结
1. 结果显示为调用eth_call 和 eth_estimateGas v1.1是支持from为合约地址,但还是不支持from 为未注册的地址
2. v1.0 不支持from 为合约地址或未注册的地址

#### QA
1. v1.1 是否要修改eth_call 和 eth_estimateGas  支持from 为未注册地址 @Flouse 
2. 前端这边展示资产的from 是否要修改成一个已经注册的账户还是等待v1.1支持 未注册账户或合约地址调用eth_call和 eth_estimateGas @zmcNotafraid

**Comment by Flouse** [comment]
> 测试结果总结
> 1. 结果显示为调用eth_call 和 eth_estimateGas v1.1是支持from为合约地址,但还是不支持 from 为未注册的地址
> 2. v1.0 不支持from 为合约地址或未注册的地址

1. 结果符合当前版本的预期。
   在该 [改进](https://github.com/nervosnetwork/godwoken-web3/issues/337#issuecomment-1125603223) 后，将支持 from 为未注册的地址

cc @zeroqn
