### ISSUE TITLE
[v1] Unregistered account query ERC20 transfer

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#472]
https://v1.aggron.gwscan.com/account/0x000000000000000000000000000000006273a3da
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/32102187/166909016-d6d4c09a-4d80-4206-b5c4-1d5d692be806.png">
#### response
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/32102187/166909295-6d73d6b2-3631-46a2-b7c7-29b3abcd0ae0.png">

**Comment by zmcNotafraid** [comment]
0x000000000000000000000000000000006273a3da is not exist in our database.So some condition are not match.Fixed
