### ISSUE TITLE
[v1] there's an untraceable token in the asset 

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#475]
https://v1.aggron.gwscan.com/_next/data/dEd-yG8PjOUZgmXsVOs_F/en-US/account/0x56a079b315daebd310ba9a8b45a1302856b2aa70.json?tab=assets&id=0x56a079b315daebd310ba9a8b45a1302856b2aa70
https://v1.aggron.gwscan.com/account/0x56a079b315daebd310ba9a8b45a1302856b2aa70?tab=assets
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/32102187/167058202-6c0d639e-df58-441f-a25e-6f22b2d41e0f.png">

https://v1.aggron.gwscan.com/token/20144
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/32102187/167058545-37a4545b-61b9-4c89-8bb9-43bb10d81050.png">

**Comment by zmcNotafraid** [comment]
This udt is a bridge token but without proxy contract,now  it can visit.

**Comment by gpBlockchain** [comment]
> This udt is a bridge token but without proxy contract,now it can visit.

https://v1.aggron.gwscan.com/token/20144  totalSupply != sum(holders) 
![image](https://user-images.githubusercontent.com/32102187/168252844-1f2565f5-69e3-434d-8693-38606b20bea1.png)
