### ISSUE TITLE
[v1] You're visiting a polyjuice transaction with a gw_hash which is just for developers, please use an eth_hash() instead

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#476]
#### step 
1. click txHash url 
https://v1.aggron.gwscan.com/account/0x56109495d7a3d94f5e7b80280679b339e87bc237?tab=transactions
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/32102187/167062450-4aad65ba-fcbe-42d8-b5e4-9d91dedb58a3.png">
https://v1.aggron.gwscan.com/tx/0x45af147883a0d5cbc4a3f09feaf767c29513218ae69fb2893fc3f6e99d3f78b8
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/32102187/167062489-aa1f0f31-d8e5-46a1-862f-e8ef436244fb.png">

**Comment by zmcNotafraid** [comment]
It caused by wrong eth_tx_hash and gw_tx_hash binding.Now it's fixed
