### ISSUE TITLE
[v1] Select blocks list to jump to the last column of data, and the next button will be displayed at the bottom

### ISSUE THREAD

**Issue by Dawn-githap** [Magickbase/godwoken_explorer#477]
![image](https://user-images.githubusercontent.com/77844990/167063267-1959b2ae-60c1-4979-a669-8b7419d75468.png)

**Comment by Cedar67** [comment]
Regression test result: Resolved in testnet Env
Environment: https://godwoken-explorer-ui-git-fork-qiweiii-fix-brush-nervosnet.vercel.app

test Result:

https://user-images.githubusercontent.com/64718893/169793927-f4b290f4-110e-44ec-9f8a-6ca3053ded86.mp4

**Comment by Dawn-githap** [comment]
V1.1 scan validation fixed
