### ISSUE TITLE
[v1] should handle requests with unsupported content in a more appropriate way

### ISSUE THREAD

**Issue by BourneNeo** [Magickbase/godwoken_explorer#485]
![image](https://user-images.githubusercontent.com/18527271/167229187-21616bea-5658-4913-867c-9395b39b9840.png)

https://v1.aggron.gwscan.com/error?message=invalid%20json%20response%20body%20at%20https://api.v1.aggron.gwscan.com/api/transfers?tx_hash=undefined&page=1%20reason:%20Unexpected%20end%20of%20JSON%20input

**Comment by Keith-CY** [comment]
A correct massage like `invalid query string "undefined"` should be returned.

BTW, is this error triggered by clicking a link to a transaction? @BourneNeo

**Comment by BourneNeo** [comment]
> 

yes, from metamask, so it's a compatibility issue, also

**Comment by zmcNotafraid** [comment]
Fixed
