### ISSUE TITLE
[v1] When covering the entire time axis, the cursor hovering prompt at the right end of the time range bar is not completely displayed

### ISSUE THREAD

**Issue by BourneNeo** [Magickbase/godwoken_explorer#489]
vulnerability scope：all charts
![image](https://user-images.githubusercontent.com/18527271/167320336-7b323a25-6bfb-45ab-adac-a4a7815bf9a0.png)

**Comment by qiweiii** [comment]
@Keith-CY

https://user-images.githubusercontent.com/32790369/169504848-a70c294c-9a85-4df0-a79d-09d8e9e16b7d.mov

Do you think this is fine? It won't display date when hovered, instead I show a compact chart on it, so user still knows it's like a range selector

**Comment by Keith-CY** [comment]
> @Keith-CY
> 
>  Screen.Recording.2022-05-20.at.17.58.46.mov 
> Do you think this is fine? It won't display date when hovered, instead I show a compact chart on it, so user still knows it's like a range selector

LGTM
