### ISSUE TITLE
[v0] the total number of pages in the bridged token list does not match the data returned by the backend.

### ISSUE THREAD

**Issue by BourneNeo** [Magickbase/godwoken_explorer#490]
![image](https://user-images.githubusercontent.com/18527271/167322190-9980c490-3ca7-4bc5-a4d2-a2eb77d4855e.png)
![image](https://user-images.githubusercontent.com/18527271/167322260-deea7979-8acc-4753-a40c-4b64e73a5a7a.png)
https://aggron.gwscan.com/tokens/bridge?type=bridge&page=2

**Comment by Keith-CY** [comment]
This error came with the update of default page size from 10 to 20 and page size was recalculated incorrectly.

It's fixed by https://github.com/Magickbase/godwoken-explorer-ui/pull/206
Please verify it on https://www.gwscan.com/zh-CN/tokens/bridge
