### ISSUE TITLE
Update for godwoken v1.1

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#491]
Godwoken changelog: https://github.com/nervosnetwork/godwoken/blob/448b7c28a49deb9f9a73683be95bd8cacbab2c57/CHANGELOG.md#110---2022-04-2x-release-candidate

**Comment by zmcNotafraid** [comment]
TODO:

- [ ] Support native ETH address in API and EVM, remove the Godwoken address concept
- [ ] EIP-712
- [ ] Ethereum address registry to store ethereum address

**Comment by zmcNotafraid** [comment]
https://github.com/nervosnetwork/godwoken-info/pull/26/files

**Comment by Keith-CY** [comment]
- [ ] erc20 proxy returns the correct total supply so we don't have to calculate it 
- [ ] decimals of CKB is set 18 instead of 8
