### ISSUE TITLE
Event/Logs api

### ISSUE THREAD

**Issue by zmcNotafraid** [Magickbase/godwoken_explorer#494]

**Comment by zmcNotafraid** [comment]
- [ ] event log for contract

**Comment by Keith-CY** [comment]
Ref: https://github.com/Magickbase/ckb-wallet-and-explorer/issues/9#issuecomment-1108058513

**Comment by zmcNotafraid** [comment]
@Keith-CY event log: eg: https://api.gwscan.com/api/accounts/0xb02c930c2825a960a50ba4ab005e8264498b64a0/logs

**Comment by Keith-CY** [comment]
## Logs in a specific transaction
Etherscan
![image](https://user-images.githubusercontent.com/7271329/169232040-125657ed-c3f8-4692-80ce-02f3ae99a041.png)
Let's add the same info in tab panel
![image](https://user-images.githubusercontent.com/7271329/169232110-c5793857-0ad2-4ed7-b2d5-b073a3ff7e59.png)

## Evnets in a specific contract
Etherscan
![image](https://user-images.githubusercontent.com/7271329/169232476-1e436c9e-ad97-4d04-9bd6-10318c42c82a.png)

Let's add the same info in tab panel too
![image](https://user-images.githubusercontent.com/7271329/169232520-c52124c9-e959-4673-9b70-43ab992cf0eb.png)

**Comment by Keith-CY** [comment]
Any update @qiweiii

**Comment by Keith-CY** [comment]
> > Any update @qiweiii
> 
> not yet, I missed this one out..
> 
> So we need to add new tabs in tx and account page?

Yep, we can add a new tab for simplicity, it would be refactored once https://github.com/Magickbase/visual-style-guide/issues/1 is done

**Comment by qiweiii** [comment]
@Keith-CY I saw new design has events/logs page, shall I try to follow new designs?

**Comment by Keith-CY** [comment]
> @Keith-CY I saw new design has events/logs page, shall I try to follow new designs?

Yes, we can follow the new design of content block
![image](https://user-images.githubusercontent.com/7271329/170819167-e5300718-12d6-45de-97a8-3f2618548305.png)

![image](https://user-images.githubusercontent.com/7271329/170819179-cee5415a-f13c-4d89-92c7-f1ebc8102717.png)

And do the rest later

**Comment by qiweiii** [comment]
@Keith-CY 

![Image](https://user-images.githubusercontent.com/32790369/172048748-440b6b6a-bb94-4dd2-8084-f405317afa94.png)

Do we need a link to block, if so we need block hash data from api.

And I am not sure how to get `method` and `methodID` of a corresponding event, should we add it in API or use ether v5?

**Comment by Keith-CY** [comment]
> Do we need a link to block, if so we need block hash data from API.

Block number returned from API can be used to link to block page as https://www.gwscan.com/block/0


> And I am not sure how to get `method` and `methodID` of a corresponding event, should we add it in API or use ether v5?

Ethers.js used in this project + abi returned from API can be used to decode logs
```javascript
const interface = new ethers.utils.Interface(abi)
const parsed = interface.parseLog({ data, topics })
```

**Comment by qiweiii** [comment]
> Ethers.js used in this project + abi returned from API can be used to decode logs

I am already using it to decode logs, but in contract events page, there is a column called methods, parseLog does not provide methods related to a log.

**Comment by Keith-CY** [comment]
> > Ethers.js used in this project + abi returned from API can be used to decode logs
> 
> I am already using it to decode logs, but in contract events page, there is a column called methods, parseLog does not provide methods related to a log.
> 
> I saw there is a [parseTransaction](https://docs.ethers.io/v5/api/utils/abi/interface/#TransactionDescription:~:text=interface.parseTransaction(%20transaction%20)), maybe I can use this to get the method

Seems correct, `event` is not coupled with `method`(event message is in pub-sub mode so original method cannot be found in message)

But tx info is not returned in the API yet, maybe we need @zmcNotafraid to update the API to return method id corresponding to this log, or we can ignore it temporarily.

**Comment by Keith-CY** [comment]
Front-end PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/212

**Comment by Keith-CY** [comment]
Contract is expected to have events but not: https://api.v1-betanet.gwscan.com/api/accounts/0x2503a1a79a443f3961ee96a8c5ec513638129614/logs

ERC 20 logs can be found in https://api.v1-betanet.gwscan.com/api/txs/0x46475e0571703bf80f900d3aae6ff1c56e9afa4b4a34a0d1cb20952c17e964bd/logs

@zmcNotafraid

**Comment by zmcNotafraid** [comment]
> Contract is expected to have events but not: https://api.v1-betanet.gwscan.com/api/accounts/0x2503a1a79a443f3961ee96a8c5ec513638129614/logs
> 
> ERC 20 logs can be found in https://api.v1-betanet.gwscan.com/api/txs/0x46475e0571703bf80f900d3aae6ff1c56e9afa4b4a34a0d1cb20952c17e964bd/logs
> 
> @zmcNotafraid

Fix at https://github.com/Magickbase/godwoken_explorer/pull/617 .Use wrong tx hash to join with logs.

**Comment by Keith-CY** [comment]
Tx Page Preview: https://v1.betanet.gwscan.com/zh-CN/tx/0x46475e0571703bf80f900d3aae6ff1c56e9afa4b4a34a0d1cb20952c17e964bd?tab=logs
Contract Page Preview: https://v1.betanet.gwscan.com/zh-CN/account/0x2503a1a79a443f3961ee96a8c5ec513638129614?tab=events

**Comment by Keith-CY** [comment]
How are logs ordered in the response @zmcNotafraid

**Comment by zmcNotafraid** [comment]
> How are logs ordered in the response @zmcNotafraid

First order by block_number desc, then order by log index desc
