### ISSUE TITLE
[v1.1] Graphql add address Mixed-case checksum address encoding middleware

### ISSUE THREAD

**Issue by Naupio** [Magickbase/godwoken_explorer#499]

**Comment by Naupio** [comment]
link #537

**Comment by Naupio** [comment]
https://eips.ethereum.org/EIPS/eip-55
address with eip-55 checksum
cc @qiweiii

**Comment by Keith-CY** [comment]
![Image](https://user-images.githubusercontent.com/7271329/170224122-d4020773-83bd-4a7a-9553-96e4bce8ac42.png)
Checksum of an address will be checked

**Comment by Keith-CY** [comment]
@xiefei1024 please have a review

**Comment by xiefei1024** [comment]
Verified  this bug ,please close this issue
