### ISSUE TITLE
[v1.1] Yokai Token is missing is `account_udts` returned from graphql

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#501]
Address: 0x387a3cb79141324c25ec4ea3c9b267b550c7fbdc

![image](https://user-images.githubusercontent.com/7271329/167768251-b033204c-0d12-4d69-ab46-9e0614226822.png)

![image](https://user-images.githubusercontent.com/7271329/167768279-51d3edb7-577c-4011-884a-4ce2b1376df7.png)

**Comment by Naupio** [comment]
fix txs count and transfer count  for query account
link #522

**Comment by Keith-CY** [comment]
I started a new issue about the multiple udts in response
https://github.com/Magickbase/godwoken_explorer/issues/542
