### ISSUE TITLE
Public JSON API

### ISSUE THREAD

**Issue by zmcNotafraid** [Magickbase/godwoken_explorer#521]
like: 
https://blockscout.com/etc/mainnet/api-docs
https://docs.etherscan.io/

**Comment by zmcNotafraid** [comment]
### API Process
## Accounts
- [x] balance
- [ ] balancemulti
- [ ] txlist
- [ ] txlistinternal
- [ ] tokentx
- [ ] tokennfttx
- [ ] getminedblocks
## Contracts
- [ ] getabi
- [ ] getsourcecode
- [ ] Verify
## Transactions
- [ ] getstatus
- [ ] gettxreceiptstatus
## Blocks
- [ ] getblockreward
- [ ] getblockcountdown
- [ ] getblocknobytime
## Logs
- [ ] getLogs
## Tokens
- [ ] tokensupply
- [ ] tokenbalance
## GasTracker
- [ ] gasestimate
- [ ] gasoracle

**Comment by Keith-CY** [comment]
Are these APIs deployed? 
`https://api.v1-betanet.gwscan.com/api?module=account&action=txlist` or `https://api.v1-betanet.gwscan.com/api?module=accounts&action=txlist` return nothing
