### ISSUE TITLE
[v1.1] bridged transfer ' ckb  decimal is 8 not 18

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#529]
https://v1.betanet.gwscan.com/account/0xb9dda6ab27789ec40976e9da395e754c961d8a99?tab=bridged
<img width="807" alt="image" src="https://user-images.githubusercontent.com/32102187/169064069-4a1570a0-9489-48c0-a2f8-75c5649cff40.png">

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/32102187/169064113-e7a686aa-5ed6-47af-b568-e32c5762a2e7.png">

**Comment by Keith-CY** [comment]
`ckb` decimal changes from `8` to `18`
Ref: 
https://github.com/nervosnetwork/godwoken/blob/448b7c28a49deb9f9a73683be95bd8cacbab2c57/CHANGELOG.md#110---2022-04-2x-release-candidate
https://github.com/Magickbase/godwoken_explorer/issues/491

**Comment by gpBlockchain** [comment]
> `ckb` decimal changes from `8` to `18` Ref: https://github.com/nervosnetwork/godwoken/blob/448b7c28a49deb9f9a73683be95bd8cacbab2c57/CHANGELOG.md#110---2022-04-2x-release-candidate #491

deposit / withdraw is 8；

layer2 transaction 是is18；

**Comment by Keith-CY** [comment]
As the https://github.com/nervosnetwork/godwoken/pull/675 says
```
This PR also changes the decimal of CKB, in layer1 CKB is represented in 8 decimal, but when user deposit CKB into layer2, we changed the representation to 18 decimal. 
```

Namely 1**10 CKB transferred to Layer2 would be represented as 1 CKB

**Comment by Keith-CY** [comment]
> > `ckb` decimal changes from `8` to `18` Ref: [nervosnetwork/godwoken@`448b7c2`/CHANGELOG.md#110---2022-04-2x-release-candidate](https://github.com/nervosnetwork/godwoken/blob/448b7c28a49deb9f9a73683be95bd8cacbab2c57/CHANGELOG.md#110---2022-04-2x-release-candidate) #491
> 
> deposit / withdraw is 8；
> 
> layer2 transaction is18； godwoken is compatible with Ethereum, as long as it is compatible at the layer2 transaction level, and deposit/withdraw does not need to be compatible with Ethereum, so it still uses the 8 decimal convention of layer1 CKB

Confirmed this is correct and I'll fix this today

**Comment by Keith-CY** [comment]
PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/189
