### ISSUE TITLE
Verify contract automatically

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#533]
Contract source code should be verified on registration, which is missing part of gwscan workflow.

Blockscout has internal integration: https://docs.blockscout.com/for-users/verifying-a-smart-contract#:~:text=1)%20On%20contract%20creation%2C%20you,contract%20details%20should%20come%20up.

3rd party service: https://sourcify.dev/

**Comment by Keith-CY** [comment]
We should enable this feature on both of GwScan and Axon Explorer.

Since it's delivered in blockscout, we may just learn from it how to verify a contract on registration.

**Comment by Keith-CY** [comment]
Corresponding code in blockscout https://github.com/blockscout/blockscout/blob/2eb03c81af/apps/explorer/lib/explorer/third_party_integrations/sourcify.ex#L26-L49

**Comment by Naupio** [comment]
link here: https://github.com/Magickbase/axon_explorer/tree/main/apps/explorer/lib/explorer/smart_contract

**Comment by Naupio** [comment]
solidity compiler: https://github.com/Magickbase/axon_explorer/blob/main/apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex
solidity verifier: https://github.com/Magickbase/axon_explorer/blob/main/apps/explorer/lib/explorer/smart_contract/solidity/verifier.ex

**Comment by Keith-CY** [comment]
Seems that godwoken explorer could add `Explorer.SmartContract.Solidity.CodeCompiler` so we can do compilation with code instead of remix @zmcNotafraid

And bytecode could be compared with deployed data at the same time.

**Comment by Keith-CY** [comment]
Sourcify doesn't include godwoken yet
Ref: https://github.com/ethereum/sourcify/pull/735

**Comment by Keith-CY** [comment]
Godwoken mainnet has been added in sourcify https://playground.sourcify.dev/ chain id #71402
