### ISSUE TITLE
[v1.1] View all blocks -> Error 

### ISSUE THREAD

**Issue by Flouse** [Magickbase/godwoken_explorer#534]
1. Click `View all blocks` Button
2. Error page showed as follow:

![image](https://user-images.githubusercontent.com/1297478/169930788-ad6bd4cd-4642-4f65-be19-e3b0cad35b13.png)
https://v1.betanet.gwscan.com/error?message=invalid%20json%20response%20body%20at%20https://api.v1-betanet.gwscan.com/api/blocks?page=1&page_size=30%20reason:%20Unexpected%20end%20of%20JSON%20input

**Comment by zmcNotafraid** [comment]
Fixed.

**Comment by Keith-CY** [comment]
> Fixed.

Better to add details of this error here so we can make it clear and avoid it again.
