### ISSUE TITLE
[Bridged Token] register USDC for v1.betanet.gwscan.com

### ISSUE THREAD

**Issue by Flouse** [Magickbase/godwoken_explorer#536]
### Token Name

USD Coin

### Description

Test USD Coin on Godwoken v1

### Symbol

USDC

### Decimals

18

### Logo URI

https://cryptologos.cc/logos/usd-coin-usdc-logo.svg?v=002

### SUDT Script Arguments

issuerLockHash: "0x58bef38794236b315b7c23fd8132d7f42676228d659b291936e8c6c7ba9f064e"

### Contract Address

0x088338e5Df007e2d7B38fd6A1eBc1EB766c6E360

### Other Info

```js
l1Lock: {
      code_hash: "0xc5e5dcf215925f7ef4dfaf5f4b4f105bc321c02776d6e7d52a1db3fcd9d011a4",
      hash_type: "type",
      args: "0x58bef38794236b315b7c23fd8132d7f42676228d659b291936e8c6c7ba9f064e"
}
```

**Comment by zmcNotafraid** [comment]
Created At:https://v1.betanet.gwscan.com/zh-CN/token/80
