### ISSUE TITLE
Fetch godwoken version by RPC

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#539]
```
echo '{
    "id": 2,
    "jsonrpc": "2.0",
    "method": "poly_version",
    "params": []
}' | tr -d '\n' \
| curl -H 'content-type: application/json' -d @- \
https://godwoken-testnet-v1.ckbapp.dev/
```
Ref: https://github.com/nervosnetwork/godwoken-web3/pull/239#issuecomment-1136699089

**Comment by Keith-CY** [comment]
We'd better cache this info on launch of gwscan api service @zmcNotafraid

**Comment by zmcNotafraid** [comment]
"versions": {
      "web3Version": "1.0.0-rc1",
      "web3IndexerVersion": "1.0.0-rc1",
      "godwokenVersion": "1.1.3 5ee735b"
    }
  which version is needed? @Keith-CY

**Comment by Keith-CY** [comment]
> "versions": { "web3Version": "1.0.0-rc1", "web3IndexerVersion": "1.0.0-rc1", "godwokenVersion": "1.1.3 5ee735b" } which version is needed? @Keith-CY

Could we cache them all in memory so front-end can decide which to be used freely

**Comment by zmcNotafraid** [comment]
visit https://api.v1-betanet.gwscan.com/api/poly_versions,
```
{
godwokenVersion: "1.2.2 697e8a0",
web3IndexerVersion: "1.1.2-rc1",
web3Version: "1.1.2-rc1"
}
```

**Comment by Keith-CY** [comment]
Front-end: https://github.com/Magickbase/godwoken-explorer-ui/pull/236

**Comment by FrederLu** [comment]
Verified.
