### ISSUE TITLE
Support snapshot of udt accounts

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#547]
Snapshot udt accounts on specific block number

**Comment by zmcNotafraid** [comment]
Current deploy to server, need  to check for some day.

**Comment by yixyxiu** [comment]
Looks good，I'll get back to you after I confirm with YokaiSwap.

**Comment by zmcNotafraid** [comment]
Add an api to support pass params from frontend and return results

**Comment by Keith-CY** [comment]
Expose an API

**Comment by zmcNotafraid** [comment]
/api/snapshots.csv?start_block_number=1&end_block_number=10000&token_contract_address_hash=0xbb30e8691f6ffd5b4c0b2f73d17847e1e289ea80

**Comment by FrederLu** [comment]
Verified.
