### ISSUE TITLE
[V1.1] Send a contract transfer, and scan shows that the contract account is empty

### ISSUE THREAD

**Issue by Dawn-githap** [Magickbase/godwoken_explorer#549]
example [https://v1.betanet.gwscan.com/tx/0xd651b9e0053630bb4dc345e3f44f4ae532e85128d568a5841032f2b5968ede55?search=0xd651b9e0053630bb4dc345e3f44f4ae532e85128d568a5841032f2b5968ede55](https://v1.betanet.gwscan.com/tx/0xd651b9e0053630bb4dc345e3f44f4ae532e85128d568a5841032f2b5968ede55?search=0xd651b9e0053630bb4dc345e3f44f4ae532e85128d568a5841032f2b5968ede55)

**Comment by Keith-CY** [comment]
I can see a transfer record in this page

**Comment by Keith-CY** [comment]
I got your question

A `transfer` may not be a `transaction`, you could see the record here https://v1.betanet.gwscan.com/account/0x47022b135616afd394ad41977efb8bb8c425645f?tab=erc20

**Comment by Dawn-githap** [comment]
Deployed Contract
[0x]

**Comment by Keith-CY** [comment]
You mean `a contract has been deployed by this transaction, but the "deployed contract" has 0x address, which should be a valid address`?

**Comment by Dawn-githap** [comment]
Yes, should be a valid address and should not be displayed as null

**Comment by Keith-CY** [comment]
Got it

**Comment by zmcNotafraid** [comment]
RPC returns value has changed. We are confirming with godwoken team. https://github.com/nervosnetwork/godwoken-web3/issues/360

**Comment by Keith-CY** [comment]
Fixed by this PR https://github.com/Magickbase/godwoken-explorer-ui/pull/213

**Comment by Keith-CY** [comment]
Deployed to betanet, please have a look @Dawn-githap

**Comment by Dawn-githap** [comment]
> 已部署到 betanet，请查看@Dawn-githap

This issue has been modified and closed
