### ISSUE TITLE
[v1.1]You're visiting a polyjuice transaction with a gw_hash which is just for developers, please use an eth_hash() instead

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#552]
1. query tx return error
https://v1.betanet.gwscan.com/account/0xa86e2b58f987d298c6103fc72592a19451fb49a4?search=0xa86e2b58f987d298c6103fc72592a19451fb49a4
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/32102187/170680090-d034b8e2-c4ea-4e08-9a3b-f455c7ac1352.png">

https://v1.betanet.gwscan.com/tx/0x610365eb06add76bb17ce9e89302b335c784d72d87c6db1290c7352af9f64449
<img width="757" alt="image" src="https://user-images.githubusercontent.com/32102187/170679917-10fc322d-d89a-4440-b4a6-5a72d77603ce.png">

**Comment by Keith-CY** [comment]
Requset: https://api.v1-betanet.gwscan.com/api/txs/0x610365eb06add76bb17ce9e89302b335c784d72d87c6db1290c7352af9f64449

Response: 
```
{
  "errors": {
    "detail": "",
    "status": "303",
    "title": "Use eth_hash query"
  }
}
```

**Comment by zmcNotafraid** [comment]
This is caused by using wrong split method of elixir.Now it's fixed

**Comment by Keith-CY** [comment]
![image](https://user-images.githubusercontent.com/7271329/171335392-89c8c336-addf-43f5-8a45-cddab815d766.png)
Now the tx hash is correct `0x34696a1157c80bf38ecbc860fbe764b4cfbaf725a3ead1f940e8b369f0e28faf` @gpBlockchain
