### ISSUE TITLE
Mark withdrawal from v0 to v1

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#553]
Because godwoken v1 is incompatible with v0, assets on v0 should be migrated to v1 on upgrade.

The basic route is `withdraw asset from v0 to ckb` -> `deposit asset from ckb to v1` but it takes time for the challenge mechanism.

So godwoken team designed another route named `fast withdraw from v0 to v1` and built a webpage for that
https://testnet.bridge.godwoken.io/#/v0

The core signal is https://github.com/zhangyouxin/light-godwoken/blob/c9c40d893e5d71ae29ee321e6dd7f1aac9a64db9/src/light-godwoken/LightGodwokenV0.ts#L299-L303

And we can mark fast-withdraw transactions according to the signal in gwscan@v0 and gwscan@v1.

**Comment by Keith-CY** [comment]
I've withdrawed 650 ckb from v0 to v1 and get the tx hash `0x0963e11375d65d462844b324d1ca7a9795922307c25bd24abfa5dc9f10a82e8e`

the withdrawal is
```
amount: "0x0"
capacity: "0xf224d4a00"
date: "5/27/2022, 6:42:31 PM"
txHash: "0x0963e11375d65d462844b324d1ca7a9795922307c25bd24abfa5dc9f10a82e8e"
type: "withdrawal"
```
And I can verify the withdrawal from RPC
```
http post http://godwoken-testnet-web3-rpc.ckbapp.dev id=2 jsonrpc="2.0" method="gw_get_withdrawal" params:='["0x0963e11375d65d462844b324d1ca7a9795922307c25bd24abfa5dc9f10a82e8e"]'
```

But it cannot be found in gwscan, maybe it's not recognized yet.

**Comment by Keith-CY** [comment]
How about taking over this issue? @Naupio 
This feature covers data in both godwoken and ckb, a good point to start work with ckb.

**Comment by Keith-CY** [comment]
Withdrawal 1: https://discord.com/channels/956765352514183188/979234782477180938/979696160090517564
Withdrawal 2: https://discord.com/channels/956765352514183188/979234782477180938/979696825701392424

They are both not found in v0.

**Comment by Keith-CY** [comment]
Any update on v1? @Naupio

**Comment by zmcNotafraid** [comment]
> Any update on v1? @Naupio

I add a column as is_fast_withdrawal:boolean for deposit_withdrawal api

**Comment by Keith-CY** [comment]
Awesome

**Comment by Keith-CY** [comment]
> Any update on v1? @Naupio

This feature will only be activated in v0 since it's hard to detect fast-withdrawal in v1
