### ISSUE TITLE
smart contract write functionality

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#557]
1. connect to the wallet(metamask) on switching to the the `write contract` tab;
2. change network of the wallet to the specific godwoken network(mainnet and testnet) with info from https://github.com/nervosnetwork/godwoken-info, network info will be added if it doesn't exist;
3. calling methods in the `write contract` should invoke the wallet to sign a transaction;
4. hash of the signed transaction will be displayed in the form, with an `open-in-new` button next to it, but it takes time to bundle the transaction into a block so `open-in-new` will lead to 404 temporarily;
5. detect change of wallet and network, and prompt the user about the change.

---
As what etherscan does https://rinkeby.etherscan.io/address/0x5a1cc3f2C200b7205Ec084A0E219Ed7D20Bb3D6F#writeContract

**Comment by Keith-CY** [comment]
It's been deployed to production environments without review because this function is called by users yesterday. So please verify it in the testnet @FrederLu , any question about details could be appended in this issue.

https://v1.testnet.gwscan.com/account/0x2503a1a79a443f3961ee96a8c5ec513638129614?tab=contract

**Comment by FrederLu** [comment]
Verified.
