### ISSUE TITLE
TransactionType doesn't cover all

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#562]
schema: https://github.com/Magickbase/godwoken_explorer/blob/main/docs/schema.graphql#L1039-L1042
```
enum TransactionType {
  POLYJUICE
  POLYJUICE_CREATOR
}
```

model: https://github.com/Magickbase/godwoken_explorer/blob/godwoken-v1.1/lib/godwoken_explorer/transaction.ex#L21
```
field(:type, Ecto.Enum,
    values: [:polyjuice_creator, :polyjuice, :eth_address_registry, :unknown]
)
```

**Comment by Naupio** [comment]
we can use godwoken-1.1 branch to check the graphql type, we now only fix in `godwoken-1.1` branch

https://github.com/Magickbase/godwoken_explorer/blob/661ea95e3d5d8c23302b195ad9f7c6d2902b18b2/docs/schema.graphql#L1078
