### ISSUE TITLE
[V1.1]View the latest block, prompting that the BigNumber value is invalid

### ISSUE THREAD

**Issue by Dawn-githap** [Magickbase/godwoken_explorer#566]
[https://v1.betanet.gwscan.com/zh-CN/block/0x272a94682cbf1a61cf65f86d137d5402da2358a5942513de7db144277b35f361](https://v1.betanet.gwscan.com/zh-CN/block/0x272a94682cbf1a61cf65f86d137d5402da2358a5942513de7db144277b35f361)

**Comment by Keith-CY** [comment]
```
{
  "finalize_state": "committed",
  "gas_limit": null,
  "gas_used": null,
  "hash": "0x272a94682cbf1a61cf65f86d137d5402da2358a5942513de7db144277b35f361",
  "l1_block": 5532123,
  "l1_tx_hash": "0xbb6b8b49088b6521b9b09862df6534e9f4eb2ea1c9b3154505346eb56237e51b",
  "logs_bloom": null,
  "miner_hash": "715ab282b873b79a7be8b0e8c13c4e8966a52040",
  "number": 61651,
  "parent_hash": "0x4ec4458eac920ef92afdb7e85fe8c732ae8da90e710318f85a3eb9d427653e08",
  "size": null,
  "timestamp": 1653896527,
  "tx_count": 0
}
```

Returned some invalid number(gas limit, gas used, size)

**Comment by zmcNotafraid** [comment]
Fetch rpc may return nil because of network problem, so let it retry until it get correct value.Data has fixed.

**Comment by Dawn-githap** [comment]
Now it has been recovered, and the value can be obtained
