### ISSUE TITLE
[v1.1] deploying contract result prompt returned by metamask led to v1 instead of v1.1

### ISSUE THREAD

**Issue by BourneNeo** [Magickbase/godwoken_explorer#571]
![image](https://user-images.githubusercontent.com/18527271/171544308-0d66c260-9137-4871-8a32-9dcba132ca6a.png)
![image](https://user-images.githubusercontent.com/18527271/171543501-697bca83-427e-40d4-8a20-06519985ae46.png)
![image](https://user-images.githubusercontent.com/18527271/171543640-5b7830c3-dd7d-468d-b5d4-ba75c32408bc.png)
wrong:
![image](https://user-images.githubusercontent.com/18527271/171544148-ba7a9ce1-a76f-42ae-8ad8-15f3b000a1b5.png)
correct:
![image](https://user-images.githubusercontent.com/18527271/171545242-9737dbb9-9562-4771-a54e-871d6dbf6a74.png)

**Comment by Keith-CY** [comment]
The explorer URL was registered by the website, so the data of website is incorrect, may I ask which page you've visited that add godwoken v1.1 into metamask?

**Comment by BourneNeo** [comment]
> The explorer URL was registered by the website, so the data of website is incorrect, may I ask which page you've visited that added godwoken v1.1 into metamask?

you mean my info source about the v1.1 rpc?

**Comment by Keith-CY** [comment]
> > The explorer URL was registered by the website, so the data of website is incorrect, may I ask which page you've visited that added godwoken v1.1 into metamask?
> 
> you mean my info source about the v1.1 rpc?

Yes, when your metamask doesn't have godwoken v1.1 info, and you visit a dapp connected to godwoken v1.1, the basic information(rpc URL, explorer URL) will be registered by the dapp.

In this case, the dapp has incorrect info.

**Comment by BourneNeo** [comment]
> 
https://discord.com/channels/956765352514183188/958261584004804650/976376004664778783

**Comment by BourneNeo** [comment]
> > > The explorer URL was registered by the website, so the data of website is incorrect, may I ask which page you've visited that added godwoken v1.1 into metamask?
> > 
> > 
> > you mean my info source about the v1.1 rpc?
> 
> Yes, when your metamask doesn't have godwoken v1.1 info, and you visit a dapp connected to godwoken v1.1, the basic information(rpc URL, explorer URL) will be registered by the dapp.
> 
> In this case, the dapp has incorrect info.

https://discord.com/channels/956765352514183188/958261584004804650/976376004664778783

**Comment by Keith-CY** [comment]
> > > > The explorer URL was registered by the website, so the data of website is incorrect, may I ask which page you've visited that added godwoken v1.1 into metamask?
> > > 
> > > 
> > > you mean my info source about the v1.1 rpc?
> > 
> > 
> > Yes, when your metamask doesn't have godwoken v1.1 info, and you visit a dapp connected to godwoken v1.1, the basic information(rpc URL, explorer URL) will be registered by the dapp.
> > In this case, the dapp has incorrect info.
> 
> [discord.com/channels/956765352514183188/958261584004804650/976376004664778783](https://discord.com/channels/956765352514183188/958261584004804650/976376004664778783)

This thread only mentions two RPC URLs, but not the explorer URL. RPC URLs works for handling requests to Godwoken Node while explorer URL provides a user interface to view godwoken data.

If the explorer url is registered manually in metamask, you may have to fix it with the correct one `https://v1.betanet.gwscan.com/`

**Comment by BourneNeo** [comment]
> > > > > The explorer URL was registered by the website, so the data of website is incorrect, may I ask which page you've visited that added godwoken v1.1 into metamask?
> > > > 
> > > > 
> > > > you mean my info source about the v1.1 rpc?
> > > 
> > > 
> > > Yes, when your metamask doesn't have godwoken v1.1 info, and you visit a dapp connected to godwoken v1.1, the basic information(rpc URL, explorer URL) will be registered by the dapp.
> > > In this case, the dapp has incorrect info.
> > 
> > 
> > [discord.com/channels/956765352514183188/958261584004804650/976376004664778783](https://discord.com/channels/956765352514183188/958261584004804650/976376004664778783)
> 
> This thread only mentions two RPC URLs, but not the explorer URL. RPC URLs works for handling requests to Godwoken Node while explorer URL provides a user interface to view godwoken data.
> 
> If the explorer url is registered manually in metamask, you may have to fix it with the correct one `https://v1.betanet.gwscan.com/`

ok, my misunderstanding. sry. i'll close this issue.
