### ISSUE TITLE
[V1.1]Gwscan transaction info has 4 decimal places more than mastmask gas price

### ISSUE THREAD

**Issue by Dawn-githap** [Magickbase/godwoken_explorer#572]
[Gas Price](https://v1.testnet.gwscan.com/tx/0xae6224990c0341712e06850eca28c290a8547ef2b37658568dc2d379fc84b7c1?search=0xae6224990c0341712e06850eca28c290a8547ef2b37658568dc2d379fc84b7c1)
![image](https://user-images.githubusercontent.com/77844990/171547687-dfce6e9b-b8f1-4710-b4af-9d771adb4554.png)

**Comment by zmcNotafraid** [comment]
original gas price is 250000000

**Comment by Keith-CY** [comment]
The price in metamask is in gwei, 0.25gwei is 0.25/(10^9), namely 0.00000000025 @Dawn-githap
