### ISSUE TITLE
Inconsistent data returned from godwoken node

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#581]
```sh
$ curl <<our node>>  -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "method": "eth_getBlockByNumber", "params": ["0x3f18c", false], "id": 1}'
$ curl https://mainnet.godwoken.io/rpc  -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "method": "eth_getBlockByNumber", "params": ["0x3f18c", false], "id": 1}'
```

The first request returns null while the second one returns block info.

And [node service](https://github.com/Magickbase/ckb-wallet-and-explorer/issues/24#issuecomment-1057581160) didn't alarm in this case.

**Comment by Keith-CY** [comment]
Logs: https://gist.github.com/ShiningRay/2b7f3d2031593293972c65ffb1f88e1e

**Comment by ShiningRay** [comment]
线上 godwoken 节点，tip block number 正常，后续的块信息也正常，数据库中唯独缺少 258444 的块信息

**Comment by Keith-CY** [comment]
这个问题已经修复了, 不过解决方面没有记录, 麻烦 @ShiningRay 补充一下

**Comment by ShiningRay** [comment]
向Godwoken团队反馈该情况之后，根据 Godwoken 团队的建议，讲godwoken 节点升级为一个 hotfix 版本
并停用 godwoken 进程内部的 indexer ，重新启动了一个独立的 web3 indexer ，清空了数据库重新进行同步
相关配置如下：

https://gist.github.com/ShiningRay/2b7f3d2031593293972c65ffb1f88e1e
