### ISSUE TITLE
Improve testing

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#589]
1. add more unit tests
2. add test coverage report
3. daily tests with real data from testnet

**Comment by zmcNotafraid** [comment]
- [ ] test coverage for CI
- [ ] public RPC
- [ ] API for front end

**Comment by Keith-CY** [comment]
@Naupio please add a todo list in this issue

**Comment by Naupio** [comment]
account udt mocking testing:
- [ ] account_current_udts
- [ ] account_current_bridged_udts
- [ ] account_ckbs
- [ ] account_udts
- [ ] account_udts_by_contract_address
- [ ] account_bridged_udts_by_script_hash

**Comment by Naupio** [comment]
account mock testing:
- [ ] account
- [ ] account with sub field reolver

**Comment by Naupio** [comment]
block object mock testing:
- [ ] block
- [ ] blocks
- [ ] block object  with sub field resolver

**Comment by Naupio** [comment]
log object mock testing:
- [ ] logs

**Comment by Naupio** [comment]
smart contract object mock testing:
- [ ] smart_contract
- [ ] smart_contracts
- [ ] smart_contract object with sub fields resolver

**Comment by Naupio** [comment]
token_transfer object mock testing:
- [ ] token_transfers
- [ ] token_transfer object with sub fields resolver

**Comment by Naupio** [comment]
transaction object  mock testing:
- [ ] transaction
- [ ] transactions
- [ ] transaction object with sub fields resolver

**Comment by Keith-CY** [comment]
for 2 weeks
