### ISSUE TITLE
Update UI

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#593]
Design: https://github.com/Magickbase/visual-style-guide/issues/1
---
Please list sub-tasks and add ETA. in this issue @qiweiii

**Comment by qiweiii** [comment]
Follow design: https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=0%3A1

Create small PRs, ensure each PR has mobile responsiveness and tests, then merge to `update-ui` branch:

- [ ]  Update custom mui theme to use new colors
- [ ]  Home Page: https://www.gwscan.com/
- [ ]  Block List: https://www.gwscan.com/blocks
- [ ]  Transaction List: https://www.gwscan.com/txs
- [ ]  Block Detail: https://www.gwscan.com/block/0x69a1838b1030a505823fb3a6f623a5839d16b9ab52c37cff4c1835222123035d
- [ ]  Transaction Detail: https://www.gwscan.com/tx/0x8a06ffecf0a3662aa0af9cdbb29e3529f0509f887067e6bdece560fcb74f9960
- [ ]  User Account Detail: https://www.gwscan.com/account/0x98d6fc98b3c26b9dd3b7e4bac3e11ceb3e7171da
- [ ]  Contract Account Detail: https://www.gwscan.com/account/0x297ce8d1532704f7be447bc897ab63563d60f223
- [ ]  Token List: https://www.gwscan.com/tokens/bridge
- [ ]  Token Detail: https://www.gwscan.com/token/249
- [ ]  Registered Contract List: https://www.gwscan.com/contracts
- [ ]  Registered Contract Detail: https://www.gwscan.com/account/0xd66eb642ee33837531fda61eb7ab15b15658bcab
- [ ]  Charts https://www.gwscan.com/charts
