### ISSUE TITLE
[v1.1]ckb Balance's decimals is wrong 

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#599]
https://v1.betanet.gwscan.com/account/0xa86e2b58f987d298c6103fc72592a19451fb49a4?search=0xa86e2b58f987d298c6103fc72592a19451fb49a4
<img width="966" alt="image" src="https://user-images.githubusercontent.com/32102187/173040419-297ba643-9f3e-4d0b-8087-12fb49220b78.png">
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/32102187/173040728-39003edb-35fd-4e40-8a5a-7a7ef890e9a4.png">

### expected
ckb balance is 699.774405865377315572 not 6997744058653.77315572
tx value is 0.000000000001193040 not 0.0119304

**Comment by Keith-CY** [comment]
> [v1.betanet.gwscan.com/account/0xa86e2b58f987d298c6103fc72592a19451fb49a4?search=0xa86e2b58f987d298c6103fc72592a19451fb49a4](https://v1.betanet.gwscan.com/account/0xa86e2b58f987d298c6103fc72592a19451fb49a4?search=0xa86e2b58f987d298c6103fc72592a19451fb49a4) <img alt="image" width="966" src="https://user-images.githubusercontent.com/32102187/173040419-297ba643-9f3e-4d0b-8087-12fb49220b78.png"> <img alt="image" width="1188" src="https://user-images.githubusercontent.com/32102187/173040728-39003edb-35fd-4e40-8a5a-7a7ef890e9a4.png">
> 
> ### expected
> ckb balance is 699.774405865377315572 not 6997744058653.77315572 tx value is 0.000000000001193040 not 0.0119304

The original value of tx `0x0757e1ddf090a1864fb371fd907c6dd47308378c544d42d8a01349a4ae22b5b8` is `1193040` and the decimal of CKB is 8, so the amount is `0.0119304`

**Comment by Keith-CY** [comment]
Account balance and ckb amount of a transaction have been fixed
![Uploading image.png…]()
