### ISSUE TITLE
aggregator misses `0x` prefix

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#601]
![image](https://user-images.githubusercontent.com/7271329/173105766-c1e9ada6-43da-4ab6-b0a6-a59b31809b5e.png)

**Comment by zmcNotafraid** [comment]
@Keith-CY  fixed

**Comment by Keith-CY** [comment]
Verified
![image](https://user-images.githubusercontent.com/7271329/173272801-13581fe6-1a03-4107-ba16-b1d7957eb072.png)
