### ISSUE TITLE
graphql supports querying account by script hash

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#602]
e.g. 0x08c9937e412e135928fd6dec7255965ddd7df4d5a163564b60895100bb3b2f9e on v1.1

**Comment by Naupio** [comment]
add here #610

**Comment by Naupio** [comment]
example:
```graphql
    query {
      account(input: {script_hash: "0x08c9937e412e135928fd6dec7255965ddd7df4d5a163564b60895100bb3b2f9e"}){
        type
        eth_address
        script_hash
      }
    }
```

result:
```
{
  "data": {
    "account": {
      "eth_address": null,
      "script_hash": "0x08c9937e412e135928fd6dec7255965ddd7df4d5a163564b60895100bb3b2f9e",
      "type": "ETH_ADDR_REG"
    }
  }
}
```

**Comment by Keith-CY** [comment]
Other query related to account, like `account_ckbs`, `token_transfers`, `transactions` should be updated too.

**Comment by Keith-CY** [comment]
`account_ckbs`, `account_udts`, `transactions` accept `script_hash` while `token_transfers` doesn't since it only happens between eth accounts.
