### ISSUE TITLE
[v1.1] address not found

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#603]
https://v1.betanet.gwscan.com/account/0xc4a4281378fe711d2e02480cb7568952eb249fdf?search=0xc4a4281378fe711d2e02480cb7568952eb249fdf
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/32102187/173195445-b859c1f9-a7e8-4949-9246-2ae7b6b79b4e.png">

**Comment by Keith-CY** [comment]
This page is available now. But the error displayed in the screenshot should be checked, an empty list of transactions should be returned when the query parameter is a valid eth address  @Naupio

**Comment by gpBlockchain** [comment]
This problem can still occur when querying for non-existent accounts @Naupio
https://v1.betanet.gwscan.com/account/0xa768cb32724ee05cd9a4d6fd5818e77c269a45ed?search=0xa768cb32724ee05cd9a4d6fd5818e77c269a45ed

**Comment by gpBlockchain** [comment]
found error when query [META CONTRACT](https://v1.betanet.gwscan.com/account/0x946d08cc356c4fe13bc49929f1f709611fe0a2aaa336efb579dad4ca197d1551) informathon 
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/32102187/173211084-71e42f79-4ee6-4d5c-8681-70acca5dd753.png">

**Comment by Naupio** [comment]
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/12268276/173277864-54ca11fd-5e04-4fff-a367-f952e931fa51.png">

**Comment by gpBlockchain** [comment]
> META CONTRACT

https://v1.betanet.gwscan.com/account/0x946d08cc356c4fe13bc49929f1f709611fe0a2aaa336efb579dad4ca197d1551

**Comment by Naupio** [comment]
related issue: https://github.com/Magickbase/godwoken_explorer/issues/602
