### ISSUE TITLE
Support unverified token

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#604]
1. list all verified ABIs
2. try verified ABIs when a new token is detected
3. Once an ABI matches, the new token is registered with the matching ABI and marked as an unverified token

**Comment by Keith-CY** [comment]
Any update?

**Comment by zmcNotafraid** [comment]
> Any update?

Will handle it next sprint.

**Comment by Keith-CY** [comment]
I post the `UAN` related details in https://github.com/Magickbase/godwoken_explorer/issues/696#issuecomment-1174543136

**Comment by Keith-CY** [comment]
And how is this feature going

**Comment by Keith-CY** [comment]
Please add the corresponding PR in this issue
