### ISSUE TITLE
[v1.1] count of holders is incorrect

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#615]
![image](https://user-images.githubusercontent.com/7271329/173483122-9442d6f8-480e-4d36-916f-919c724d5b94.png)
![image](https://user-images.githubusercontent.com/7271329/173483181-9c85b058-dc3e-4e42-905c-b43d5cb00781.png)

**Comment by zmcNotafraid** [comment]
I query 0x067e469c13a7294d1aafa2130272a9c7b70a4464 address's balance is 0.
0xaab2020cd4d5ed9a5d3c43d3549f26eddae26994 not exist .
So the holder is 0

**Comment by Keith-CY** [comment]
> I query 0x067e469c13a7294d1aafa2130272a9c7b70a4464 address's balance is 0. 0xaab2020cd4d5ed9a5d3c43d3549f26eddae26994 not exist . So the holder is 0

Can we create the account when it is referred to in any case

**Comment by zmcNotafraid** [comment]
Need to split account table. Bind with https://github.com/Magickbase/godwoken_explorer/issues/618
