### ISSUE TITLE
Incorrect udt percentage

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#621]
https://v1.betanet.gwscan.com/zh-CN/token/80?tab=holders

![image](https://user-images.githubusercontent.com/7271329/173899028-65eb8c6e-b04d-4455-9b12-103e47f837ca.png)

**Comment by zmcNotafraid** [comment]
usdc contract may have some problem?

**Comment by Keith-CY** [comment]
> usdc contract may have some problem?

I'm not sure where the error is, if the `total supply` is incorrect and calculated by transfers, it should be fixed with `recognizing unverified contracts` by reading `total supply` from the contract.

**Comment by zmcNotafraid** [comment]
godwoken team will depoly a new contract, current is not verified
