### ISSUE TITLE
Logs are missing in tx

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#622]
![image](https://user-images.githubusercontent.com/7271329/173902963-64a0af42-7988-4972-8aae-a591296a7feb.png)
![image](https://user-images.githubusercontent.com/7271329/173903016-bd93e528-4690-4756-a6da-25235056f9ac.png)

Page https://v1.betanet.gwscan.com/tx/0x60216a524b36390f878efc52fbf87bcdc1f66b5ac6f51b19ea3a593e3cff4fd1?tab=logs

**Comment by Keith-CY** [comment]
Raw logs should be displayed when `abi` is missing

**Comment by Keith-CY** [comment]
Also missing in contract page https://v1.betanet.gwscan.com/account/0x1ac2b66eb3572b89ed20077d5b127a25dfc8f2f1?tab=events

**Comment by Keith-CY** [comment]
It's been fixed roughly by https://github.com/Magickbase/godwoken-explorer-ui/commit/44a1e982b3268b794942d307ee50f6fb8e88ff6c, please refine details

**Comment by Keith-CY** [comment]
Tutorial https://medium.com/linum-labs/everything-you-ever-wanted-to-know-about-events-and-logs-on-ethereum-fec84ea7d0a5

**Comment by qiweiii** [comment]
@Keith-CY what exactly we need to refine? Seems https://v1.betanet.gwscan.com/tx/0x60216a524b36390f878efc52fbf87bcdc1f66b5ac6f51b19ea3a593e3cff4fd1?tab=logs already show raw logs:



![Image](https://user-images.githubusercontent.com/32790369/174064902-9e9aee53-dd52-46c3-b3f6-e55c2922183f.png)

Do you mean we need to add hex/number/address format convertor?

**Comment by Keith-CY** [comment]
> @Keith-CY what exactly we need to refine? Seems [v1.betanet.gwscan.com/tx/0x60216a524b36390f878efc52fbf87bcdc1f66b5ac6f51b19ea3a593e3cff4fd1?tab=logs](https://v1.betanet.gwscan.com/tx/0x60216a524b36390f878efc52fbf87bcdc1f66b5ac6f51b19ea3a593e3cff4fd1?tab=logs) already show raw logs:
> 
> ![Image](https://user-images.githubusercontent.com/32790369/174064902-9e9aee53-dd52-46c3-b3f6-e55c2922183f.png)
> 
> Do you mean we need to add hex/number/address format convertor?

For example, it's hard coded https://github.com/Magickbase/godwoken-explorer-ui/pull/212/files#diff-fac5379b5e1a56d9919b9c60252da7a4c18750ad96b59d9f669c73648ea03edbR189-R194 to bind `eventInputs[2]` with `item.data`, actually it should be handled by the signature of event. In this case, the signature is `Transfer(indexed address, indexed address,uint256)`, the third parameter happens to be type of data, if the event has a signature `Transfer(indexed address, indexed address, indexed bool)`, then the third parameter is a `topic`.

Besides, `data` should be split into an array of 32bytes due to the rule of evm.

**Comment by Keith-CY** [comment]
> Besides, data should be split into an array of 32bytes due to the rule of evm.

An example of real data
![image](https://user-images.githubusercontent.com/7271329/174087008-40c215e6-e51f-4586-a8d9-927c78fa1c97.png)

Tx hash `0xffbd9b58bf95614775b112e2dbeb28d69081cecf3985d0cf1f8ec0b0ee0a9221` in ropsten

**Comment by Keith-CY** [comment]
I'll add detailed PRD and papers for future features so we can learn well to finish the work.
