### ISSUE TITLE
(graphql)Feat: add token list(udt list) filter and sorter

### ISSUE THREAD

**Issue by Naupio** [Magickbase/godwoken_explorer#625]

**Comment by Naupio** [comment]
- [ ] sorted by total supply/circulating supply
- [ ] sorted by holders
- [ ] sorted by name
- [ ] filtered by name (fuzzy)

**Comment by Naupio** [comment]
example:
```
    query {
      udts(
        input: {
          limit: 1
          fuzzy_name: "%ckb%"
          sorter: [{ sort_type: ASC, sort_value: ID }]
        }
      ) {
        entries {
          id
          name
          type
          supply
          account {
            eth_address
            script_hash
          }
        }
        metadata {
          total_count
          after
          before
        }
      }
    }

{
  "data": {
    "udts": {
      "entries": [
        {
          "account": {
            "eth_address": null,
            "script_hash": "0x595cc14e574a708dc70a320d2026f79374246ed4659261131cdda7dd5814b5ca"
          },
          "id": "1",
          "name": "pCKB",
          "supply": "12800091655514882421855103",
          "type": "BRIDGE"
        }
      ],
      "metadata": {
        "after": null,
        "before": null,
        "total_count": 1
      }
    }
  }
}
```

**Comment by Naupio** [comment]
sorter-example:
    query {
      udts(
        input: {
          limit: 3
          sorter: [{ sort_type: ASC, sort_value: SUPPLY }]
        }
      ) {
        entries {
          id
          name
          type
          supply
          account {
            eth_address
            script_hash
          }
        }
        metadata {
          total_count
          after
          before
        }
      }
    }

    {
      "data": {
        "udts": {
          "entries": [
            {
              "account": {
                "eth_address": "0x2503a1a79a443f3961ee96a8c5ec513638129614",
                "script_hash": "0x9b55204439c78d3b9cbcc62c03f31e47c8457fd39ca9a9eb805b364b45c26c38"
              },
              "id": "6841",
              "name": "test",
              "supply": "111",
              "type": "NATIVE"
            },
            {
              "account": {
                "eth_address": null,
                "script_hash": "0x3e1301e759261b676ce68d0d97936cd431a4af2a34072aa94e44655909765eb4"
              },
              "id": "6571",
              "name": "GodwokenToken on testnet_v1",
              "supply": "3247",
              "type": "BRIDGE"
            },
            {
              "account": {
                "eth_address": "0xd3ecf26a4a1e99c8717d7d8e365933fffa7d74d6",
                "script_hash": "0xb9150cbee429e205f9c956da7def16344232f50c851d9a5b0f7ef6f211c91cbf"
              },
              "id": "20021",
              "name": " My Hardhat Token",
              "supply": "100000000000000000000",
              "type": "NATIVE"
            }
          ],
          "metadata": {
            "after": "g3QAAAABZAAGc3VwcGx5dAAAAARkAApfX3N0cnVjdF9fZAAORWxpeGlyLkRlY2ltYWxkAARjb2VmbgkAAAAQYy1ex2sFZAADZXhwYQBkAARzaWduYQE=",
            "before": null,
            "total_count": 16
          }
        }
      }
    }

**Comment by Naupio** [comment]
```graphql
    sorter-example:
    query {
      udts(
        input: {
          limit: 3
          sorter: [{ sort_type: ASC, sort_value: NAME }]
        }
      ) {
        entries {
          id
          name
          type
          supply
          account {
            eth_address
            script_hash
          }
        }
        metadata {
          total_count
          after
          before
        }
      }
    }

    {
      "data": {
        "udts": {
          "entries": [
            {
              "account": {
                "eth_address": null,
                "script_hash": "0x3e1301e759261b676ce68d0d97936cd431a4af2a34072aa94e44655909765eb4"
              },
              "id": "6571",
              "name": "GodwokenToken on testnet_v1",
              "supply": "3247",
              "type": "BRIDGE"
            },
            {
              "account": {
                "eth_address": "0xd3ecf26a4a1e99c8717d7d8e365933fffa7d74d6",
                "script_hash": "0xb9150cbee429e205f9c956da7def16344232f50c851d9a5b0f7ef6f211c91cbf"
              },
              "id": "20021",
              "name": " My Hardhat Token",
              "supply": "100000000000000000000",
              "type": "NATIVE"
            },
            {
              "account": {
                "eth_address": null,
                "script_hash": "0x595cc14e574a708dc70a320d2026f79374246ed4659261131cdda7dd5814b5ca"
              },
              "id": "1",
              "name": "pCKB",
              "supply": "12800091655514882421855103",
              "type": "BRIDGE"
            }
          ],
          "metadata": {
            "after": "g3QAAAABZAAEbmFtZW0AAAAEcENLQg==",
            "before": null,
            "total_count": 16
          }
        }
      }
    }
```

**Comment by Keith-CY** [comment]
Any update about `sorted by holder count`?

**Comment by Naupio** [comment]
```graphql
    holders example:
    query {
      udts(
        input: {
          limit: 1
          sorter: [
            { sort_type: DESC, sort_value: EX_HOLDERS }
            { sort_type: ASC, sort_value: NAME }
          ]
        }
      ) {
        entries {
          id
          name
          holders_count
          type
          supply
          account {
            eth_address
            script_hash
          }
        }
        metadata {
          total_count
          after
          before
        }
      }
    }

    {
      "data": {
        "udts": {
          "entries": [
            {
              "account": {
                "eth_address": null,
                "script_hash": "0x595cc14e574a708dc70a320d2026f79374246ed4659261131cdda7dd5814b5ca"
              },
              "holders_count": 13563,
              "id": "1",
              "name": "pCKB",
              "supply": "13930369823571892421855103",
              "type": "BRIDGE"
            }
          ],
          "metadata": {
            "after": "g3QAAAABZAACaWRhAQ==",
            "before": null,
            "total_count": 14
          }
        }
      }
    }
```

**Comment by FrederLu** [comment]
> ```graphql
>     holders example:
>     query {
>       udts(
>         input: {
>           limit: 1
>           sorter: [
>             { sort_type: DESC, sort_value: EX_HOLDERS }
>             { sort_type: ASC, sort_value: NAME }
>           ]
>         }
>       ) {
>         entries {
>           id
>           name
>           holders_count
>           type
>           supply
>           account {
>             eth_address
>             script_hash
>           }
>         }
>         metadata {
>           total_count
>           after
>           before
>         }
>       }
>     }
> 
>     {
>       "data": {
>         "udts": {
>           "entries": [
>             {
>               "account": {
>                 "eth_address": null,
>                 "script_hash": "0x595cc14e574a708dc70a320d2026f79374246ed4659261131cdda7dd5814b5ca"
>               },
>               "holders_count": 13563,
>               "id": "1",
>               "name": "pCKB",
>               "supply": "13930369823571892421855103",
>               "type": "BRIDGE"
>             }
>           ],
>           "metadata": {
>             "after": "g3QAAAABZAACaWRhAQ==",
>             "before": null,
>             "total_count": 14
>           }
>         }
>       }
>     }
> ```

```
sorter: [
            { sort_type: DESC, sort_value: EX_HOLDERS }
            { sort_type: ASC, sort_value: NAME }
          ]
```
There is no change in data sorting after modifying the multi-condition filter conditions.

**Comment by Naupio** [comment]
holders count sorter example:
```graphql
    query {
      udts(
        input: {
          limit: 1
          sorter: [
            { sort_type: ASC, sort_value: EX_HOLDERS_COUNT }
            { sort_type: ASC, sort_value: NAME }
          ]
        }
      ) {
        entries {
          id
          name
          holders_count
          type
          supply
          account {
            eth_address
            script_hash
          }
        }
        metadata {
          total_count
          after
          before
        }
      }
    }

{
  "data": {
    "udts": {
      "entries": [
        {
          "account": {
            "eth_address": null,
            "script_hash": "0x3f052275a936fbba9f73b04d35c9099120e74a0ce183bdec18c2af7f599206ef"
          },
          "holders_count": 1,
          "id": "39912",
          "name": null,
          "supply": null,
          "type": "BRIDGE"
        }
      ],
      "metadata": {
        "after": "g3QAAAABZAAEbmFtZWQAA25pbA==",
        "before": null,
        "total_count": 14
      }
    }
  }
}
```

**Comment by Naupio** [comment]
holders count desc example:
```graphql
    query {
      udts(
        input: {
          limit: 1
          sorter: [
            { sort_type: DESC, sort_value: EX_HOLDERS_COUNT }
            { sort_type: ASC, sort_value: NAME }
          ]
        }
      ) {
        entries {
          id
          name
          holders_count
          type
          supply
          account {
            eth_address
            script_hash
          }
        }
        metadata {
          total_count
          after
          before
        }
      }
    }

{
  "data": {
    "udts": {
      "entries": [
        {
          "account": {
            "eth_address": null,
            "script_hash": "0x595cc14e574a708dc70a320d2026f79374246ed4659261131cdda7dd5814b5ca"
          },
          "holders_count": 13589,
          "id": "1",
          "name": "pCKB",
          "supply": "14479113756399902421855103",
          "type": "BRIDGE"
        }
      ],
      "metadata": {
        "after": "g3QAAAABZAAEbmFtZW0AAAAEcENLQg==",
        "before": null,
        "total_count": 14
      }
    }
  }
}
```

**Comment by FrederLu** [comment]
https://github.com/Magickbase/godwoken_explorer/issues/625#issuecomment-1185431423
Verified.

**Comment by Keith-CY** [comment]
Not used yet so it's safe to be merged
