### ISSUE TITLE
Enhancement: get the contract's tx_hash for update smart contract

### ISSUE THREAD

**Issue by Naupio** [Magickbase/godwoken_explorer#627]
integrate with sourcify feature

**Comment by Keith-CY** [comment]
We can also update `deployed tx hash` and `deployer address` on detecting a contract is deployed.

**Comment by Naupio** [comment]
link: [#650](https://github.com/Magickbase/godwoken_explorer/issues/650)

**Comment by zmcNotafraid** [comment]
polyjuices table 's  created_contract_address_hash column is contract address.So query contract address in this table then you can find gw tx hash, join transactions and find eth_hash to save as deployed tx hash. from account id is  deployer address

**Comment by FrederLu** [comment]
Verified.
