### ISSUE TITLE
Optimize saving logs/events

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#642]
https://github.com/Magickbase/godwoken_explorer/issues/629 This issue is caused by timeout of handling a bunch of events/logs in a single transaction
![image](https://user-images.githubusercontent.com/7271329/174938640-63d6acd9-a4eb-496c-9eeb-00a54d82101c.png)

Maybe events/logs should be treated in batches so it won't block other processes.

**Comment by zmcNotafraid** [comment]
Block number: 109921

**Comment by Keith-CY** [comment]
> Syn block (number: 109921), have 59w logs
> 
> * filter nil first_topic needs 52s
> * don't filter needs  51.33s
> 
> The bottleneck was insert 59w godwoken logs to DB
> 
> An strange thing， we query this block's log from public full node, we can't get first_topic was nil 's log.But from our read only node, we can get.

The last point is that if a log has an empty `first_topic`, it cannot be fetched from our read-only node, but it's accessible in the public full node.

Theoretically, the first topic is the signature of the event so it couldn't be empty, could you post a transaction hash for debug?

**Comment by zmcNotafraid** [comment]
> 109921
` curl https://godwoken-testnet-v1.ckbapp.dev -X POST -H "Content-Type: application/json"   -d '{"jsonrpc":"2.0", "method": "eth_getTransactionReceipt","params": ["0x7968f28cece252d9d7a565d52debfdce536768ee0d70cb2d8172a16080a33963"],"id":1}'`
