### ISSUE TITLE
[V1.1] Chart data is not updated every day at 00:10 (utc+0)

### ISSUE THREAD

**Issue by Dawn-githup** [Magickbase/godwoken_explorer#649]
![image](https://user-images.githubusercontent.com/77844990/175236349-50311d1b-a85d-4903-9bd8-f5dbf76bc283.png)

**Comment by zmcNotafraid** [comment]
Chart data have re-generated.

**Comment by zmcNotafraid** [comment]
The Oban Cron Plugin only pass args at boot time. So when we pass DateTime.utc_now to worker that it is not at the cron job run time, however is boot time.

**Comment by zmcNotafraid** [comment]
Wait tomorrow morning check the data

**Comment by Dawn-githup** [comment]
Fixed
