### ISSUE TITLE
Check contract deployment on sourcify

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#650]
![image](https://user-images.githubusercontent.com/7271329/175248571-8c03c546-6489-4e14-9553-dddc31ad6352.png)
![image](https://user-images.githubusercontent.com/7271329/175248692-05f403f2-7749-47d7-bd0a-cd3e0b266c15.png)

**Comment by Keith-CY** [comment]
How is it going

**Comment by Keith-CY** [comment]
https://gw-explorer.nervosdao.community/

**Comment by Keith-CY** [comment]
1. Need verified contract address
2. add a tutorial to deploy contract on godwoken

**Comment by Keith-CY** [comment]
> 1. Need verified contract address
> 2. add a tutorial to deploy contract on godwoken

Please try `0x7A4a65Db21864384d2D21a60367d7Fd5c86F8Fba` on Testnet, it can be found in https://sourcify.dev/#/lookup

**Comment by Keith-CY** [comment]
> > 1. Need verified contract address
> > 2. add a tutorial to deploy contract on godwoken
> 
> Please try `0x7A4a65Db21864384d2D21a60367d7Fd5c86F8Fba` on Testnet, it can be found in [sourcify.dev/#/lookup](https://sourcify.dev/#/lookup)

cc @Naupio

**Comment by Keith-CY** [comment]
Follow this guide to deploy erc20 on godwoken: https://dev.to/yakult/a-concise-hardhat-tutorial-part-2-writing-erc20-2jpm

Steps:
1. create an empty directory and set it as the working directory
```bash
mkdir erc20 && cd erc20 && npm init -y
```
2. init with hardhat
```bash
npx hardhat
```
3. set hardhat config to connect to godwoken
```javascript
// hardhat.config.js
import { HardhatUserConfig, task } from "hardhat/config";
import "@nomicfoundation/hardhat-toolbox";

const SK = # private key to deploy the contract, e.g. "0x" + "e".repeat(64);

const config: HardhatUserConfig = {
  solidity: "0.8.9",
  networks: {
    godwoken: {
      url: "https://godwoken-testnet-v1.ckbapp.dev", // godwoken rpc endpoint
      accounts: [SK],
    },
  },
};

export default config;
```
4. install open zeppelin for contract development
```
npm install @openzeppelin/contracts
```
5. add erc20 contract
```solidity
// ./contracts/Token.sol
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract Token is ERC20 {
    constructor(uint256 initialSupply) ERC20("CKBytes", "CKB") {
        _mint(msg.sender, initialSupply);
    }
}
```
6. add deploy script
```javascript
// ./scripts/deploy.ts
import hre from 'hardhat'

async function main () {
  const Token = await hre.ethers.getContractFactory('Token')
  console.log("Deploying Token...")
  const token = await Token.deploy('10000000000000000000000')

  await token.deployed()
  console.log('Token deployed to:', token.address)
}

main().then(() => process.exit(0)).catch(err => {
  console.error(err)
  process.exit(1)
})

```
7. use cli to deploy the contract
```bash
npx hardhat run scripts/deploy.ts --network godwoken
```

**Comment by Keith-CY** [comment]
The ETA. is updated, which part blocked the integration

**Comment by Naupio** [comment]
sourcify_check_by_addresses example:
```graphql
    query {
      sourcify_check_by_addresses(
        input: { addresses: ["0x7A4a65Db21864384d2D21a60367d7Fd5c86F8Fba"] }
      ) {
        address
    status
        chain_ids
      }
    }

    {
      "data": {
        "sourcify_check_by_addresses": [
          {
            "address": "0x7a4a65db21864384d2d21a60367d7fd5c86f8fba",
            "chain_ids": [
              "71401"
            ],
            "status": "perfect"
          }
        ]
      }
    }

    {
      "data": {
        "sourcify_check_by_addresses": [
          {
            "address": "0x7a4a65db21864384d2d21a60367d7fd5c86f8fba",
            "chain_ids": [
              "71401"
            ],
            "status": "perfect"
          }
        ]
      }
    }
```

**Comment by Naupio** [comment]
verify_and_update_from_sourcify example:
```graphql
    mutation {
      verify_and_update_from_sourcify(
        input: { address: "0x7A4a65Db21864384d2D21a60367d7Fd5c86F8Fba" }
      ) {
        id
        account_id
        # contract_source_code
        # abi
				compiler_version
        deployment_tx_hash
				name
      }
    }

    {
      "data": {
        "verify_and_update_from_sourcify": {
          "account_id": "43012",
          "compiler_version": "v0.8.9+commit.e5eed63a",
          "deployment_tx_hash": "0x505e25885828c847102af40848ba9cdaf7974d2046e7949ed46e2024494f33cd",
          "id": 4,
          "name": "Bridge"
        }
      }
    }
```

**Comment by Keith-CY** [comment]
I've tested with https://v1.testnet.gwscan.com/account/0x731fd088a2120ad5934e788f5051d778661106dd?tab=contract

and found two issues

1. before the contract is verified on sourcify, `tx hash` and `deployer` is not stored.
2. after the contract is verified on sourcify, `tx hash` is stored but `deployer` is still missing

**Comment by FrederLu** [comment]
<img width="788" alt="image" src="https://user-images.githubusercontent.com/25676576/185276198-e77b9871-f1d2-4c44-a987-4afc41423807.png">
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/25676576/185276283-948f01e4-4d07-4f64-8a08-7f955ee4051e.png">
https://v1.testnet.gwscan.com/account/0x2131181fb7233196e3536a7198c5fb2817fad46a2e3cfa633190ddd7fa313135?search=0x9e4e4a38116a6a5d955cd9d0cba5d8b8cda04851
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/25676576/185276619-cd32204f-40db-465a-b881-6ec49f103539.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/25676576/185276830-17325f1b-4ba8-4879-8eb8-df408a2056d5.png">

@Naupio 
The contract has been verified by sourcecify. After calling the back-end interface, the interface called by the page does not have Deployer and Deploy Transaction data.

**Comment by Naupio** [comment]
@FrederLu  I check the source data from database, I find your verify_xxx mutation request was called at stg-env.
and `https://v1.testnet.gwscan.com/account/0x2131181fb7233196e3536a7198c5fb2817fad46a2e3cfa633190ddd7fa313135?search=0x9e4e4a38116a6a5d955cd9d0cba5d8b8cda04851` this link is testnet-prod env

after I request a verify_xxx mution at `http://api.v1.betanet.gwscan.com/graphql` 
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/12268276/186441659-7abe119a-0e51-4936-838a-a17e19749d6f.png">

and this page `https://v1.testnet.gwscan.com/account/0x2131181fb7233196e3536a7198c5fb2817fad46a2e3cfa633190ddd7fa313135?search=0x9e4e4a38116a6a5d955cd9d0cba5d8b8cda04851 `  also return the correct smart contract data
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/12268276/186441873-faf7d181-7929-4146-835e-c88989e35f09.png">

the smart contract data was add success

**Comment by Naupio** [comment]
> I've tested with https://v1.testnet.gwscan.com/account/0x731fd088a2120ad5934e788f5051d778661106dd?tab=contract
> 
> and found two issues
> 
>     1. before the contract is verified on sourcify, `tx hash` and `deployer` is not stored.
> 
>     2. after the contract is verified on sourcify, `tx hash` is stored but `deployer` is still missing



> 

the second items seems deployer was exist, how to reoccur this scenario
<img width="947" alt="image" src="https://user-images.githubusercontent.com/12268276/186452183-74b4e29b-84bb-4028-9d5d-7f01c9e9e1e3.png">

by first time, I push a new pr https://github.com/Magickbase/godwoken_explorer/pull/890 here, and stg-env was deplyed. @FrederLu @Keith-CY

**Comment by Naupio** [comment]
@FrederLu  new pr #890  was deployed in testnet-prod env, please check this issue again

**Comment by FrederLu** [comment]
Now, after the ERC20 contract is deployed, you will not see deployer-related information immediately after viewing the contract page. 1. It will be automatically displayed after about 10s, and 2. it will be displayed after it needs to be triggered manually. Adjustments will be made later.

**Comment by Keith-CY** [comment]
Because the sourcify is enabled on mainnet, the function works well except some delay on showing deployment tx hash and deployer address, I think this issue could be closed

The further adjustment could be an independent issue as a refactor/enhancement. @Naupio please add the new issue for refining the workflow of updating deployment tx hash and close this one.

**Comment by Naupio** [comment]
> 

link https://github.com/Magickbase/godwoken_explorer/issues/918
