### ISSUE TITLE
[Bridged Token] Godwoken Test Token

### ISSUE THREAD

**Issue by Flouse** [Magickbase/godwoken_explorer#651]
### Token Name

GodwokenToken on testnet_v1

### Description

The sUDT_ERC20_Proxy of Godwoken Test Token.

### Symbol

GWK

### Decimals

18

### Logo URI

-

### SUDT Script Arguments

0x5c7253696786b9eddd34e4f6b6e478ec5742bd36569ec60c1d0487480ba4f9e3

### Contract Address

0x2275Afe815dE66BeAbE7A2C03005537AB843afB2

**Comment by zmcNotafraid** [comment]
Registered At : https://v1.betanet.gwscan.com/zh-CN/token/6571 @Flouse
