### ISSUE TITLE
[v0][Bridged Token] **YokaiSwap Token (YOK)**

### ISSUE THREAD

**Issue by honestgoing** [Magickbase/godwoken_explorer#671]
### Token Name

YokaiSwap Token

### Description

YokaiSwap is a next generation interoperable, decentralized trading platform and the first to come from the Nervos network.

### Symbol

YOK

### Decimals

18

### Max Supply

1000000000 YOK

### Website

https://yokaiswap.com

### Logo URI

https://tokens.yokaiswap.com/images/0xb02c930C2825A960A50ba4Ab005e8264498b64a0.png

### SUDT Script Arguments

```shell
0x656edac5463ef828a1a95f214b56adfe8f37da148fbc7ff424905e5264297c70
```

### Contract Address

0x3a2215B02C06e6425B670B8BB372FbeFB975B081

**Comment by zmcNotafraid** [comment]
Registered At : https://gwscan.com/zh-CN/token/49721
