### ISSUE TITLE
[v1][Bridged Token] **YokaiSwap Token (YOK)**

### ISSUE THREAD

**Issue by honestgoing** [Magickbase/godwoken_explorer#672]
### Token Name

YokaiSwap Token

### Description

YokaiSwap is a next generation interoperable, decentralized trading platform and the first to come from the Nervos network.

### Symbol

YOK

### Decimals

18

### Max Supply

1000000000 YOK

### Website

https://yokaiswap.com

### Logo URI

https://tokens.yokaiswap.com/images/0x885fb612947ccF1C7611894Bd828D388b046fc24.png

### SUDT Script Arguments

```shell
0x656edac5463ef828a1a95f214b56adfe8f37da148fbc7ff424905e5264297c70
```

### Contract Address

0x885fb612947ccF1C7611894Bd828D388b046fc24

**Comment by zmcNotafraid** [comment]
Registered At https://v1.gwscan.com/zh-CN/token/128.
Please submit an issue for YOK smart contract  @honestgoing
