### ISSUE TITLE
(graphql) add sorter and filter for Smart Contract list

### ISSUE THREAD

**Issue by Naupio** [Magickbase/godwoken_explorer#675]

**Comment by Naupio** [comment]
- [ ]    sorted by balance
- [ ]    sorted by tx count

**Comment by Naupio** [comment]
example:
```
    query {
      smart_contracts(
        input: { sorter: [{ sort_type: DESC, sort_value: EX_TX_COUNT }] }
      ) {
        entries {
          name
          account_id
          account {
            eth_address
            transaction_count
          }
        }
        metadata {
          total_count
          after
          before
        }
      }
    }

{
  "data": {
    "smart_contracts": {
      "entries": [
        {
          "account": {
            "eth_address": "0x2503a1a79a443f3961ee96a8c5ec513638129614",
            "transaction_count": 33
          },
          "account_id": "6841",
          "name": "EIP20"
        }
      ],
      "metadata": {
        "after": null,
        "before": null,
        "total_count": 1
      }
    }
  }
}
```

**Comment by Naupio** [comment]
add new `sorter` field for input object
@Keith-CY

**Comment by Naupio** [comment]
restful api use rpc to fetch ckb balance for responses , so doesn’t implement balance sorter for graphql query

**Comment by FrederLu** [comment]
![Image](https://user-images.githubusercontent.com/25676576/179670222-f9525484-1434-4aa1-a7ce-4036c19179ad.png)
![Image](https://user-images.githubusercontent.com/25676576/179670303-61f6fe87-6dd0-4b49-8834-e118226ef7a4.png)
@Naupio 
There are 2 pieces of data on the page. The interface output parameter displays one piece of data. Is the second piece of data filtered?
