### ISSUE TITLE
[vtest 1.1] link to main network should be v1.1 scan not v0 scan

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/godwoken_explorer#677]
https://v1.testnet.gwscan.com/zh-CN
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/32102187/176607835-ef19450c-8bc2-4ef2-b79e-5b02b5ce729d.png">
https://gwscan.com/zh-CN
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/32102187/176608077-26920233-0c11-4c61-8cd3-9dfcb3f74a94.png">

**Comment by Keith-CY** [comment]
Will be redeployed with new environment variables and link to v1 mainnet will be restored by PR https://github.com/Magickbase/godwoken-explorer-ui/pull/272
