### ISSUE TITLE
Update registered tokens by RFC "Universal Asset Notation"

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#678]
It was a mistake in force bridge that deployed the first bunch of tokens not following the "Universal Asset Notation" https://github.com/nervosnetwork/godwoken-info/blob/8a5128a2d8b008e40e2c05e5691ac841a96e790b/mainnet_v1/bridged-token-list.json

Here's a patch doc that added a `UAN` field to replace the symbol and a `displayName` field to replace the `name` to show. https://raw.githubusercontent.com/nervosnetwork/godwoken-info/rfc-uan/mainnet_v1/bridged-token-list.json

**Comment by Keith-CY** [comment]
Universal Assets Notation: https://github.com/nervosnetwork/rfcs/pull/335

**Comment by zmcNotafraid** [comment]
Updated!
