### ISSUE TITLE
mainnet_v1: balance of 0xb8cde090e6a4741b6450308fad1dc338c53936a0 wasn't updated

### ISSUE THREAD

**Issue by Flouse** [Magickbase/godwoken_explorer#679]
## https://app.warp.dev/block/Rb8fdefGX27a6U2VkBMalJ
```bash
curl -X POST https://v1.mainnet.godwoken.io/rpc \
  -H 'content-type: application/json' \
  --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0xb8cde090e6a4741b6450308fad1dc338c53936a0", "latest"],"id":1}'


{"jsonrpc":"2.0","id":1,"result":"0x2391bd8f421aafa204"}%                                                                
```
0x2391bd8f421aafa204 = 656137750000010502660 ~= 656 CKB

But the CKB balance in [this page](https://v1.gwscan.com/account/0xb8cde090e6a4741b6450308fad1dc338c53936a0?search=0xb8cde090e6a4741b6450308fad1dc338c53936a0) was not updated.
![image](https://user-images.githubusercontent.com/1297478/176623992-a3c0a1d6-487a-4c95-ad94-e7ca573f8437.png)

**Comment by zmcNotafraid** [comment]
I found this address only have 1 deposit of 400 ckb and have no erc20 transfer.So it's there any other way to get value?

**Comment by zmcNotafraid** [comment]
了解，那可能还得监听一下 Godwoken 的 Logs：
GW_LOG_SUDT_TRANSFER 和 GW_LOG_SUDT_PAY_FEE

see: https://github.com/nervosnetwork/godwoken/blob/develop/crates/utils/src/script_log.rs#L7-L37

**Comment by zmcNotafraid** [comment]
Schema:
- [ ] gw_log
- [ ] gw_sudt_transfer
- [ ] gw_sudt_pay_fee 
Process:
- [ ] fetch all gw log
- [ ] update balance

**Comment by Flouse** [comment]
> I query 1500 block's ckb balance is 400000000000009406219, so how to increase 0.000000000009406219 ckb ?

0xb8cde090e6a4741b6450308fad1dc338c53936a0 is the eth_address of the block_producer. It receive fee from every transactions.

**Comment by zmcNotafraid** [comment]
```
curl -X POST https://v1.mainnet.godwoken.io/rpc \
  -H 'content-type: application/json' \
  --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0xb8cde090e6a4741b6450308fad1dc338c53936a0", "latest"],"id":1}'

{"jsonrpc":"2.0","id":1,"result":"0x8f0971d36759664204"}%

```

0x8f0971d36759664204 = 2638564960000010502660 
![image](https://user-images.githubusercontent.com/12708910/177455722-2d30d46b-d782-449b-bf68-5e129ba0df54.png)
