### ISSUE TITLE
Update 3 tokens not following UAN

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#682]
TAI: https://github.com/nervosnetwork/godwoken-info/pull/41/files#diff-ef1bc6784ccea00946eb65a77a3e6c8b0ddba11ac4dbc0f66a08a1a84e844d8eR38-R39
pCKB: https://github.com/nervosnetwork/godwoken-info/pull/41/files#diff-ef1bc6784ccea00946eb65a77a3e6c8b0ddba11ac4dbc0f66a08a1a84e844d8eR12-R13
dCKB: https://github.com/nervosnetwork/godwoken-info/pull/41/files#diff-ef1bc6784ccea00946eb65a77a3e6c8b0ddba11ac4dbc0f66a08a1a84e844d8eR25-R26

IBFR: https://github.com/nervosnetwork/godwoken-info/pull/41/files#diff-ef1bc6784ccea00946eb65a77a3e6c8b0ddba11ac4dbc0f66a08a1a84e844d8eR25-R26 display name will be updated to `IBFR` for the rule https://github.com/nervosnetwork/rfcs/pull/335/files#diff-7bf2b14f7b4494be536928ba7b24b6e0ed9b5fe9579b2c2dd7cdfb5d92e0e1e2R45

**Comment by zmcNotafraid** [comment]
All Updated
