### ISSUE TITLE
Balance is not updated by deposit/withdraw action

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#684]
Address `0x0318e960501645a9755121c6d3f42b46900ff995` has 500 ckb deposited to v1
![image](https://user-images.githubusercontent.com/7271329/176876775-205e01d3-652e-4e46-9183-8ed05a52f8f1.png)

and then it deployed a tx with fee '16.23681 CKB`
![image](https://user-images.githubusercontent.com/7271329/176876750-f3ce0ce9-78b1-4c46-9bc7-671ea307f444.png)

Now it should have `483.76319 CKB`
![image](https://user-images.githubusercontent.com/7271329/176876928-083ba951-3f6b-4227-9a89-00c53295f28d.png)
0x1a39901a37bfcd6000 -> 483763190000000000000

But `0` is displayed, it seems that `deposit 500 CKB` didn't update its balance.

**Comment by zmcNotafraid** [comment]
![image](https://user-images.githubusercontent.com/12708910/177074439-72f5bb41-94ff-4717-bc71-a9ebfaba4642.png)
Current is correct

**Comment by Keith-CY** [comment]
![Image](https://user-images.githubusercontent.com/7271329/177599011-dff730e7-106f-4a01-bba7-85989824989f.png)

Still there

**Comment by Naupio** [comment]
seems also not updated by withdraw
link: https://github.com/Magickbase/godwoken_explorer/issues/699#issuecomment-1175959066

**Comment by FrederLu** [comment]
Verified.
deposit/withdraw operations now update the amount.

**Comment by Keith-CY** [comment]
Has been deployed to testnet
