### ISSUE TITLE
ERC721 token removed from transfers api

### ISSUE THREAD

**Issue by zmcNotafraid** [Magickbase/godwoken_explorer#686]
https://api.v1.gwscan.com/api/transfers?eth_address=0xce20908da256b4a3be51472ee53864e054a3a067&page=1 some null transfer value is erc721

**Comment by zmcNotafraid** [comment]
TODO:
1. add `eth_type` to udt schema(enum: ERC-20, ERC-721, ERC-1155)
2. Parse eth log and get tokens contract_address and eth_type, save to database .
3.  filter tokens: 
   ```
    bridged: type == :bridged, 
    native: type == :native and eth_type == ERC-20
    ERC-721: eth_type == ERC-721
    ERC-1155: eth_type == ERC-1155
```

**Comment by zmcNotafraid** [comment]
Current in udt tables we have above data:
1. type is bridge, this data only have bridge_account_id, doesn't have contract_address_hash, these data only used with deposit and withdrawal data.
2. type is native, this data have NO bridge_account_id, but have contract_address_hash, these data can join with token_transfer because they are all erc20 udt.

@Naupio

**Comment by zmcNotafraid** [comment]
CheckList:
1. account detail page
2. account token_transfer page 
3. account bridged page
4. account assets page
5. all UDT page
@FrederLu

**Comment by FrederLu** [comment]
Verified.
