### ISSUE TITLE
API performance improvement

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#687]
- [ ] api performance tests
- [x] monitor api performance: grafana
- [ ] reduce api response time
- [ ] improve page rendering

**Comment by zmcNotafraid** [comment]
grafana: https://github.com/Magickbase/godwoken_explorer/pull/896

**Comment by Keith-CY** [comment]
Any plan for the unchecked tasks?

**Comment by Keith-CY** [comment]
Will open new issues for each task @Naupio
