### ISSUE TITLE
Address field in exported could be address instead of alias

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#690]
[transactions (1).csv](https://github.com/Magickbase/godwoken_explorer/files/9037033/transactions.1.csv)
`Address` in exported data could be address instead of an alias

Download link: https://api.v1.betanet.gwscan.com/api/txs?block_hash=0xd3b6b28a9b302a3db63d94592626ba9c2efafa8dc9cb7c6689a014e0daa5a947&export=true

**Comment by zmcNotafraid** [comment]
fix at https://github.com/Magickbase/godwoken_explorer/issues/695
