### ISSUE TITLE
Token page click to export holder list interface is abnormal

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#692]
Click on the [holders](https://api.v1.betanet.gwscan.com/api/account_udts/udt_id=80&export=true) report page in [token page](https://godwoken-explorer-jrdqk08p7-nervosnet.vercel.app/token/6571) to prompt 500.
API：  https://api.v1.betanet.gwscan.com/api/account_udts/udt_id=80&export=true

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/25676576/177101792-51e24ac1-f710-4444-a12e-7431b162db3a.png">

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/25676576/177101710-4ad00abf-2e28-4fb4-bb2b-67bc52a6e7e0.png">

**Comment by Keith-CY** [comment]
https://v1.gwscan.com/zh-CN/account/0x8a09e0c71ff2b3a28f21b075db94e9c43522f38b?tab=assets
export tx list doesn't work too

**Comment by zmcNotafraid** [comment]
This udt doesn't have contract proxy caused this error.

**Comment by zmcNotafraid** [comment]
https://api.v1.betanet.gwscan.com/api/account_udts?udt_id=80&export=true is worked

**Comment by Keith-CY** [comment]
Link on mainnet should be fixed too https://api.v1.gwscan.com/api/account_udts/udt_id=110&export=true

**Comment by Keith-CY** [comment]
https://api.v1.betanet.gwscan.com/api/account_udts/udt_id=6571&export=true does not work

**Comment by Keith-CY** [comment]
The download url is incorrect, `/udt_id=6571` should be fixed into `?udt_id=6571`
Fixed by PR https://github.com/Magickbase/godwoken-explorer-ui/pull/312

**Comment by FrederLu** [comment]
@Keith-CY @zmcNotafraid 
Now the interface download file is normal, but there are some problems with the consistency of the exported file and page data. It is confirmed that the data inconsistency involves the data on the ckb, which is not easy to handle for the time being. We will pay more attention to it later.

**Comment by Keith-CY** [comment]
Please check again @zmcNotafraid
