### ISSUE TITLE
[bug] Cannot read properties of null (reading 'href')

### ISSUE THREAD

**Issue by Flouse** [Magickbase/godwoken_explorer#702]
https://v1.testnet.gwscan.com/token/6841

![image](https://user-images.githubusercontent.com/1297478/177252869-290b7cc1-9318-4814-9660-3ff5d65a1b9f.png)

**Comment by Keith-CY** [comment]
Fixed on testnet

This error exists only on testnet because a broken download link has been removed temporarily but the button is not, so the `null` is passed in and an exception is thrown. Now the corresponding button is removed too.
