### ISSUE TITLE
[General Contract] **Bridge**

### ISSUE THREAD

**Issue by liuxiaobleach** [Magickbase/godwoken_explorer#705]
### Contract Name

Bridge

### Contract Address

0x4c882ec256823ee773b25b414d36f92ef58a7c0c

### Code Format

solidity standard json input

### Deployment Transaction Hash

0x385b018742c8057ce3d3e68862a5621fdf2bb0260b02a846435152673cc214ef

### Compiler Version

v0.8.9+commit.e5eed63a

### Contract Source Code

```shell
https://github.com/celer-network/sgn-v2-contracts/blob/main/contracts/liquidity-bridge/Bridge.sol
https://gw-mainnet-explorer.nervosdao.community/address/0x4C882ec256823eE773B25b414d36F92ef58a7c0C/contracts

Can find abi here
```

### Other Info

https://github.com/celer-network/sgn-v2-contracts/blob/main/contracts/liquidity-bridge/Bridge.sol
https://gw-mainnet-explorer.nervosdao.community/address/0x4C882ec256823eE773B25b414d36F92ef58a7c0C/contracts

**Comment by zmcNotafraid** [comment]
Created at: https://v1.gwscan.com/zh-CN/account/0x4c882ec256823ee773b25b414d36f92ef58a7c0c
