### ISSUE TITLE
[General Contract]  PeggedTokenBridgeV2

### ISSUE THREAD

**Issue by liuxiaobleach** [Magickbase/godwoken_explorer#713]
### Contract Name

PeggedTokenBridgeV2

### Contract Address

0xb3833ecd19d4ff964fa7bc3f8ac070ad5e360e56

### Code Format

solidity multiple files

### Deployment Transaction Hash

0x51a7a3479267f2cd0f1dfca1dcf95bd0487bff0394431701f14dc090db73cf66

### Compiler Version

v0.8.9+commit.e5eed63a

### Contract Source Code

```shell
https://github.com/celer-network/sgn-v2-contracts/blob/main/contracts/pegged-bridge/PeggedTokenBridgeV2.sol

https://gw-mainnet-explorer.nervosdao.community/address/0xb3833Ecd19D4Ff964fA7bc3f8aC070ad5e360E56/contracts

Can find abi here
```

**Comment by zmcNotafraid** [comment]
Registered at: https://v1.gwscan.com/zh-CN/account/0xb3833ecd19d4ff964fa7bc3f8ac070ad5e360e56 @liuxiaobleach
