### ISSUE TITLE
[Native ERC20 Token] USDC

### ISSUE THREAD

**Issue by liuxiaobleach** [Magickbase/godwoken_explorer#714]
### display Name

USDC (via Celer cBridge from ETH)

### UAN

USDC.gw|cb.eth

### Logo URI

https://get.celer.app/cbridge-icons/USDT.png

### Contract Address

0x53bB26dc8C5EFC6c95C37155aCa487d1D043436a

### Code Format

solidity multiple files

### Deployment Transaction Hash

0x69f062d30ab9b5023ad9c6873430a0ed342641498187c0f76def87a20abd16f1

### Compiler Version

v0.8.9+commit.e5eed63a

### Contract Source Code

```shell
https://github.com/celer-network/sgn-v2-contracts/blob/main/contracts/pegged-bridge/tokens/MintSwapCanonicalToken.sol

https://gw-mainnet-explorer.nervosdao.community/address/0x53bB26dc8C5EFC6c95C37155aCa487d1D043436a/contracts
```

**Comment by Keith-CY** [comment]
Registered at https://v1.gwscan.com/token/192
