### ISSUE TITLE
[Native ERC20 Token] DAI

### ISSUE THREAD

**Issue by liuxiaobleach** [Magickbase/godwoken_explorer#716]
### display Name

DAI (via Celer cBridge from ETH)

### UAN

DAI.gw|cb.eth

### Logo URI

https://get.celer.app/cbridge-icons/DAI.png

### Contract Address

0x317F8d18FB16E49a958Becd0EA72f8E153d25654

### Code Format

solidity multiple files

### Deployment Transaction Hash

0x5f0623803e8cdd235c183f7aec0a132e62ccea1074fb26a29297ed0cd24c2561

### Compiler Version

v0.8.9+commit.e5eed63a

### Contract Source Code

```shell
https://github.com/celer-network/sgn-v2-contracts/blob/main/contracts/pegged-bridge/tokens/MintSwapCanonicalToken.sol

https://gw-mainnet-explorer.nervosdao.community/address/0x317F8d18FB16E49a958Becd0EA72f8E153d25654/contracts
```

**Comment by Keith-CY** [comment]
Registered at https://v1.gwscan.com/account/0x317f8d18fb16e49a958becd0ea72f8e153d25654
