### ISSUE TITLE
[Native ERC20 Token] WETH

### ISSUE THREAD

**Issue by liuxiaobleach** [Magickbase/godwoken_explorer#718]
### display Name

WETH (via Celer cBridge from ETH)

### UAN

WETH.gw|cb.eth

### Logo URI

https://get.celer.app/cbridge-icons/WETH.png

### Contract Address

0xB66954619363145a05eF835547449EB9050d82f6

### Code Format

solidity multiple files

### Deployment Transaction Hash

0x04344b7b5ead6f403d9e72bad47645161e6372041b21b33004f49f92afa5f453

### Compiler Version

v0.8.9+commit.e5eed63a

### Contract Source Code

```shell
https://github.com/celer-network/sgn-v2-contracts/blob/main/contracts/pegged-bridge/tokens/MintSwapCanonicalToken.sol

https://gw-mainnet-explorer.nervosdao.community/address/0xB66954619363145a05eF835547449EB9050d82f6/contracts
```

**Comment by zmcNotafraid** [comment]
![image](https://user-images.githubusercontent.com/12708910/177716320-f0cb2f38-2135-4ac3-af76-efe7d0ce3281.png)
All created.

**Comment by Keith-CY** [comment]
Registered at https://v1.gwscan.com/account/0xb66954619363145a05ef835547449eb9050d82f6
