### ISSUE TITLE
Deposit record of pure CKB includes `pCKB` and `CKB` is quite confusing

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#719]
![image](https://user-images.githubusercontent.com/7271329/177558387-b02c5015-b107-4890-ac22-7e74ba0863f9.png)
Actually, they are the same asset and should have the same value, could we return the paired erc20 `pCKB` with 0 and rename the `CKB` column to `pCKB`?

**Comment by zmcNotafraid** [comment]
@Keith-CY  
![image](https://user-images.githubusercontent.com/12708910/182147608-566df128-2db1-44e4-a39e-75e4f4abe75e.png)
It's this right?

**Comment by Keith-CY** [comment]
> @Keith-CY ![image](https://user-images.githubusercontent.com/12708910/182147608-566df128-2db1-44e4-a39e-75e4f4abe75e.png) It's this right?

I think `pCKB` in `0 pCKB` could be removed too, but if it's not convenient to do, keeping it is acceptable

**Comment by zmcNotafraid** [comment]
We only need to change testnet ckb symbol to finish this issue
