### ISSUE TITLE
The search interface request returns 500.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#737]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/25676576/177900950-45889b16-e613-4c53-acd9-42ddebf09e90.png">
https://api.v1-betanet.gwscan.com/api/search?keyword=11111111111111111111

The search interface reports 500 at the input 11111111111111111111 interface. Which small partner should I take a look at?

**Comment by zmcNotafraid** [comment]
- [ ] search 11111111111111111111
- [ ] pending transaction search

**Comment by FrederLu** [comment]
> 11111111111111111111


The interface no longer prompts 500, and the verification is passed.

**Comment by FrederLu** [comment]
Production environment verification passed.
