### ISSUE TITLE
[Native ERC20 Token] BUSD

### ISSUE THREAD

**Issue by liuxiaobleach** [Magickbase/godwoken_explorer#742]
### display Name

BUSD (via Celer cBridge from BNB Chain)

### Description

BUSD (via Celer cBridge from BNB Chain)

### UAN

BUSD.gw|cb.bsc

### Logo URI

https://get.celer.app/cbridge-icons/BUSD.png

### Contract Address

0xcD7bC9fC617a4F82eC1c8359D1C8610B90e3B44C

### Code Format

solidity multiple files

### Deployment Transaction Hash

0xd051da53a283d9a5180d744ac8a5e92208fd64364aba7994742aaa0e1c267c75

### Compiler Version

v0.8.9+commit.e5eed63a

### Contract Source Code

```shell
https://github.com/celer-network/sgn-v2-contracts/blob/main/contracts/pegged-bridge/tokens/MintSwapCanonicalToken.sol

https://gw-mainnet-explorer.nervosdao.community/address/0xB66954619363145a05eF835547449EB9050d82f6/contracts
```

**Comment by zmcNotafraid** [comment]
Registered at : https://v1.gwscan.com/zh-CN/token/246
