### ISSUE TITLE
PendingTransaction fetch from public rpc

### ISSUE THREAD

**Issue by zmcNotafraid** [Magickbase/godwoken_explorer#752]
Before we use gw_get_transaction rpc method(pass gw_hash) to fetch pending transaction.But now we can only get eth_hash, so need to do some extra work for this

**Comment by Keith-CY** [comment]
Waiting for a new PRC to get `gw hash` by `eth hash`

**Comment by classicalliu** [comment]
Add two new RPCs 
- https://github.com/nervosnetwork/godwoken-web3/pull/449

**Comment by Flouse** [comment]
> Add two new RPCs
> 
> * [feat: add `poly_getEthTxHashByGwTxHash` and `poly_getGwTxHashByEthTxHash` nervosnetwork/godwoken-web3#449](https://github.com/nervosnetwork/godwoken-web3/pull/449)

Godwoken testnet_v1 deployed:
https://github.com/nervosnetwork/godwoken-web3/releases/tag/v1.5.0-rc1

**Comment by FrederLu** [comment]
And https://github.com/Magickbase/godwoken_explorer/issues/729#issuecomment-1182960045 is a class of problems, and the verification passes.
Verified.

**Comment by Flouse** [comment]
> > Add two new RPCs
> > 
> > * [feat: add `poly_getEthTxHashByGwTxHash` and `poly_getGwTxHashByEthTxHash` nervosnetwork/godwoken-web3#449](https://github.com/nervosnetwork/godwoken-web3/pull/449)
> 
> Godwoken testnet_v1 deployed: https://github.com/nervosnetwork/godwoken-web3/releases/tag/v1.5.0-rc1

Godwoken mainnet_v1 deployed:

```bash
curl https://v1.mainnet.godwoken.io/rpc -X POST \
  -H "Content-Type: application/json" \
  -d '{"jsonrpc": "2.0", "method":"poly_version", "params": [], "id": 1}'

# Result
{"jsonrpc":"2.0","id":1,"result":{"versions":{"web3Version":"1.5.2-rc1","web3IndexerVersion":"1.5.2-rc1","godwokenVersion":"1.4.0-rc4 17a0cb5"},"nodeInfo":{...
```
