### ISSUE TITLE
[V1.3] Transaction Info page download erc20Records in Chinese Untranslated

### ISSUE THREAD

**Issue by Dawn-githup** [Magickbase/godwoken_explorer#756]
- Switch Chinese
- Transaction Info page
- download > erc20Records

**Comment by Keith-CY** [comment]
It was designed (https://github.com/Magickbase/godwoken_explorer/issues/559) by postponed due to progress pressure.

We will support internationalization if there's a bandwidth

**Comment by zmcNotafraid** [comment]
![image](https://user-images.githubusercontent.com/12708910/194692726-9bf874c4-a03c-40d4-81fe-b84707726253.png)
I think this issue is only aim to the button translation.Not csv header's translation @Keith-CY

**Comment by Keith-CY** [comment]
This issue may be obscure, but internationalization is required at first in the PRD mentioned above https://github.com/Magickbase/godwoken_explorer/issues/559

So I think we could support querying with `locale` if possible.
