### ISSUE TITLE
[V1.3] Transaction Info page download erc20Records failed

### ISSUE THREAD

**Issue by Dawn-githup** [Magickbase/godwoken_explorer#757]
1. Click download erc20records failed

**Comment by zmcNotafraid** [comment]
Can you submit which url downloads failed @Dawn-githup

**Comment by Dawn-githup** [comment]
> 你能提交哪些url下载失败@Dawn-githup

[https://v1.testnet.gwscan.com/zh-CN/tx/0xe34637c629e87e930e2c2d69b01db2dbfed8e1361dcdbf038db51df5c10cea58](https://v1.testnet.gwscan.com/zh-CN/tx/0xe34637c629e87e930e2c2d69b01db2dbfed8e1361dcdbf038db51df5c10cea58)
- Click download erc20records

**Comment by Dawn-githup** [comment]
> Can you submit which url downloads failed @Dawn-githup

[https://v1.testnet.gwscan.com/zh-CN/tx/0xe34637c629e87e930e2c2d69b01db2dbfed8e1361dcdbf038db51df5c10cea58](https://v1.testnet.gwscan.com/zh-CN/tx/0xe34637c629e87e930e2c2d69b01db2dbfed8e1361dcdbf038db51df5c10cea58)
- Click download erc20records

**Comment by zmcNotafraid** [comment]
Need to handle with no records condition

**Comment by FrederLu** [comment]
The downloadable file address is as follows：
https://v1.gwscan.com/tx/0xc8be330a4ba6db2ae8f77f61e12e17087000176d986ed83290ec9fcc67185779
https://v1.testnet.gwscan.com/zh-CN/tx/0xacc41c989f4d9c5f351aa7486989f94c2aec5c3f0fdbc9791bcacd7db13d9f86

Unable to download URL：
https://github.com/Magickbase/godwoken_explorer/issues/757#issuecomment-1184036009
https://v1.testnet.gwscan.com/zh-CN/tx/0x3b9075b6755eb02a48b6ed4357d19a17d4fa75b78bf4decef554f276fc5bbe1a
![Image](https://user-images.githubusercontent.com/25676576/182123309-cd82756b-5fde-4789-8015-0e5036b4c665.png)

**Comment by FrederLu** [comment]
Verified.

**Comment by Keith-CY** [comment]
@Dawn-githup please check if it works and close this issue if it's verified

**Comment by Dawn-githup** [comment]
Fixed
