### ISSUE TITLE
Incorrect asset list of a specific account

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#759]
https://v1.gwscan.com/account/0x540c12a76fbac81b64cc119524a8b69389f0a0ae?tab=assets
This account holds 0 YOK, which should be filtered out in the list

**Comment by Keith-CY** [comment]
1. Filtered in the front-end
2. Filtered in the API

**Comment by Keith-CY** [comment]
Ready in API

**Comment by Naupio** [comment]
fix here: https://github.com/Magickbase/godwoken_explorer/pull/745

**Comment by Naupio** [comment]
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/12268276/181154027-8a17330c-8765-488d-8961-7ae618067bc4.png">

**Comment by FrederLu** [comment]
![Image](https://user-images.githubusercontent.com/25676576/182127021-d94fc6b7-ce7d-42ff-a26e-d2665bf30119.png)

Verified.

**Comment by Keith-CY** [comment]
https://v1.gwscan.com/account/0x540c12a76fbac81b64cc119524a8b69389f0a0ae?tab=assets

This address holds bridged YOK and native YOK of different balances

**Comment by Keith-CY** [comment]
> [v1.gwscan.com/account/0x540c12a76fbac81b64cc119524a8b69389f0a0ae?tab=assets](https://v1.gwscan.com/account/0x540c12a76fbac81b64cc119524a8b69389f0a0ae?tab=assets)
> 
> This address holds bridged YOK and native YOK of different balances
> 
> ![image](https://user-images.githubusercontent.com/7271329/182128882-5499bade-42fe-446d-bd94-0089d2dcccc0.png)

And they are both different from the value shown in `Yokai Swap`

**Comment by Keith-CY** [comment]
> [v1.gwscan.com/account/0x540c12a76fbac81b64cc119524a8b69389f0a0ae?tab=assets](https://v1.gwscan.com/account/0x540c12a76fbac81b64cc119524a8b69389f0a0ae?tab=assets)
> 
> This address holds bridged YOK and native YOK of different balances
> 
> ![image](https://user-images.githubusercontent.com/7271329/182128882-5499bade-42fe-446d-bd94-0089d2dcccc0.png)

I'm going to hide `bridged` one because they are theoretically the same token. But difference between their value should be debugged though

**Comment by Keith-CY** [comment]
> [v1.gwscan.com/account/0x540c12a76fbac81b64cc119524a8b69389f0a0ae?tab=assets](https://v1.gwscan.com/account/0x540c12a76fbac81b64cc119524a8b69389f0a0ae?tab=assets)
> 
> This address holds bridged YOK and native YOK of different balances
> 
> ![image](https://user-images.githubusercontent.com/7271329/182128882-5499bade-42fe-446d-bd94-0089d2dcccc0.png)

Hotfixed on mainnet, now only the `native` YOK is in the list
![image](https://user-images.githubusercontent.com/7271329/182130958-b65f54a6-8331-40a4-9dfa-d355c90a773f.png)

But the response of API should be fixed too, @Naupio @FrederLu

**Comment by Naupio** [comment]
can fix here https://github.com/Magickbase/godwoken_explorer/pull/805
