### ISSUE TITLE
[v0][Bridged Token] **StableKoi Token (KOIv1)**

### ISSUE THREAD

**Issue by kintar2010** [Magickbase/godwoken_explorer#760]
### Display Name

StableKoi Token

### Description

StableKoi is the leading cross-chain stable swap on Nervos Network, providing the liquid foundation for stablecoins.

### UAN

KOIv1.gw|gb.ckb

### Decimals

18

### Max Supply

1,000,000,000,000 KOI

### Website

https://stablekoi.com/

### Logo URI

https://app.stablekoi.com/images/tokens/0xd66eb642eE33837531FdA61eb7Ab15B15658BcaB.svg

### SUDT Script Arguments

```shell
0x68ab5e63d676ce31c56c73d037f38bc35398d4af94b43f8717832c1c81eb251e
```

### Contract Address

0x02261C825979D36D79d4dC32d42a16B75aC6F1B3

**Comment by zmcNotafraid** [comment]
Registered at: https://gwscan.com/zh-CN/token/49787 @kintar2010
