### ISSUE TITLE
(Docs) build github page for graphql api

### ISSUE THREAD

**Issue by Naupio** [Magickbase/godwoken_explorer#767]

**Comment by Naupio** [comment]
https://magickbase.github.io/gwscan-graphql-doc/

**Comment by Keith-CY** [comment]
Code format is in improper format, e.g.


![Image](https://user-images.githubusercontent.com/7271329/186300583-bd811726-afc2-4afc-9fd4-f576a9a254ea.png)

**Comment by Keith-CY** [comment]
Seems that the `docs` is an independent repo and not triggered by update of `godwoken_explorer`, maybe we should add a CI to deploy docs automatically.

**Comment by Naupio** [comment]
fixed docs format @FrederLu
