### ISSUE TITLE
(graphql) fix query account subfieild with udt throw error 

### ISSUE THREAD

**Issue by Naupio** [Magickbase/godwoken_explorer#770]
```graphql
query {
  account(
    input: {
      address: "0xe05d380839f32bc12fb690aa6fe26b00bd982613"
    }
  ) {
    type
    eth_address
    script_hash
    script
    transaction_count
    nonce
    udt {
      id
      name
      decimal
      symbol
    }
    smart_contract {
      name
      deployment_tx_hash
      compiler_version
      compiler_file_format
      contract_source_code
      constructor_arguments
      abi
    }
  }
}
```

**Comment by Naupio** [comment]
access this contract address with internal error https://v1.testnet.gwscan.com/account/0xe05d380839f32bc12fb690aa6fe26b00bd982613 

reason:
account with this address has 2 mapping udt records, one is udt.id == account.id, the other is udt.bridged_account_id ==  udt.id

fix:
In here, the graphql `account` query api with subfields `udt` that we use udt.id mapping the account.id to fix the internal error.

**Comment by FrederLu** [comment]
> summary: access some contract `account` with subfeild `udt` will rasie internal error
> 
> env: testnet-prod
> 
> access link: https://v1.testnet.gwscan.com/account/0xe05d380839f32bc12fb690aa6fe26b00bd982613
> 
> reason: account with this address has 2 mapping udt records, one is udt.id == account.id, the other is udt.bridged_account_id == udt.id
> 
> fix: In here, the graphql `account` query api with subfields `udt` that we use udt.id mapping the account.id to fix the internal error.
> 
> error snapshot: <img alt="image" width="1343" src="https://user-images.githubusercontent.com/12268276/180391624-d3e0ee8c-0a23-45b1-a121-b661b2c4d873.png">

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/25676576/180396969-b581bf62-e49d-41d5-8832-9e4cbff285f8.png">
@Naupio 
The interface report 500 on the page is now normal, and the verification is passed.
