### ISSUE TITLE
 Bridged Token List page is missing data.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#776]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/25676576/180419699-8bf25e8f-133b-4a2a-b1a4-7b3d51f24f03.png">

There is missing data compared to the [url](https://github.com/nervosnetwork/godwoken-info/blob/main/mainnet_v1/bridged-token-list.json) on mainnet, and now only part of it is displayed.

**Comment by zmcNotafraid** [comment]
I thinks now is correct, please check again @FrederLu

**Comment by FrederLu** [comment]
Verified.
