### ISSUE TITLE
origin 'https://bridge.godwoken.io/' has been blocked by CORS policy

### ISSUE THREAD

**Issue by Flouse** [Magickbase/godwoken_explorer#777]
![image](https://user-images.githubusercontent.com/1297478/180465426-fe6bbc43-1b9d-40fe-ad30-cffd09419cb6.png)

## log
from origin 'https://bridge.godwoken.io/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

## HTTP ERROR 500
https://api.v1.gwscan.com/api/withdrawal_histories?owner_lock_hash=0xc10d05d15d8f1c4295df6d5849c6a1a6daebe448bad1d8af8580305d9482a5c8

**Comment by zmcNotafraid** [comment]
It's caused by the  udt's transfer count bug.Because withdrawal history's udt is bridge token.So we need to find it's proxy contract and get it transfer count.
Current is fixed.

**Comment by Flouse** [comment]
![image](https://user-images.githubusercontent.com/1297478/180591712-c8d52b36-e787-4ea0-9df4-47779e3f0782.png)
