### ISSUE TITLE
Total supply of pCKB is incorrect

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#778]
![image](https://user-images.githubusercontent.com/7271329/180475985-f608ecb6-2274-45c8-9a4b-a2e193144de4.png)

Environment: Mainnet
API returns
```
{
  "name": "pCKB (via GodwokenBridge from CKB)",
  "supply": "174672032486787920000023033",
  "type": "BRIDGE"
},
{
  "name": "pCKB (via GodwokenBridge from CKB)",
  "supply": "958352657424121880000023033",
  "type": "NATIVE"
},
```

called from contract(pCKB contract -> read contract -> total supply): https://v1.gwscan.com/account/0x7538c85cae4e4673253ffd2568c1f1b48a71558a?tab=contract
`961196430426632320000023033`

**Comment by FrederLu** [comment]
![Image](https://user-images.githubusercontent.com/25676576/182334156-dbd1f93c-f0bb-4fe8-b5d2-243283697442.png)

![Image](https://user-images.githubusercontent.com/25676576/182334316-20bbf331-fa52-4649-994c-315b94697060.png)

2 Total Supply data inconsistent for a long time.2 Total Supply data inconsistent for a long time. totalSupply(): uint256 data is larger than [url](https://godwoken-explorer-ui-development.vercel.app/token/375) data.

**Comment by FrederLu** [comment]
![Image](https://user-images.githubusercontent.com/25676576/182349496-799f1fdc-803c-484e-a585-200604942605.png)

![Image](https://user-images.githubusercontent.com/25676576/182349233-6fbc1c2e-9d27-4c9c-b5f8-eb5d7252156c.png)


Now that the data of the two are consistent, it takes a long time for the data to be updated asynchronously.
