### ISSUE TITLE
Add udt id of corresponding native erc20 token when requesting a bridge token

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#788]
```
query($script_hash: HashFull, $address: HashAddress) {
  account(
    input: {
      script_hash: $script_hash,
    }
  ) {
    script
		udt {
			id
			name
			decimal
		}
  }
}
```

When I query an account of UDT with `udt field` the `udt.id` points to the bridged one. However, the `udt.id` cannot be used to visit the token page.

For example, the `GodwokenToken on testnet_v1` has a bridge one of id `6571` and a native one of id `36050`. `36050` is recognized by the API to fetch a token while `6571` is not.

So the link on the sudt account page points to token page leads to 404.

Can we add one more field of the corresponding native token, or simply return token info even the requested id is a bridged one?

**Comment by Keith-CY** [comment]
add a field named `bridged_udt`

**Comment by Naupio** [comment]
native example:
```graphql
query {
  account(
    input: {
      address: "0x24AEE7A0DC15BC45B8C1345E38AF6FC62152035D"
    }
  ) {
    udt {
      id
      name
      bridge_account_id
      type
    }
    bridged_udt {
      id
      name
      bridge_account_id
      type
    }
  }
}

{
  "data": {
    "account": {
      "bridged_udt": null,
      "udt": {
        "bridge_account_id": null,
        "id": "49095",
        "name": "My Token",
        "type": "NATIVE"
      }
    }
  }
}
```

bridge account example:
```graphql
    query {
      account(
        input: {
          script_hash: "0x3E1301E759261B676CE68D0D97936CD431A4AF2A34072AA94E44655909765EB4"
        }
      ) {
        udt {
          id
          name
          bridge_account_id
          type
        }
        bridged_udt {
          id
          name
          bridge_account_id
          type
        }
      }
    }

    {
      "data": {
        "account": {
          "bridged_udt": {
            "bridge_account_id": 36050,
            "id": "6571",
            "name": "GodwokenToken on testnet_v1",
            "type": "BRIDGE"
          },
          "udt": {
            "bridge_account_id": null,
            "id": "36050",
            "name": "GodwokenToken on testnet_v1",
            "type": "NATIVE"
          }
        }
      }
    }
```

**Comment by FrederLu** [comment]
According to the above example, the interface is normal.


Reference native example https://github.com/Magickbase/godwoken_explorer/issues/788#issuecomment-1196271132  , use address "0xcc0af0af911dd40853b8c8dfee90b32f8d1ecad6".

```graphql
query {
  account(
    input: {
      address: "0xcc0af0af911dd40853b8c8dfee90b32f8d1ecad6"
    }
  ) {
    udt {
      id
      name
      bridge_account_id
      type
    }
    bridged_udt {
      id
      name
      bridge_account_id
      type
    }
  }
}
```

![Image](https://user-images.githubusercontent.com/25676576/182356664-36459d4c-4f1c-4770-af00-fe9d0fc45fef.png)

![Image](https://user-images.githubusercontent.com/25676576/182356318-3a37b76e-2f9d-4387-b564-a246b26a9e86.png)

The interface has no data, and the [url]( https://v1.betanet.gwscan.com/account/0xcc0af0af911dd40853b8c8dfee90b32f8d1ecad6?tab=assets
) has data data.

**Comment by Keith-CY** [comment]
Should be udpated in front-end

**Comment by FrederLu** [comment]
Now the interfaces is consistent with the page data, and the verification is passed.
