### ISSUE TITLE
Font doesn't work on some platform

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#789]
![image](https://user-images.githubusercontent.com/7271329/180963553-b76eba6b-358e-4330-ad43-9d0e4a9fa3aa.png)

`Roboto` doesn't work on `from` and `to`

Please check the font of new UI design

**Comment by qiweiii** [comment]
Checked on my machine, cannot reproduce.

Is this on old UI? if it is, I guess it could because I did not import 'Roboto Mono' from `@fontsource` in `_app`

If on new ui, addresses are using Jetbrain Mono, it should be fine since I imported that font

**Comment by Keith-CY** [comment]
> Checked on my machine, cannot reproduce.
> 
> Is this on old UI? if it is, I guess it could because I did not import 'Roboto Mono' from `@fontsource` in `_app`
> 
> If on new ui, addresses are using Jetbrain Mono, it should be fine since I imported that font

yes，on old ui and reproducible on windows and KDE.

I will check on new ui once all pages are ready

**Comment by Keith-CY** [comment]
Fixed in new UI
