### ISSUE TITLE
Order `transfer list` of a specific transaction in `asc`

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#793]
1. order transfer list of a specific transaction in `asc`
2. add `log index` in the list
Ref: https://github.com/Magickbase/visual-style-guide/issues/4#issuecomment-1195341607

**Comment by Keith-CY** [comment]
PR to order transfer list of a specific transaction: https://github.com/Magickbase/godwoken-explorer-ui/pull/389

**Comment by Keith-CY** [comment]
Please verify in the production environment

**Comment by FrederLu** [comment]
This issue is subject to https://github.com/Magickbase/godwoken_explorer/issues/793#issuecomment-1205960809, and the verification is passed.
