### ISSUE TITLE
Speed synchronization

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#794]
The current workflow seems to have a mandatory interval to synchronize a block, especially on catching up after a halting. The span could be almost a minute even blocks are empty.

We should explain the workflow with mermaid diagram in this issue and find out what the bottleneck is.

**Comment by Keith-CY** [comment]
Debug locally

**Comment by zmcNotafraid** [comment]
Test in locally, the api can display blocks timely，so maybe need to pay attention to this situation for next time.

**Comment by zmcNotafraid** [comment]
After lastest test, the speed is ok.
