### ISSUE TITLE
Account's asset is missing in the list

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#795]
Address owns YOK but is not listed in its asset list
![image](https://user-images.githubusercontent.com/7271329/181356957-743635c1-3090-4c5d-9710-a6f90affbb30.png)

Environment: Mainnet
Address: 0xdef1c554531cc0b1bba75bb3a0e925d8a1cf6c69

**Comment by Keith-CY** [comment]
This issue is urgent because the user thought his token was lost

**Comment by Naupio** [comment]
@Keith-CY  testnet-prod was deployed

**Comment by FrederLu** [comment]
![Image](https://user-images.githubusercontent.com/25676576/182116500-f2255b3c-506e-4cf2-a51b-5a32de553480.png)

Verified.
