### ISSUE TITLE
[Feature Request] Add pending transaction list

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#802]
# Requirement
An RPC fetching a list of the pending transactions' hashes will be added into the node https://github.com/nervosnetwork/godwoken/pull/772/files#diff-429e77264474e64c6aece151ed3977aa53693405a99a2b8ddcddf1cb71454405R745

With this RPC, we can then get the transactions in mem-pool(transaction submitted but not packaged into a block) by batch RPC request `gw_getTransaction` and show them on an independent page as https://etherscan.io/txsPending

# Schema
All the same as current graphql query of fetching `transactions`

# Pages
1. add an independent page for all pending transactions as https://etherscan.io/txsPending;
2. `transaction` in an account's transaction list, `transfer` in an account's transfer list could have a `pending` status, which has been implemented.

# Others
1. include `pending transactions`, `pending transfer` in an account's `transaction list`, `transfer list`, better returned by the same graphql query;
2. do not add `pending transactions` in `list of all transactions, or we can add a filter for this status.

**Comment by Keith-CY** [comment]
@zmcNotafraid @Naupio @FrederLu @Kirl70 please have a review

**Comment by Kirl70** [comment]
Filter entry on the transaction page, as shown in the design draft:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6%3A920
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/106060898/182338365-2e9ee6bd-87a6-4b1f-bc6c-cf031e9a94d5.png">

**Comment by Keith-CY** [comment]
Wait for release of godwoken node

**Comment by Keith-CY** [comment]
godwoken@v1.5 has been pre released https://github.com/nervosnetwork/godwoken/releases/tag/v1.5.0-rc1

**Comment by Keith-CY** [comment]
godwoken@v1.5 testnet has been deployed

**Comment by Keith-CY** [comment]
Only public node supports this API

**Comment by zmcNotafraid** [comment]
For transaction graphql query, we add a input filed as status.It's value include:
- PENDING: only pending transaction return
- ON_CHAINED: only on chain transactions return
- not set this value: return all transaction
```
query {
      transactions(
        input: {
          status: PENDING
        }
      ) {
        entries {
          hash
        }
      }
    }
```

**Comment by Keith-CY** [comment]
> For transaction graphql query, we add a input filed as status.It's value include:
> 
> * PENDING: only pending transaction return
> * ON_CHAINED: only on chain transactions return
> * not set this value: return all transaction
> 
> ```
> query {
>       transactions(
>         input: {
>           status: PENDING
>         }
>       ) {
>         entries {
>           hash
>         }
>       }
>     }
> ```

Why not use `stauts: ['PENDING', "SUCCESS', 'FAILED']` so we can get a list of success txns or failed txns

**Comment by zmcNotafraid** [comment]
> > For transaction graphql query, we add a input filed as status.It's value include:
> > 
> > * PENDING: only pending transaction return
> > * ON_CHAINED: only on chain transactions return
> > * not set this value: return all transaction
> > 
> > ```
> > query {
> >       transactions(
> >         input: {
> >           status: PENDING
> >         }
> >       ) {
> >         entries {
> >           hash
> >         }
> >       }
> >     }
> > ```
> 
> Why not use `stauts: ['PENDING', "SUCCESS', 'FAILED']` so we can get a list of success txns or failed txns

Because transactions table have other types transaction(polyjuice_creator;eth_addr_reg), not only polyjuice.For polyjuice tx, they have status.For other gw tx, they have no status .

**Comment by Keith-CY** [comment]
> > > For transaction graphql query, we add a input filed as status.It's value include:
> > > 
> > > * PENDING: only pending transaction return
> > > * ON_CHAINED: only on chain transactions return
> > > * not set this value: return all transaction
> > > 
> > > ```
> > > query {
> > >       transactions(
> > >         input: {
> > >           status: PENDING
> > >         }
> > >       ) {
> > >         entries {
> > >           hash
> > >         }
> > >       }
> > >     }
> > > ```
> > 
> > 
> > Why not use `stauts: ['PENDING', "SUCCESS', 'FAILED']` so we can get a list of success txns or failed txns
> 
> Because transactions table have other types transaction(polyjuice_creator;eth_addr_reg), not only polyjuice.For polyjuice tx, they have status.For other gw tx, they have no status .

Got it, then I think the API is enough for now.
