### ISSUE TITLE
Some issues on the new UI

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#803]
1. flashes on opening the menu, and anchor of menu should be `right-top`, now it's `left-top`

https://user-images.githubusercontent.com/7271329/181753390-bed3033a-ca61-4a8f-a191-c14e89e0d20a.mp4

https://user-images.githubusercontent.com/7271329/181753943-57913054-3d60-48b6-a7ae-93acd51825dd.mov

2. progress is covered by the list
![O Tas](https://user-images.githubusercontent.com/7271329/181753001-05411adc-012d-4321-bd53-a25670579ae5.PNG)

3. Expanded submenu is not closed on dismissing.
4. layout of homepage flashes on loaded, could be refined

https://user-images.githubusercontent.com/7271329/181754100-30463cb9-a38d-4a18-8582-fc5133cae113.mov

**Comment by Kirl70** [comment]
1.The homepage list of the mobile terminal only needs to list the latest 5 pieces of data.
![image](https://user-images.githubusercontent.com/106060898/182007711-6165dc34-e63c-4e22-aeba-349c68d1211c.png)

2.The text of the navigation bar should change to the theme color when the mouse hovers over the corresponding title.
<img width="2077" alt="image" src="https://user-images.githubusercontent.com/106060898/182007782-6fcd7403-2abe-4fad-ae60-80ebf3d09cc9.png">

**Comment by Keith-CY** [comment]
PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/385

**Comment by FrederLu** [comment]
https://github.com/Magickbase/godwoken_explorer/issues/803#issuecomment-1200388457 
[The second point](https://github.com/Magickbase/godwoken_explorer/issues/803#issuecomment-1200388457 ) here is not implemented on the page.

**Comment by FrederLu** [comment]
The second point [pr](https://github.com/Magickbase/godwoken-explorer-ui/pull/437) in  https://github.com/Magickbase/godwoken_explorer/issues/803#issuecomment-1200388457 is verified.
