### ISSUE TITLE
Update `in/out/self` tag in transaction list and transfer list

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#811]
Design https://github.com/Magickbase/visual-style-guide/issues/3#issuecomment-1196215300

**Comment by Keith-CY** [comment]
Update and please verify in production environment @FrederLu

**Comment by FrederLu** [comment]
1、The [transactions tab](https://v1.gwscan.com/block/0xbd63cf81752d482198055f5f7dbb0a9d852f9524bcd12e55144c1f675af4bd65) in blocks detial is missing the tag.
--------------------------------------------------------------------------------------------------------------------------------
![Image](https://user-images.githubusercontent.com/25676576/183617063-34fdafb2-8512-4369-8969-d81bdf37c15a.png)
![Image](https://user-images.githubusercontent.com/25676576/183617613-09c1b511-b07e-4e9a-afff-ae493d88c67f.png)

--------------------------------------------------------------------------------------------------------------------------------
2、The [transactions list](https://v1.gwscan.com/txs) is missing the tag.
--------------------------------------------------------------------------------------------------------------------------------
![Image](https://user-images.githubusercontent.com/25676576/183618096-d159843f-3dda-40a8-b1ba-bf1d9ea7f3e2.png)
![Image](https://user-images.githubusercontent.com/25676576/183618212-133ffd8e-d4ca-4c9c-9f12-bcd2799d2e72.png)

--------------------------------------------------------------------------------------------------------------------------------
3、The transfers list on the token page([bridge](https://v1.gwscan.com/token/103) and [native](https://v1.gwscan.com/token/103)) is missing the tag.
--------------------------------------------------------------------------------------------------------------------------------
![Image](https://user-images.githubusercontent.com/25676576/183620551-db3a54bb-b8f3-46e8-9f0a-98fe51b434a7.png)
![Image](https://user-images.githubusercontent.com/25676576/183620706-5a2b3034-b863-477d-a866-7ffb96127d56.png)

--------------------------------------------------------------------------------------------------------------------------------

**Comment by FrederLu** [comment]
Verified.
