### ISSUE TITLE
Add address QR Code

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#812]
Design https://github.com/Magickbase/visual-style-guide/issues/4#issuecomment-1197615459

**Comment by Keith-CY** [comment]
PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/398

**Comment by FrederLu** [comment]
https://github.com/Magickbase/godwoken_explorer/issues/812#issuecomment-1207434973 pr verified.
