### ISSUE TITLE
 Page data and download file data are abnormal.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#819]
https://v1.gwscan.com/tx/0x047fa79ad5427c5cf43f46f6f908a0f25d9c0bfbe03498bfc391ed6af493a100?tab=erc20

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/25676576/182129685-6384fa97-02ca-4f97-966c-20483b8df249.png">
<img width="940" alt="image" src="https://user-images.githubusercontent.com/25676576/182129865-7fde3715-9294-4bc4-813e-258626051d9d.png">
<img width="891" alt="image" src="https://user-images.githubusercontent.com/25676576/182130199-37f1a2f0-ae65-4e9b-b4ad-d922aab5ea89.png">

1、There is no data in the ERC20Records tab, but there is data in the downloaded ERC20Records file.
2、The downloaded ERC20Records file data does not meet the requirements.

**Comment by Keith-CY** [comment]
Only 1 log is included in this Tx and it's not an erc20 transfer. Is it a bug that if `no records are found, all data will be exported`? @zmcNotafraid

**Comment by zmcNotafraid** [comment]
@FrederLu  please check again. I click download button but there is no data to export.

**Comment by FrederLu** [comment]
Verified.
