### ISSUE TITLE
Contract page needs to be optimized.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#834]
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/25676576/183041609-37a2e0b8-4110-46c5-a4f1-f1f1ac6127a5.png">
1、The information behind the topic is not aligned horizontally.

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/25676576/183047556-85a0d09d-5028-4cea-8abc-740a74a27804.png">
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/25676576/183052638-9073cc9e-cecb-43dd-9984-a61b5b19a593.png">
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/25676576/183058242-f88df15f-396c-4e19-b6c4-efc5bd2846d8.png">

polyjuice creator account: https://godwoken-explorer-ui-git-refine-account-page-nervosnet.vercel.app/account/0x829cc5785a4d8ac642ede32cb3cb5cb9dc389d5892f2fc2afc760691445be194
sudt account: https://godwoken-explorer-ui-git-refine-account-page-nervosnet.vercel.app/account/0x3e1301e759261b676ce68d0d97936cd431a4af2a34072aa94e44655909765eb4
meta contract account: https://godwoken-explorer-ui-git-refine-account-page-nervosnet.vercel.app/account/0x946d08cc356c4fe13bc49929f1f709611fe0a2aaa336efb579dad4ca197d1551?search=0x946d08cc356c4fe13bc49929f1f709611fe0a2aaa336efb579dad4ca197d1551

2、Polyjuice Creator Account、Bridged Token Account、Meta Contract Account click to download has no effect, it is recommended to hide it.

**Comment by Keith-CY** [comment]
Please verify in production environment

**Comment by FrederLu** [comment]
Questions 1 and 3 are verified on mainnet;
**Question 2 needs to be looked at again;**
