### ISSUE TITLE
[Feature Request] return bridged udt id in response of native udt

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#837]
Now we can only visit a bridge token page by its native token id, which leads to an error that `bridged records` requires the bridge token id, but it's not returned by API.

There're two solutions

1. return bridged token info on querying a native token
2. bridged records API accepts native token id and return its bridged one's data

**Comment by zmcNotafraid** [comment]
All udt I return it's native record in purpose.So I will choose solution 2 for resolve this bug.

**Comment by Keith-CY** [comment]
> All udt I return it's native record in purpose.So I will choose solution 2 for resolve this bug.

Same idea, as bridged token and native token point to the same one asset, they should share data.

**Comment by Keith-CY** [comment]
PR: https://github.com/Magickbase/godwoken_explorer/pull/843

**Comment by FrederLu** [comment]
Testnet verified.

**Comment by FrederLu** [comment]
Production environment verified.
