### ISSUE TITLE
StableKoi's official site and description is missing

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#838]
![image](https://user-images.githubusercontent.com/7271329/183257318-88d884af-6507-46ca-bdf9-07bdee1a90d2.png)
Since we can only visit a bridged token via its native token id, `official site` and `description` should be synchronized for the native one

**Comment by Keith-CY** [comment]
I've update the description and official site of KOI's native token

**Comment by Naupio** [comment]
fix https://github.com/Magickbase/godwoken_explorer/pull/849/commits/c1697c66f99ffb5161eec62c6d045c33acc584f7

**Comment by Naupio** [comment]
env: testnet-stg
example:
```graphql
    query {
      udt(
        input: { id: 36050 }
      ) {
        id
        name
        description
        official_site
        script_hash
        contract_address_hash
      }
    }
```

```
{
  "data": {
    "udt": {
      "contract_address_hash": "0x2275afe815de66beabe7a2c03005537ab843afb2",
      "description": "The sUDT_ERC20_Proxy of Godwoken Test Token.",
      "id": 36050,
      "name": "GodwokenToken on testnet_v1(via Force Bridge from CKB)",
      "official_site": null,
      "script_hash": null
    }
  }
}
```

**Comment by FrederLu** [comment]
testnet-stg verified.

**Comment by Naupio** [comment]
@FrederLu  testnet-prod was published

**Comment by FrederLu** [comment]
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/25676576/184794576-5bb291ba-cc0f-4970-a1f1-fa75649ecf7f.png">
testnet-prod verified.
