### ISSUE TITLE
Token name/token symbol  in search field

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#839]
The rule to match a token is not clear yet, so `token name/token symbol` is removed from the prompt of the search input.

Case 1. search `USDC` redirects to a `USDC (via Celer cBridge from ETH)`, but there're many USDCs, why the one bridged from celer is effective;
Case 2. search `pCKB (via Godwoken Bridge from CKB)` redirects to 404, but it exists;
Case 3. search `pCKB.gw|gb.ckb` returns 404, but it exists.

Since there could be many tokens having the same name or symbol, we should remove searching token in the search field and use `fuzzy search` in the token list page.

**Comment by Keith-CY** [comment]
Or we can redirect to page with filter query as https://v1.gwscan.com/tokens/bridge?type=bridge&name=usdc

**Comment by zmcNotafraid** [comment]
Current we only query with full match  for name or symbol. And if match multiple results, we return 404.
For case 1, USDC only match this one result. other usdc udt's symbol is like this: "USDC.gw|gb.ckb|fb.eth", so not match.
For case 2, the query match two result, one is bridge token, the other is it's natvie token.
For case 3, it's same as above situation.

**Comment by Keith-CY** [comment]
> Current we only query with full match for name or symbol. And if match multiple results, we return 404. For case 1, USDC only match this one result. other usdc udt's symbol is like this: "USDC.gw|gb.ckb|fb.eth", so not match. For case 2, the query match two result, one is bridge token, the other is it's natvie token. For case 3, it's same as above situation.

For the first case, if there're more than 1 token having symbol `USDC`, we still don't know which one to go.

For the second and third cases, there're two token hit but the page is redirected to 404, it's weird.

I think all problems come from that multiple records will be hit by `name` or `symbol` and recommend using the filter in the token list page, as when `usdc` is used in a search keyword, we should redirect the page to [v1.gwscan.com/tokens/bridge?name=usdc](https://v1.gwscan.com/tokens/bridge?name=usdc) and all related tokens will be listed.

**Comment by Keith-CY** [comment]
PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/420

**Comment by FrederLu** [comment]
Each bridge token will map a native token, so it will eventually jump to the native token page, if it does not exist, display No Records.
Verifief.
