### ISSUE TITLE
[UI] Add NFT pages

### ISSUE THREAD

**Issue by qiweiii** [Magickbase/godwoken_explorer#840]
https://github.com/Magickbase/visual-style-guide/issues/5#issuecomment-1202107154

- [ ] nft collection list, 1d, @Keith-CY https://github.com/Magickbase/godwoken-explorer-ui/pull/431
- [ ] nft details page
    - [ ] overall layout, requests, basic info 1d, @Keith-CY https://github.com/Magickbase/godwoken-explorer-ui/pull/431
    - [ ] nft detail activity list component, 1.5d, @Keith-CY https://github.com/Magickbase/godwoken-explorer-ui/pull/476
    - [ ] nft detail holders list, 0.5d, @qiweiii, https://github.com/Magickbase/godwoken-explorer-ui/pull/441
    - [ ] nft detail inventory list component, 1.5d, @qiweiii, https://github.com/Magickbase/godwoken-explorer-ui/pull/441
- [ ] nft item detail page, 2.5d, @qiweiii
    - [ ] overall layout, requests, basic info, https://github.com/Magickbase/godwoken-explorer-ui/pull/441
    - [ ] activity list (reuse activity list component)
- [ ] user account details page's nft tab (reuse inventory list component), 0.5d, @qiweiii

**Comment by Keith-CY** [comment]
Base branch https://github.com/Magickbase/godwoken-explorer-ui/tree/erc-721

**Comment by Keith-CY** [comment]
All are done except functions of filter/sort
