### ISSUE TITLE
Holders in token list is incorrect

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#842]
https://v1.gwscan.com/tokens/native?type=native&after=g3QAAAABZAAEbmFtZW0AAAAhV0JUQyAodmlhIENlbGVyIGNCcmlkZ2UgZnJvbSBFVEgp

In this list, all `YokaiSwap LP`s have 0 holders but they do have when visit their detail page

Besides, `YOK` in bridged token list(https://v1.gwscan.com/tokens/bridge?type=bridge&name=YOK) has **2615** holders, `YOK` in native token detail page(https://v1.gwscan.com/token/133) has **670** holders, but `YOK` in native token list(https://v1.gwscan.com/tokens/native?type=native&after=g3QAAAABZAAEbmFtZW0AAAAhV0JUQyAodmlhIENlbGVyIGNCcmlkZ2UgZnJvbSBFVEgp&name=YOK) has **0** holders, data are not synchronized in three APIs.

**Comment by zmcNotafraid** [comment]
```
  def count_holder(udt_id) do
    from(cbub in CurrentBridgedUDTBalance, where: cbub.udt_id == ^udt_id)
    |> Repo.aggregate(:count)
  end
```
should use CurrentUDTBalance  @Naupio

**Comment by Naupio** [comment]
env: testnet-stg

example
```
    query {
      udt(
        input: { id: 36050 }
      ) {
        id
        holders_count
        name
        description
        official_site
        script_hash
        contract_address_hash
      }
    }
```

```
{
  "data": {
    "udt": {
      "contract_address_hash": "0x2275afe815de66beabe7a2c03005537ab843afb2",
      "description": "The sUDT_ERC20_Proxy of Godwoken Test Token.",
      "holders_count": 12,
      "id": 36050,
      "name": "GodwokenToken on testnet_v1(via Force Bridge from CKB)",
      "official_site": null,
      "script_hash": null
    }
  }
}
```

**Comment by Naupio** [comment]
@FrederLu  please testing it on testnet-stg env and testnet-prod env

**Comment by FrederLu** [comment]
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/25676576/184794735-47cf3b7d-7bb0-4df4-8404-f12a8546bf3e.png">
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/25676576/184794831-bbcf6ef8-bb20-4ec5-b66f-aca3b22c2941.png">

testnet-stg env and testnet-prod env verified.
