### ISSUE TITLE
The page prompts that no information was found.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#845]
The page https://v1.gwscan.com/block/4041 Clicking on Bridged Transfers and Raw Data will display the information page not found, and the graphql interface has data.
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/25676576/183408255-4a1ad453-b76e-42f8-878f-26ebc8b0bf77.png">

**Comment by Keith-CY** [comment]
It should be fixed in production environments

**Comment by FrederLu** [comment]
Verified.
