### ISSUE TITLE
The bridge token detial type is displayed incorrectly.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#846]
<img width="642" alt="image" src="https://user-images.githubusercontent.com/25676576/183408794-27668c94-726e-4f09-b98d-36aa526f2b91.png">

The type in the token detial accessed through `bridge token list` should show `bridge`.

**Comment by Keith-CY** [comment]
A tooltip with text `view mapped native token` is added in PR https://github.com/Magickbase/godwoken-explorer-ui/pull/417

**Comment by FrederLu** [comment]
The test environment lacks corresponding data, and it is verified online.
