### ISSUE TITLE
 The contract account events tab has no data.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#847]
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/25676576/183411784-2cbb2048-3d14-4bb8-9c6d-74775ef908a6.png">

There is no data under the [contract account](https://v1.gwscan.com/account/0xf4b5cd842e1962ca5b59327fe4bbf5b845c18669?tab=events) events tab.

**Comment by Keith-CY** [comment]
This contract doesn't have event logs on chain
