### ISSUE TITLE
Token Approval Tool

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#853]
https://user-images.githubusercontent.com/7271329/183792631-f4940627-8ab7-4a0b-9a37-aa32cd469669.mp4
https://etherscan.io/tokenapprovalchecker

- list all approved erc20/erc721/erc1155
    - Tx Hash
    - Last Updated Time
    - Token Name(symbol, id)
    - Token Type
    - Approved Type
    - Approved spender

**Comment by zmcNotafraid** [comment]
For erc20, have  `event Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)`
For erc721, have 
```
  event Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
  event ApprovalForAll(address indexed owner, address indexed operator, bool approved)
```
For erc1155, have   `event ApprovalForAll(address indexed owner, address indexed operator, bool approved)`

**Comment by Keith-CY** [comment]
Backend PR: https://github.com/Magickbase/godwoken_explorer/pull/870

**Comment by Keith-CY** [comment]
Deploy a ERC 721 on testnet

**Comment by Keith-CY** [comment]
I've added a new field named `Approved Type` next to `Token Type` which could be `approve`, `approve for all` etc. for broader use cases. Please update it in the Design @Kirl70

**Comment by Kirl70** [comment]
Design draft:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=4131%3A20601
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/106060898/185073941-9945b428-77d5-4336-9a09-7e0ddd5b3a7c.png">

**Comment by qiweiii** [comment]
Currently, seems API need to specify token_type when sending query

```
enum TokenType {
  ERC1155
  ERC20
  ERC721
}
```

But in design, all token types are in one list, that means I need to send 3 request to get the list, and pagination can be weired.

Maybe we should change the ui design to allow switch tabs under Token Approval (like etherscan), or maybe change API to return a list ordered by token_type according to design

**Comment by Keith-CY** [comment]
> Currently, seems API need to specify token_type when sending query
> 
> ```
> enum TokenType {
>   ERC1155
>   ERC20
>   ERC721
> }
> ```
> 
> But in design, all token types are in one list, that means I need to send 3 request to get the list, and pagination can be weired.
> 
> Maybe we should change the ui design to allow switch tabs under Token Approval (like etherscan), or maybe change API to return a list ordered by token_type according to design

All in one is fine for now because a user won't approve too many contracts(it's a dangerous action).

And graphql supports combining multiple queries into one like
```
query() {
  data_1 {}
  data_2 {}
  data_3 {}
}
```

**Comment by qiweiii** [comment]
Questions about the sorters and filters:

`TokenApprovalsSorter` in API seems not we we need

```ts
enum TokenApprovalsSorter {
  BLOCK_NUMBER
  ID
}
```

From design, we need 3 sorters:
![Image](https://user-images.githubusercontent.com/32790369/187192618-60702b92-4bf7-4b5c-a184-a616d01173bf.png)

Also, filter/query by asset seems not supported in API

**Comment by Keith-CY** [comment]
> Questions about the sorters and filters:
> 
> `TokenApprovalsSorter` in API seems not we we need
> 
> ```ts
> enum TokenApprovalsSorter {
>   BLOCK_NUMBER
>   ID
> }
> ```
> 
> From design, we need 3 sorters: ![Image](https://user-images.githubusercontent.com/32790369/187192618-60702b92-4bf7-4b5c-a184-a616d01173bf.png)
> 
> Also, filter/query by asset seems not supported in API

We can leave fitlers/sorters for now since devs don't have enough time for that.

**Comment by Keith-CY** [comment]
How is it going @qiweiii

**Comment by qiweiii** [comment]
> How is it going @qiweiii 

Having a holiday now, hopefully will be done by next week

**Comment by Keith-CY** [comment]
> > How is it going @qiweiii
> 
> Having a holiday now, hopefully will be done by next week

Got it

**Comment by qiweiii** [comment]
Frontend PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/533

**Comment by FrederLu** [comment]
What is the difference between token approval under User Account and the operation of token add to MetaMask on the token page? Is there a relationship between the two?

**Comment by Keith-CY** [comment]
> What is the difference between token approval under User Account and the operation of token add to MetaMask on the token page? Is there a relationship between the two?

They are two independent features:

1. `Token Approval Tools` is used to list all approval actions of an account, and allow the owner to revoke unexpected approvals.

    An approval action is a transaction calling `approve` or `approveForAll` method of ERC20/721/1155 contracts, this action is dangerous because it grants `approved spender` to send assets of the owner without restriction, and is generally used in defi protocols.
    
2. `Add token to MetaMask` is just a shortcut to import token info(name, symbol, decimal, contract address) to MetaMask so its balance will be revealed in MetaMask, it's just an token registration off-chain and has nothing to do with on-chain state.

**Comment by FrederLu** [comment]
>>What is the difference between token approval under User Account and the operation of token add to MetaMask on the token >>page? Is there a relationship between the two?
>
>They are two independent features:
>
>Token Approval Tools is used to list all approval actions of an account, and allow the owner to revoke unexpected approvals.
>
>An approval action is a transaction calling approve or approveForAll method of ERC20/721/1155 contracts, this action is dangerous because it grants approved spender to send assets of the owner without restriction, and is generally used in defi protocols.
>
>Add token to MetaMask is just a shortcut to import token info(name, symbol, decimal, contract address) to MetaMask so its balance will be revealed in MetaMask, it's just a token registration off-chain and has nothing to do with on-chain state.

Ok,got it.

**Comment by FrederLu** [comment]
Association problem https://github.com/Magickbase/godwoken_explorer/issues/1030
