### ISSUE TITLE
Research importing token info into MetaMask

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#858]
### Etherscan
Visit a token page(https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7) and click on `More` at the top right corner then expand menu which includes `Add Token to MetaMask(Web3)`

![image](https://user-images.githubusercontent.com/7271329/185086179-748ab8d8-8c74-4b5a-8320-efe37092f8b4.png)

MetaMask will pop a dialog to confirm
![image](https://user-images.githubusercontent.com/7271329/185086308-98e528ae-7dc7-4b37-b3a9-8ebf8cec04a4.png)

### Blockscout

Doesn't support importing a token

### Coinmarketcap

Click the MetaMask icon to import token into MetaMask
![image](https://user-images.githubusercontent.com/7271329/185092379-e38a405b-9dbb-40cc-8fc1-9f3910cbbbbd.png)

**Comment by Keith-CY** [comment]
GwScan will also support importing tokens into MetaMask on the token detail page(https://v1.gwscan.com/token/192).

Besides, a `submit` link to [Submit a native token](https://github.com/Magickbase/godwoken_explorer/issues/new?assignees=Keith-CY&labels=Token+Registration&template=register-a-new-native-erc20-token.yml&title=%5BNative+ERC20+Token%5D+%2A%2ADisplay+Name%2A%2A) should be added to register off-chain info, such as `UAN`, official website, description of the token.

I think the icon of MetaMask is quite clear for users, how do you think about it @Kirl70 @FrederLu @qiweiii

**Comment by qiweiii** [comment]
MetaMask icon sounds good!

**Comment by qiweiii** [comment]
Are these what we are going to call:
- https://docs.metamask.io/guide/registering-your-token.html#code-free-example
- https://github.com/ethereum/EIPs/blob/master/EIPS/eip-747.md

**Comment by Kirl70** [comment]
So now, do I need to update the draft to `Add Token to MetaMask` button and a `Submit a native token` button to the token details page ?

**Comment by FrederLu** [comment]
<img width="723" alt="image" src="https://user-images.githubusercontent.com/25676576/185275416-61656651-0037-41f5-a999-2231262207b0.png">

I think the icon of MetaMask is good. The MetaMask entry on the screenshot should be more user-friendly if it is placed in a prominent position.

**Comment by Keith-CY** [comment]
> Are these what we are going to call:
> 
> * [docs.metamask.io/guide/registering-your-token.html#code-free-example](https://docs.metamask.io/guide/registering-your-token.html#code-free-example)
> * [https://github.com/ethereum/EIPs/blob/master/EIPS/eip-747.md](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-747.md?rgh-link-date=2022-08-18T01%3A13%3A53Z)

Cool, that's the method we should call to import a token into MetaMask

**Comment by Keith-CY** [comment]
> So now, do I need to update the design draft to `Add Token to MetaMask` button and a `Submit a native token` button to the token details page ?

Yes, I think it's better to add these two buttons(for importing into MetaMask, and submitting off-chain info) on the token detail page, just as we will add two buttons(for verifying the contract and add off-chain information) on the contract detail page (https://github.com/Magickbase/godwoken_explorer/issues/873)

But on a specific page we can rename `submit a native token` to `add token info` because now tokens are recognized automatically and users don't have to submit again.

**Comment by Keith-CY** [comment]
> <img alt="image" width="723" src="https://user-images.githubusercontent.com/25676576/185275416-61656651-0037-41f5-a999-2231262207b0.png">
> 
> I think the icon of MetaMask is good. The MetaMask entry on the screenshot should be more user-friendly if it is placed in a prominent position.

I do think so, `MetaMask` is quite outstanding for a ethereum user

**Comment by Kirl70** [comment]
The design draft has been adjusted, because it is impossible to tell whether MetaMask has added this token, so the icon of MetaMask will always remain in the same position.

Unregistered
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=67%3A910
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/106060898/185364837-3357a57b-4130-4ae0-b3f7-2990ea386ce1.png">

Information has been submitted
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=67%3A1728
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/106060898/185364907-9d1e6a98-3a05-49c9-8483-89ea45aafef5.png">

**Comment by Keith-CY** [comment]
Front-end PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/520
