### ISSUE TITLE
Update style of amount/value

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#861]
1. fraction(with dot)
  - #938dac for mainnet
  - #8f9fb8 for testnet
2. set font weight 500

![image](https://user-images.githubusercontent.com/7271329/184103638-e1ce312a-1503-4586-9112-7d0875c7ad21.png)

https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU?node-id=6:920#245034837

**Comment by Keith-CY** [comment]
PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/436

**Comment by FrederLu** [comment]
The color number on testnet is wrong, it should be #8f9fb8, now it is #8f8fb8.

![Image](https://user-images.githubusercontent.com/25676576/184303023-772d8a80-e870-4a9f-85af-2fd79bf6c768.png)

**Comment by Keith-CY** [comment]
> The color number on testnet is wrong, it should be #8f9fb8, now it is #8f8fb8.
> 
> ![Image](https://user-images.githubusercontent.com/25676576/184303023-772d8a80-e870-4a9f-85af-2fd79bf6c768.png)

Sorry for that, it is fixed https://github.com/Magickbase/godwoken-explorer-ui/pull/436/files#diff-6fe0960f6b27eeb64b9353c548799e22d57fb11f05e2347f75501516b4838fd5R26 and is being deployed

**Comment by FrederLu** [comment]
https://github.com/Magickbase/godwoken_explorer/issues/861#issuecomment-1212806287 verified.
