### ISSUE TITLE
Some user experience adjustments

### ISSUE THREAD

**Issue by Kirl70** [Magickbase/godwoken_explorer#862]
1. Change the text color of the input box under this label to #333333.

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/106060898/184270786-676a38c1-cda6-4865-b900-6119892b6ead.png">

2. The design draft supplements the style of the prompt.

https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=3049%3A19069
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/106060898/184272890-13e9381e-2586-44ee-85bc-6d6da0043ed2.png">

replace existing style
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/106060898/184270882-f65f23d6-ec55-400a-b96b-33a69074c87a.png">

3. The text in the page that can be clicked to jump to the new page should be the main color.

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/106060898/184273733-92342c7b-8eef-4801-a602-0f98604e5d2a.png">

4. If there is no data in the list, the bottom content should not appear.

<img width="1258" alt="image" src="https://user-images.githubusercontent.com/106060898/184274178-9ca117fd-4279-4270-a052-0ae03d04d130.png">

5. In the list with one token and two tokens superimposed, you need to adjust the position where the two tokens are superimposed. The purpose of this is to align the token names for visual balance.
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=67%3A2195
<img width="249" alt="image" src="https://user-images.githubusercontent.com/106060898/184276519-d793a0c2-377e-4df5-8f50-66296ce274c6.png">

Before:
<img width="131" alt="image" src="https://user-images.githubusercontent.com/106060898/184276717-4c80c715-d81e-4c7f-bf94-ab6bd740518e.png">

**Comment by Keith-CY** [comment]
I'll fix 1, 3, 5

4 should be fixed by https://github.com/Magickbase/godwoken-explorer-ui/pull/417

@qiweiii please check 2

**Comment by FrederLu** [comment]
4-10 in https://github.com/Magickbase/godwoken_explorer/issues/862#issuecomment-1212697971 need to be verified in the pro environment.
