### ISSUE TITLE
`Static Call` method in contract page

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#864]
There's another feature added but I missed it in https://github.com/Magickbase/visual-style-guide/issues/3

A contract usually has two kinds of methods: `read` and `write`.

`Read method` will only call a reading method that not updates the state of a contract while `Write method` will change the state of a contract(require a signature from wallet)

But ethereum node now allows `write method` to be called without a signature, which is named `static call` or `call static`, this usage is usually for checking contract logic or estimating gas that will be consumed in the transaction, or calling some write-marked `read method`(if assembly is used).

So in the `read contract` panel, we introduced the `write method` and allow users to invoke them without signing, as the `totalSupply` method in https://v1.gwscan.com/account/0x9e858a7aaedf9fdb1026ab1f77f627be2791e98a?tab=contract

I simply grouped them with a title `Call Static`, it's not following out visual guide and should be updated @Kirl70

**Comment by Kirl70** [comment]
In order to unify the page, a title needs to be added to the upper part, and a title needs to be added to the write operation, Design draft:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=118%3A2230
<img width="826" alt="image" src="https://user-images.githubusercontent.com/106060898/184567151-fac18431-f5e5-42e6-a781-008171c1d654.png">
<img width="810" alt="image" src="https://user-images.githubusercontent.com/106060898/184567488-f321d266-228d-489e-aa2a-e1bb6d7a9b0e.png">

**Comment by Keith-CY** [comment]
PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/450

**Comment by FrederLu** [comment]
![Image](https://user-images.githubusercontent.com/25676576/184841147-69e59e2b-a5d4-4ae6-b002-13537ad9d090.png)
https://godwoken-explorer-ui-git-add-title-in-interact-88e9cd-nervosnet.vercel.app/contracts

Access the link, the page prompts an exception.

**Comment by Keith-CY** [comment]
The 3rd contract returned in the API https://api.v1-betanet.gwscan.com/api/smart_contracts?page=1&page_size=50 has no `compiler_file_format`. Not sure if it is from sourcify and is it possible to have `null` compiler_file_format when we detect a contract via sourcify? @Naupio

**Comment by Keith-CY** [comment]
Please verify this function on this page https://godwoken-explorer-ui-git-add-title-in-interact-88e9cd-nervosnet.vercel.app/account/0x2503a1a79a443f3961ee96a8c5ec513638129614?tab=contract because the list is temporarily unavailable

**Comment by FrederLu** [comment]
https://github.com/Magickbase/godwoken_explorer/issues/864#issuecomment-1216353131 verified.
