### ISSUE TITLE
[GwScanV1.4.0] In the pending status of the transaction just sent, the fee is displayed as Nan pckb

### ISSUE THREAD

**Issue by Dawn-githup** [Magickbase/godwoken_explorer#869]
## **Version**
Godwoken mainnet Scan

![image](https://user-images.githubusercontent.com/77844990/184654101-385e9155-7987-4cce-8ca1-30c538df5828.png)

**Comment by Keith-CY** [comment]
`Gas used` is missing in this transaction, please append the tx hash for further debug @Dawn-githup

**Comment by Dawn-githup** [comment]
> `Gas used` is missing in this transaction, please append the tx hash for further debug @Dawn-githup

https://v1.gwscan.com/tx/0xc3bff6ca23619dc6fc0254947f3d6fe2aae47745b0d54dd289d300b5c4f82fc8?search=0xc3bff6ca23619dc6fc0254947f3d6fe2aae47745b0d54dd289d300b5c4f82fc8

**Comment by Keith-CY** [comment]
It's been fixed by https://github.com/Magickbase/godwoken-explorer-ui/commit/89426a32c1251e1c692a445bd48ea5e37c704d85, `gas used` and `fee` will be concealed when the transaction is not determined because execution of the transaction is not finished.

**Comment by Dawn-githup** [comment]
> Failed transaction transaction fee shows NaN
https://v1.gwscan.com/zh-CN/tx/0x1500eb68ed1e51f779c37f0daa1417289e967fce0bbd94e477a2bf72feb8781f

**Comment by Keith-CY** [comment]
> > Failed transaction transaction fee shows NaN
> > [v1.gwscan.com/zh-CN/tx/0x1500eb68ed1e51f779c37f0daa1417289e967fce0bbd94e477a2bf72feb8781f](https://v1.gwscan.com/zh-CN/tx/0x1500eb68ed1e51f779c37f0daa1417289e967fce0bbd94e477a2bf72feb8781f)

Please check again, it could be cached because fee is properly displayed when I visit the page
