### ISSUE TITLE
Add `verify` and `register` buttons in contract account page

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#873]
Now contracts on godwoken are verified by submitting a form in GitHub, so there's a link to GitHub issue on the contract detail page
![image](https://user-images.githubusercontent.com/7271329/185094413-f84a84c6-df86-49db-ad4d-992042d7bfad.png)

With the integration of sourcify delivered(https://github.com/Magickbase/godwoken_explorer/issues/650), users should be led to https://sourcify.dev/#/verifier to verify contracts.

Now the workflow would be like this:
1. User submits a transaction to deploy a contract
2. GwScan recognized the contract and its detail page could be visited with three links(buttons)
	1. `verify by sourcify`: link to sourcify(https://sourcify.dev/#/verifier) for source code verification
	2. `has been verified by sourcify, check again`: button to trigger a double-check when the contract has been verified in sourcify
	3. `register`: link to [github issue](https://github.com/Magickbase/godwoken_explorer/issues/new?assignees=Keith-CY&labels=Contract+Registration&template=register-a-general-contract.yml&title=%5BGeneral+Contract%5D+%2A%2AContract+Name%2A%2A) to add off-chain info, such as official website, description

Once the contract has been verified in sourcify and the `double-check` has been triggered too, the whole flow of contract verification is done, `verify by sourcify` and `has been verified by sourcify, check again` will be replaced by `look up in sourcify` which leads to https://sourcify.dev/#/lookup

**Comment by Keith-CY** [comment]
A new feature(https://github.com/Magickbase/godwoken_explorer/issues/650) is going to be ready so the workflow of contract verification will be adjusted as above.

Its description might be unclear, feel free to ask any questions @Kirl70 @FrederLu

**Comment by Keith-CY** [comment]
After a second thought I found `verify by sourcify` and `has been verified by sourcify, check again` can be merged into a single button `verify by sourcify`

When a user clicks the button, the `check again` logic could be execute first, if `check again` succeed, everything is fine. If `check again` failed, open [sourcify.dev/#/verifier](https://sourcify.dev/#/verifier) in a new tab, and text of the link turns into `verify again`

**Comment by Kirl70** [comment]
So in the design draft, only need to change the text and color of the button according to the state, right?

Unverified
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/106060898/185274448-f8786c23-3bc0-40ff-85e7-dcb6fca27154.png">

Verification failed
<img width="849" alt="image" src="https://user-images.githubusercontent.com/106060898/185274795-99052973-1784-478c-ab3d-d917729fe680.png">

Verified
<img width="701" alt="image" src="https://user-images.githubusercontent.com/106060898/185274890-e40aca51-8075-4f97-8064-985223177ec0.png">

**Comment by Keith-CY** [comment]
For current functions, it would be enough to change the `verify status` style. But I think we can add another entry for user to submit off-chain info in https://github.com/Magickbase/godwoken_explorer/issues/new?assignees=Keith-CY&labels=Contract+Registration&template=register-a-general-contract.yml&title=%5BGeneral+Contract%5D+%2A%2AContract+Name%2A%2A

Before we integrated sourcify service, the github issue takes two responsibilities

1. require for source code of the contract so we can verify if it's matched
2. require extra info other than source code, such as `constructor arguments`, `other info`

After the sourcify service is integrated, the 1st responsibility is taken by sourcify and the github issue holds the 2nd. one

That's why we'd better have two entries on the page, one to sourcify for verification and one for github to submit extra info

**Comment by Kirl70** [comment]
The design draft adds verification and registration buttons.

Unverified / Unregistered
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=118%3A1409
<img width="891" alt="image" src="https://user-images.githubusercontent.com/106060898/185305293-e63347d1-3924-4994-88cc-67c6de1c1934.png">

Status verified / Information has been submitted
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=118%3A1961
<img width="859" alt="image" src="https://user-images.githubusercontent.com/106060898/185305718-515cf6cd-e64a-4928-b362-3aaaee95f335.png">
