### ISSUE TITLE
Token listings need to limit the number of characters displayed for token names.

### ISSUE THREAD

**Issue by Kirl70** [Magickbase/godwoken_explorer#875]
It is recommended to display up to 24 characters, and the extra ones are represented by ellipses.

https://v1.gwscan.com/tokens/native?type=native&after=g3QAAAABZAAEbmFtZW0AAAAUQnJhaW5pYWMgWU9LLUVUSHxldGg%3D
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/106060898/185583616-da51a0db-6f2a-41e4-b4c9-2e1a3bdad025.png">

**Comment by Keith-CY** [comment]
After some tests I found maximum of 16 characters is suitable https://v1.gwscan.com/tokens/native?type=native&after=g3QAAAABZAAEbmFtZW0AAAAUQnJhaW5pYWMgWU9LLUVUSHxldGg%3D
