### ISSUE TITLE
[Native ERC20 Token] **Display Name**

### ISSUE THREAD

**Issue by dezzyboy** [Magickbase/godwoken_explorer#876]
### display Name

 Jio ForceUSDC/CelUSDC

### Description

Jioswap USD 2pool LP Token (forceBridge USDC ported from ETH + cBridge USDC ported from ETH)

### UAN

jio2USD

### Website

https://jioswap.finance

### Logo URI

https://app.jioswap.finance/static/media/logo.724338c6.svg

### Contract Address

0xb3D6913CF2D6A8fD9b472ff7526ec11620957C8b

### Code Format

solidity standard json input

### Deployment Transaction Hash

0xe6979dc31b6228268db4256c56c5f412b5706b3215865f7406d374d55174a734

### Compiler Version

v0.6.12+commit.27d51765

### Contract Source Code

```shell
link to json file : https://gist.github.com/dezzyboy/879cb8744a43d626db1506e594184d70
```

**Comment by zmcNotafraid** [comment]
Registered at: https://v1.gwscan.com/zh-CN/token/4262
