### ISSUE TITLE
[Native ERC20 Token] **Display Name**

### ISSUE THREAD

**Issue by dezzyboy** [Magickbase/godwoken_explorer#877]
### display Name

Jio CelBUSD/CelDAI/CelUSDC/CelUSDT

### Description

Jioswap celerUSD pool LP Token 

### UAN

jio4celUSD

### Website

https://jioswap.finance

### Logo URI

https://app.jioswap.finance/static/media/logo.724338c6.svg

### Contract Address

0x83f3cff88102f498b7170fbd237935152e6909c7

### Code Format

solidity standard json input

### Deployment Transaction Hash

0x8fb38bd410e09f853b374370c2f0d6b99349bb7a7bb90b52285605d4531e7a86

### Compiler Version

v0.6.12+commit.27d51765

### Contract Source Code

```shell
link to json file : https://gist.github.com/dezzyboy/879cb8744a43d626db1506e594184d70
```

**Comment by zmcNotafraid** [comment]
Registered at: https://v1.gwscan.com/zh-CN/token/4262
