### ISSUE TITLE
Deploy tx hash and deployer address are missing on an verified contract page

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#897]
https://v1.gwscan.com/account/0x885fb612947ccf1c7611894bd828d388b046fc24?tab=contract

![image](https://user-images.githubusercontent.com/7271329/186828175-69962e77-03d2-49c8-9c55-1fcc9ae7d159.png)

**Comment by zmcNotafraid** [comment]
I query from the database this contract doesn't have deployment_tx_hash. So we don't know the info.

**Comment by Keith-CY** [comment]
Information updated
![image](https://user-images.githubusercontent.com/7271329/187133543-c5d19d69-025c-47ff-914b-ec570a877c5c.png)
