### ISSUE TITLE
`gas used` is missing when `polyjuice status` is not `pending`

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#907]
![Pasted Graphic 15](https://user-images.githubusercontent.com/7271329/187151440-98946313-8e98-4e72-b07d-11cdb8bd06d1.png)

**Comment by Keith-CY** [comment]
When `poyjuice status` is `succeed` or `failed` the execution of contract is done and gas used is determined

**Comment by zmcNotafraid** [comment]
I think this transaction is also a pending tx, because it doesn't have block hash and number.

**Comment by Keith-CY** [comment]
> I think this transaction is also a pending tx, because it doesn't have block hash and number.

There should be two kinds of pending transactions

1. transaction in `pending` polyjuice status: `pending polyjuice status` means the contract calls derived from the transaction haven't finished, evm is working so the `result of the transaction` and `gas used` are not determined.
2. transaction not mined in a block: this kind of transaction has finished contract execution, has a determined `contract result`, `gas used`, but is not mined by miners yet.

The case mentioned in this issue is the first type of transaction, it has finished contract execution and should have a determined `gas used`

Correct me if I'm wrong @flouse

**Comment by Flouse** [comment]
> ![Pasted Graphic 15](https://user-images.githubusercontent.com/7271329/187151440-98946313-8e98-4e72-b07d-11cdb8bd06d1.png)

What is the tx_hash of this transaction?
Would you please give us one cURL command?

**Comment by Keith-CY** [comment]
> > ![Pasted Graphic 15](https://user-images.githubusercontent.com/7271329/187151440-98946313-8e98-4e72-b07d-11cdb8bd06d1.png)
> 
> What is the tx_hash of this transaction? Would you please give us one cURL command?

Every transaction goes through the following stages:
1. `pending polyjuice status` + `pending transaction status`
2. `success/failed polyjuice status` + `pending transaction status`
3. `success/failed polyjuice status` + `committed transaction status`

My point is that when a transaction is in stage 2(`success/failed polyjuice status` + `pending transaction status`), the `gas used` has been determined because all `eth call` have been done. But now response from server only reveals `value`, `polyjuice status` but misses `gas used`

**Comment by Flouse** [comment]
> when a transaction is in stage 2(success/failed polyjuice status + pending transaction status), the gas used has been determined

Yes.

**Comment by zmcNotafraid** [comment]
I direct invoke json api, it returns `
polyjuice_status: null,
status: null,
` .So succeed it's not default value

**Comment by Keith-CY** [comment]
Figure out that it's a mistake in front-end where `polyjuice status` has a fallback value of `succeed` which should be `pending`
https://github.com/Magickbase/godwoken-explorer-ui/blob/develop/utils/api/tx.ts#L85

Will be fixed soon

**Comment by Keith-CY** [comment]
Fixed by https://github.com/Magickbase/godwoken-explorer-ui/pull/550

**Comment by Keith-CY** [comment]
![Image](https://user-images.githubusercontent.com/7271329/190938727-0c2af4f0-c151-491b-9a47-34494b85428e.png)
