### ISSUE TITLE
Dismission of alert is delayed but its state is not cached

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#909]
When the `alert` is dismissed, the `type` turns into `success` from `error` because `success` is the default value.

But because there's a latency on disappearing, the `alert` component shows `success` with a blank message temporarily as the video shows

https://user-images.githubusercontent.com/7271329/187182285-15a3099b-e7b7-48df-8ffa-05852e5f8466.mov

I think the state should be held during the progress of disappearance if we want it to exit gradually but not vanish

How do you think about this detail @qiweiii

**Comment by qiweiii** [comment]
Just took a look, seems the default success state is in material-ui.

To solve the problem in video, I tried this and seems it works for [#520](https://github.com/Magickbase/godwoken-explorer-ui/pull/520)

```js
setMsg({ open: true, type: 'error', msg: t('connect-mm-fail') })
```

and Alert

```jsx
<Alert open={msg.open} onClose={() =< setMsg({ open: false }) ... />
```
