### ISSUE TITLE
Check godwoken mainnet accessibility on sourcify

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#915]
Godwoken mainnet has been added by PR(https://github.com/ethereum/sourcify/pull/774) but sill invisible on the `verifier` page(https://sourcify.dev/#/verifier)
![image](https://user-images.githubusercontent.com/7271329/187245022-993062e3-8681-4a0b-9805-74bb89869d77.png)

Has opened an issue(https://github.com/ethereum/sourcify/issues/783) for tracking

Some contracts(https://github.com/Magickbase/godwoken_explorer/issues/912) are blocked by it

**Comment by Keith-CY** [comment]
Will connect to devrel of godwoken if no response by 09/01

**Comment by dezzyboy** [comment]
update : can confirm that mainnet GodwokenV1 is now added to the [verifier](https://sourcify.dev/#/verifier) page 
![Screen Shot 2022-09-02 at 11 14 28 PM](https://user-images.githubusercontent.com/37994033/188253747-403b8138-e021-450e-bd1f-65438b19c03e.png)
