### ISSUE TITLE
Displays an exception message prompt.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#919]
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/25676576/187361057-82d66bbd-efb0-4d73-85d7-d923bd15e0d1.png">

<img width="1371" alt="image" src="https://user-images.githubusercontent.com/25676576/187361024-5abcef3a-077d-4c0f-9974-9d822d2f6361.png">

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/25676576/187360910-e8b9c2a4-e8e0-4ad4-96ea-aa51ec8c44d6.png">

https://godwoken-explorer-plbsw4um6-nervosnet.vercel.app/token/61411
Click the MetaMask icon on the page to complete/cancel the authorization, and an abnormal prompt will appear instantly when the correct prompt information ends.

**Comment by Keith-CY** [comment]
The solution will be discussed and tracked in an issue(https://github.com/Magickbase/godwoken_explorer/issues/909) for optimizing the notification component so I think this one could be closed

**Comment by FrederLu** [comment]
The issue has been tracked in other similar issues.
