### ISSUE TITLE
 Click on metamask to prompt an exception.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken_explorer#928]
<img width="818" alt="image" src="https://user-images.githubusercontent.com/25676576/187653693-778d37be-723f-4242-97c0-d243d47b4fd0.png">

The [online](https://v1.gwscan.com/token/77) token is abnormal, but the [testnet](https://v1.testnet.gwscan.com/token/46408
) is normal.

**Comment by Keith-CY** [comment]
> <img alt="image" width="818" src="https://user-images.githubusercontent.com/25676576/187653693-778d37be-723f-4242-97c0-d243d47b4fd0.png">
> 
> The [online](https://v1.gwscan.com/token/77) token is abnormal, but the [testnet](https://v1.testnet.gwscan.com/token/46408) is normal.

I got this, `UAN`(things like `1INCH.gw|gb.ckb|fb.eth`) is invalid for MetaMask, as it's invalid in ethereum. I'll fix it by only submit `token name` instead of the whole `UAN`

**Comment by Keith-CY** [comment]
Fixed in production environments

Now `1INCH.gw|gb.ckb|fb.eth` will be imported as `1INCH`.

But token which has an invalid symbol will still be prevented by MetaMask, users should add their own alias for those tokens.
![image](https://user-images.githubusercontent.com/7271329/187659756-244b43e1-1423-4f41-a5bc-a3cfffd66742.png)

**Comment by FrederLu** [comment]
1INCH (via Force Bridge from ETH) can now be added, and some tokens will prompt an exception when they are added.

![Image](https://user-images.githubusercontent.com/25676576/188103430-7bc193ef-694f-4859-b8a0-78255b7bb387.png)

![Image](https://user-images.githubusercontent.com/25676576/188102716-cf6b769a-ba41-4ebf-8497-e6b682ad7cca.png)
https://v1.gwscan.com/token/3179

**Comment by Keith-CY** [comment]
> 1INCH (via Force Bridge from ETH) can now be added, and some tokens will prompt an exception when they are added.
> 
> ![Image](https://user-images.githubusercontent.com/25676576/188103430-7bc193ef-694f-4859-b8a0-78255b7bb387.png)
> 
> ![Image](https://user-images.githubusercontent.com/25676576/188102716-cf6b769a-ba41-4ebf-8497-e6b682ad7cca.png) [v1.gwscan.com/token/3179](https://v1.gwscan.com/token/3179)

Yes, `Brainiac-YOK-ETH|eth` is an invalid symbol for MetaMask so users have to import it with a custom symbol

**Comment by FrederLu** [comment]
The prompt character too long is now resolved. There is another type of too long name that needs to be modified by the project party or the user, and the user can also import it manually through MetaMask.
