### ISSUE TITLE
`approveForAll` of ERC 1155 is not recognized

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#930]
ERC 1155 Contract: https://v1.testnet.gwscan.com/account/0x9eae4141f817dd904c01cb145a2e694a8392583b?tab=contract

owner: 0x46a23E25df9A0F6c18729ddA9Ad1aF3b6A131160
approved spender: 0x731fd088a2120ad5934e788f5051d778661106dd
![image](https://user-images.githubusercontent.com/7271329/187882050-7eee37ef-a48c-4fcc-94af-f597f8b8c6d9.png)
![image](https://user-images.githubusercontent.com/7271329/187882139-e57338ba-d070-45c7-94a5-5b7199437f3c.png)

query
```graphql
query {
	erc20: token_approvals (input:{address: "0x46a23E25df9A0F6c18729ddA9Ad1aF3b6A131160", token_type: ERC20}) {
		entries{
			approved
			token_contract_address_hash
			type
			block {
				number
				timestamp
			}
		}
	}
		erc721:token_approvals (input:{address: "0x46a23E25df9A0F6c18729ddA9Ad1aF3b6A131160", token_type: ERC721}) {
		entries{
			approved
			token_contract_address_hash
      type
			block {
				number
				timestamp
			}
		}
	},
	erc1155:token_approvals(input:{address:"0x46a23E25df9A0F6c18729ddA9Ad1aF3b6A131160", token_type: ERC1155}){
		entries{
			approved
			token_contract_address_hash
			type
			block{
				number
				timestamp
			}
		}
	}
}
```

**Comment by zmcNotafraid** [comment]
Because we use inner join udt of this record.But we can't found this udt in udt table.

**Comment by Keith-CY** [comment]
> Because we use inner join udt of this record.But we can't found this udt in udt table.

Got it, we need wait for the erc 721/1155 to merge

Ref: 
- https://github.com/Magickbase/godwoken_explorer/issues/689
- https://github.com/Magickbase/godwoken_explorer/issues/854

**Comment by zmcNotafraid** [comment]
> > Because we use inner join udt of this record.But we can't found this udt in udt table.
> 
> Got it, we need wait for the erc 1155 to merge
> 
> Ref:
> 
> * [Support ERC 1155 #854](https://github.com/Magickbase/godwoken_explorer/issues/854)

Current we import udt ony they have transfer transactions. But this contract have no transfer transaction.

**Comment by Keith-CY** [comment]
> > > Because we use inner join udt of this record.But we can't found this udt in udt table.
> > 
> > 
> > Got it, we need wait for the erc 1155 to merge
> > Ref:
> > 
> > * [Support ERC 1155 #854](https://github.com/Magickbase/godwoken_explorer/issues/854)
> 
> Current we import udt ony they have transfer transactions. But this contract have no transfer transaction.

So the approval will not be recorded if I empower someone to spend all my tokens before I get one. This case should be considered.
