### ISSUE TITLE
[Native ERC20 Token] **Token Name**

### ISSUE THREAD

**Issue by specmeup** [Magickbase/godwoken_explorer#934]
### Token Name

$OVUM

### Description

The 1st "meme" project on the  NERVOS NETWORK

### Max Supply

1,000,000,000

### Website

eggsly.fun

### Logo URI

https://ibb.co/YTvdchy

### Contract Address

 0xc883765768ec7f6816fa17f944610613b7a6159f

### Code Format

solidity standard json input

### Deployment Transaction Hash

0x5e701ab2cb65583d1cea64b7020f9e8766e0a39285e6d9179db2945b4eb50a14

### Compiler Version

v0.8.11+commit.d7f03943

### Contract Source Code

{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "hash": "0x5e701ab2cb65583d1cea64b7020f9e8766e0a39285e6d9179db2945b4eb50a14",
    "blockHash": "0x34cee8301a465946ccea9f7667a9329f8ae6a71baa847a05e9841f2caa1abc9e",
    "blockNumber": "0x13799",
    "transactionIndex": "0x0",
    "from": "0x6289e12cbe76382b7c1d1d5c6b296214674c1091",
    "to": "0x8b0591c77f8acfddbf4d05db2fa72ccf90190f21",
    "gas": "0x46065",
    "gasPrice": "0x246139ca8000",
    "input": "0x4457d5f0000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000033b2e3c9fd0803ce80000000000000000000000000000006289e12cbe76382b7c1d1d5c6b296214674c10910000000000000000000000000000000000000000000000000000000000000006454747534c59000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044f56554d00000000000000000000000000000000000000000000000000000000",
    "nonce": "0x2b",
    "value": "0x0",
    "v": "0x0",
    "r": "0x4692de69ad2356429ea3fc169f3008017a7f5a49962fd7352110008909f21f4c",
    "s": "0x2a9d6a9b81896c5aa8ebaf005a351245991bd5c89183c31e284757ee3012e9c5"
  }
}

**Comment by Keith-CY** [comment]
Hi @specmeup 

Off-chain info(logo, description, official website) has been updated and can be viewed on https://v1.gwscan.com/token/3880

The source code provided above is incorrect, so it's not been updated.

BTW we're using [sourcify](https://sourcify.dev/#/verifier) to verify contracts now, with that the verification info will be shared among https://gwscan.com and [community explorer](https://gw-mainnet-explorer.nervosdao.community/)
