### ISSUE TITLE
`To` in native transfer transaction is incorrect

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#945]
![image](https://user-images.githubusercontent.com/7271329/188615659-c9e3949e-fcae-4f96-86f5-e4f3fe6fa78f.png)

`To` in the response of RPC is `0x715ab282b873b79a7be8b0e8c13c4e8966a52040` while address of `Deploy Contract` is `0x829cc5785a4d8ac642ede32cb3cb5cb9dc389d5892f2fc2afc760691445be194`

**Comment by zmcNotafraid** [comment]
We can found that input data is  really user account address

**Comment by Dawn-githup** [comment]
![image](https://user-images.githubusercontent.com/77844990/189066960-4e37ab03-a41e-4524-885f-f3103ac34294.png)
>> https://v1.betanet.gwscan.com/zh-CN/tx/0x69f63e4d97d90c18ff8d3411082cf201cfc077d5321a293da201db4319e6e286?search=0x69f63e4d97d90c18ff8d3411082cf201cfc077d5321a293da201db4319e6e286

**Comment by Keith-CY** [comment]
> ![image](https://user-images.githubusercontent.com/77844990/189066960-4e37ab03-a41e-4524-885f-f3103ac34294.png)
> 
> > > [v1.betanet.gwscan.com/zh-CN/tx/0x69f63e4d97d90c18ff8d3411082cf201cfc077d5321a293da201db4319e6e286?search=0x69f63e4d97d90c18ff8d3411082cf201cfc077d5321a293da201db4319e6e286](https://v1.betanet.gwscan.com/zh-CN/tx/0x69f63e4d97d90c18ff8d3411082cf201cfc077d5321a293da201db4319e6e286?search=0x69f63e4d97d90c18ff8d3411082cf201cfc077d5321a293da201db4319e6e286)

We will decode this kind of transaction from `args` of `gw transaction`

In this case, the `args` of `gw transaction` is `0xffffff504f4c5900405489000000000001e40b540200000000000000000000000000f444829163450000000000000000000000000000000000000000000000000000000000000007`, means it's a native transfer to `0x0000000000000000000000000000000000000007` with value `0xf44482916345000000000000000000000000`(little-endian)

**Comment by zmcNotafraid** [comment]
I add a `native_transfer_address_hash` attribute for native transfer.Such as: https://api.v1-betanet.gwscan.com/api/txs/0xd701f687d0f814de7e3d75f3665fa277ea174da243fa4d2938cedba7b864787d
@Keith-CY

**Comment by Keith-CY** [comment]
`native_transfer_address_hash` in graphql api is incorrect
![image](https://user-images.githubusercontent.com/7271329/190921799-52f78f75-4836-4be8-aff7-6ba4e01b3209.png)
queried with `hash `0xd701f687d0f814de7e3d75f3665fa277ea174da243fa4d2938cedba7b864787d` and json api returned `native_transfer_address_hash`

**Comment by zmcNotafraid** [comment]
> `native_transfer_address_hash` in graphql api is incorrect ![image](https://user-images.githubusercontent.com/7271329/190921799-52f78f75-4836-4be8-aff7-6ba4e01b3209.png) queried with `hash = 0xd701f687d0f814de7e3d75f3665fa277ea174da243fa4d2938cedba7b864787d` and json api returned `native_transfer_address_hash`

Data have fixed

**Comment by Keith-CY** [comment]
> > `native_transfer_address_hash` in graphql api is incorrect ![image](https://user-images.githubusercontent.com/7271329/190921799-52f78f75-4836-4be8-aff7-6ba4e01b3209.png) queried with `hash = 0xd701f687d0f814de7e3d75f3665fa277ea174da243fa4d2938cedba7b864787d` and json api returned `native_transfer_address_hash`
> 
> Data have fixed

Still get `null` in testnet prod

**Comment by Keith-CY** [comment]
> > > `native_transfer_address_hash` in graphql api is incorrect ![image](https://user-images.githubusercontent.com/7271329/190921799-52f78f75-4836-4be8-aff7-6ba4e01b3209.png) queried with `hash = 0xd701f687d0f814de7e3d75f3665fa277ea174da243fa4d2938cedba7b864787d` and json api returned `native_transfer_address_hash`
> > 
> > 
> > Data have fixed
> 
> Still get `null` in testnet prod

Caused by missing of `native_transfer_address_hash` field in the query, fixed by https://github.com/Magickbase/godwoken-explorer-ui/commit/c5425a1ff0fb6bf8be8bbcb01757b6e05d41a23c
