### ISSUE TITLE
History data of contracts could be updated

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#953]
https://v1.gwscan.com/account/0xbf7b7295f84b4bd2de9d549d047e51c7917dc5e3
Like this contract, its deploy tx and deployer could be stored
![image](https://user-images.githubusercontent.com/7271329/189034422-abb0c736-611b-45fb-967e-be8e75393040.png)

**Comment by zmcNotafraid** [comment]
This contract address can't find it's deployment tx hash from database

**Comment by Keith-CY** [comment]
Got it, this contract is deployed by a factory contract
