### ISSUE TITLE
The native transaction to address is displayed incorrectly

### ISSUE THREAD

**Issue by Dawn-githup** [Magickbase/godwoken_explorer#955]
>> https://v1.betanet.gwscan.com/account/0xc7d2e37c3b38084c0aa2a698965860d7cbceb5b3?tab=transactions

![image](https://user-images.githubusercontent.com/77844990/189072412-8aefc48d-3ca7-4b01-b799-9e5df22bcf12.png)

**Comment by Keith-CY** [comment]
> > > [v1.betanet.gwscan.com/account/0xc7d2e37c3b38084c0aa2a698965860d7cbceb5b3?tab=transactions](https://v1.betanet.gwscan.com/account/0xc7d2e37c3b38084c0aa2a698965860d7cbceb5b3?tab=transactions)
> 
> ![image](https://user-images.githubusercontent.com/77844990/189072412-8aefc48d-3ca7-4b01-b799-9e5df22bcf12.png)

Do you mean that a transaction sending `110 pCKB` to this address but not listed in the receiver's transaction list?

**Comment by Keith-CY** [comment]
Maybe it's caused by incorrectly resolved `to` in the native transfer transaction @zmcNotafraid

**Comment by Dawn-githup** [comment]
> > > > [v1.betanet.gwscan.com/account/0xc7d2e37c3b38084c0aa2a698965860d7cbceb5b3?tab=transactions](https://v1.betanet.gwscan.com/account/0xc7d2e37c3b38084c0aa2a698965860d7cbceb5b3?tab=transactions)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/77844990/189072412-8aefc48d-3ca7-4b01-b799-9e5df22bcf12.png)
> 
> Do you mean that a transaction sent `110 pCKB` to this address but is not listed in the receiver's transaction list?

> > yes,Transaction display is empty;
