### ISSUE TITLE
The "TPS" metric seems inaccurate

### ISSUE THREAD

**Issue by Flouse** [Magickbase/godwoken_explorer#958]
![image](https://user-images.githubusercontent.com/1297478/189472548-3c10e330-573d-4564-a1bd-de197cb8d3f1.png)

**Comment by Keith-CY** [comment]
Fixed in production environments, it was caused by the animation which rounds 0.x to 0

**Comment by Flouse** [comment]
Thank you for being around during the mid-autumn holiday!
