### ISSUE TITLE
Questions about ERC 721 tokens

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#959]
From the collection list api we can know that token `0x821543e1e3923bb6c7efa6e5ebd5f83da3b25cd8` has 32 holders and 32 minted tokens
![image](https://user-images.githubusercontent.com/7271329/189512747-845470d9-33c6-4af7-b845-dd0265354741.png)

But holder list API tells use the token `0x821543e1e3923bb6c7efa6e5ebd5f83da3b25cd8` has only 1 holder who owns all token
![image](https://user-images.githubusercontent.com/7271329/189512762-b1443792-0c83-4cc7-9be9-c442e29f1a7c.png)

Then I queried `token item transfer list` and found there were only 32 transactions and they were all minting transaction
![image](https://user-images.githubusercontent.com/7271329/189512812-dea61e47-19a8-4157-a773-91e32ab964de.png)

So we can conclude that the ERC 721 has minted 32 token items to the same owner address, and none has been transferred. The holder count should be 1

**Comment by Keith-CY** [comment]
Also has a question about token `[0x310a1f73379a658ef0eb9c4e5bd1006a24a5ad79](https://godwoken-explorer-ui-git-erc-721-nervosnet.vercel.app/account/0x310a1f73379a658ef0eb9c4e5bd1006a24a5ad79)`

**Comment by Naupio** [comment]
fixed in stg
```
query {
  erc721_holders(
    input: { contract_address: "0x821543e1e3923bb6c7efa6e5ebd5f83da3b25cd8" }
  ) {
    entries {
      rank
      address_hash
      token_contract_address_hash
      quantity
    }
    metadata {
      total_count
      after
      before
    }
  }

  erc721_udts(
    input: { contract_address: "0x821543e1e3923bb6c7efa6e5ebd5f83da3b25cd8" }
  ) {
    entries {
      id
      name
      contract_address_hash
      eth_type
      holders_count
      minted_count
    }
    metadata {
      total_count
      after
      before
    }
  }

  erc721_erc1155_inventory(
    input: {
      contract_address: "0x821543e1e3923bb6c7efa6e5ebd5f83da3b25cd8"
      limit: 1
    }
  ) {
    entries {
      token_id
      address_hash
      token_contract_address_hash
      value
    }
    metadata {
      total_count
      after
      before
    }
  }
}

{
  "data": {
    "erc721_erc1155_inventory": {
      "entries": [
        {
          "address_hash": "0x3089ea87cd8dc04e0985e0c0da272e399a7c289a",
          "token_contract_address_hash": "0x821543e1e3923bb6c7efa6e5ebd5f83da3b25cd8",
          "token_id": "31",
          "value": "32"
        }
      ],
      "metadata": {
        "after": "g3QAAAACZAACaWRiABS_JGQACHRva2VuX2lkdAAAAARkAApfX3N0cnVjdF9fZAAORWxpeGlyLkRlY2ltYWxkAARjb2VmYR9kAANleHBhAGQABHNpZ25hAQ==",
        "before": null,
        "total_count": 32
      }
    },
    "erc721_holders": {
      "entries": [
        {
          "address_hash": "0x3089ea87cd8dc04e0985e0c0da272e399a7c289a",
          "quantity": "32",
          "rank": 1,
          "token_contract_address_hash": "0x821543e1e3923bb6c7efa6e5ebd5f83da3b25cd8"
        }
      ],
      "metadata": {
        "after": null,
        "before": null,
        "total_count": 1
      }
    },
    "erc721_udts": {
      "entries": [
        {
          "contract_address_hash": "0x821543e1e3923bb6c7efa6e5ebd5f83da3b25cd8",
          "eth_type": "ERC721",
          "holders_count": 1,
          "id": 5799,
          "minted_count": 32,
          "name": "YokaiswapNFT"
        }
      ],
      "metadata": {
        "after": null,
        "before": null,
        "total_count": 1
      }
    }
  }
}
```

**Comment by FrederLu** [comment]
> fixed in stg @FrederLu
> 
> ```
> query {
>   erc721_holders(
>     input: { contract_address: "0x821543e1e3923bb6c7efa6e5ebd5f83da3b25cd8" }
>   ) {
>     entries {
>       rank
>       address_hash
>       token_contract_address_hash
>       quantity
>     }
>     metadata {
>       total_count
>       after
>       before
>     }
>   }
> 
>   erc721_udts(
>     input: { contract_address: "0x821543e1e3923bb6c7efa6e5ebd5f83da3b25cd8" }
>   ) {
>     entries {
>       id
>       name
>       contract_address_hash
>       eth_type
>       holders_count
>       minted_count
>     }
>     metadata {
>       total_count
>       after
>       before
>     }
>   }
> 
>   erc721_erc1155_inventory(
>     input: {
>       contract_address: "0x821543e1e3923bb6c7efa6e5ebd5f83da3b25cd8"
>       limit: 1
>     }
>   ) {
>     entries {
>       token_id
>       address_hash
>       token_contract_address_hash
>       value
>     }
>     metadata {
>       total_count
>       after
>       before
>     }
>   }
> }
> 
> {
>   "data": {
>     "erc721_erc1155_inventory": {
>       "entries": [
>         {
>           "address_hash": "0x3089ea87cd8dc04e0985e0c0da272e399a7c289a",
>           "token_contract_address_hash": "0x821543e1e3923bb6c7efa6e5ebd5f83da3b25cd8",
>           "token_id": "31",
>           "value": "32"
>         }
>       ],
>       "metadata": {
>         "after": "g3QAAAACZAACaWRiABS_JGQACHRva2VuX2lkdAAAAARkAApfX3N0cnVjdF9fZAAORWxpeGlyLkRlY2ltYWxkAARjb2VmYR9kAANleHBhAGQABHNpZ25hAQ==",
>         "before": null,
>         "total_count": 32
>       }
>     },
>     "erc721_holders": {
>       "entries": [
>         {
>           "address_hash": "0x3089ea87cd8dc04e0985e0c0da272e399a7c289a",
>           "quantity": "32",
>           "rank": 1,
>           "token_contract_address_hash": "0x821543e1e3923bb6c7efa6e5ebd5f83da3b25cd8"
>         }
>       ],
>       "metadata": {
>         "after": null,
>         "before": null,
>         "total_count": 1
>       }
>     },
>     "erc721_udts": {
>       "entries": [
>         {
>           "contract_address_hash": "0x821543e1e3923bb6c7efa6e5ebd5f83da3b25cd8",
>           "eth_type": "ERC721",
>           "holders_count": 1,
>           "id": 5799,
>           "minted_count": 32,
>           "name": "YokaiswapNFT"
>         }
>       ],
>       "metadata": {
>         "after": null,
>         "before": null,
>         "total_count": 1
>       }
>     }
>   }
> }
> ```

The interface contract_address`0x821543e1e3923bb6c7efa6e5ebd5f83da3b25cd8` data display is normal, but the `
0x310a1f73379a658ef0eb9c4e5bd1006a24a5ad79`There is duplicate data in the corresponding interface of holder and inventory tab, and the id is 0, 1, 5.

Reference https://gw-explorer.nervosdao.community/token/0x310A1f73379A658EF0eb9c4e5Bd1006A24A5aD79/token-holders

**Comment by FrederLu** [comment]
Verified.
