### ISSUE TITLE
`from_account` is `null` in pending tx list

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#961]
![image](https://user-images.githubusercontent.com/7271329/189839046-54b7de7c-e5d4-4f2a-bd79-9d6d3f04ff9e.png)
https://www.gwscan.com/account/0x53bb26dc8c5efc6c95c37155aca487d1d043436a

In some cases the `from_account` of a pending transaction in the list is `null` and the record disappears after a while, see the tx `0xb915a8...b1814525`

![image](https://user-images.githubusercontent.com/7271329/189839553-682b7956-df63-470c-b4cd-42c6b86731f2.png)

There're two questions

1. it's impossible to have a `null` `from` in a transaction
2. why the record disappears from the list, is it rejected by the node and removed from the mem pool?

**Comment by zmcNotafraid** [comment]
1. For  pending transaction, we can only get from_account_id from rpc.If from_account_id doesn't exist in our account database, so it will return null.
2. For pending transaction, the tx hash is gw_hash. So the 0xb915a8... gw_hash's eth_hash is 0x28c317670ca35123b23029ec3775af7be17597a57f560561de492c39709722b5. https://v1.gwscan.com/zh-CN/tx/0x28c317670ca35123b23029ec3775af7be17597a57f560561de492c39709722b5?search=0x28c317670ca35123b23029ec3775af7be17597a57f560561de492c39709722b5
