### ISSUE TITLE
native transfer address in tx list is incorrect

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#998]
Should use `native transfer address hash`, but `to` is used in fact

**Comment by Keith-CY** [comment]
Fixed by https://github.com/Magickbase/godwoken-explorer-ui/commit/b747852c081eba79aa2ee359eddec72700c66b89

Account has native transfer: https://v1.testnet.gwscan.com/account/0xd1667cbf1cc60da94c1cf6c9cfb261e71b6047f7?search=0xd1667cbf1cc60da94c1cf6c9cfb261e71b6047f7

Please have a review @Dawn-githup

**Comment by Dawn-githup** [comment]
> Fixed by [Magickbase/godwoken-explorer-ui@b747852](https://github.com/Magickbase/godwoken-explorer-ui/commit/b747852c081eba79aa2ee359eddec72700c66b89)
> 
> Account has native transfer: https://v1.testnet.gwscan.com/account/0xd1667cbf1cc60da94c1cf6c9cfb261e71b6047f7?search=0xd1667cbf1cc60da94c1cf6c9cfb261e71b6047f7
> 
> Please have a review @Dawn-githup

> No problem, just add the Method field

**Comment by Keith-CY** [comment]
> > Fixed by [Magickbase/godwoken-explorer-ui@b747852](https://github.com/Magickbase/godwoken-explorer-ui/commit/b747852c081eba79aa2ee359eddec72700c66b89)
> > Account has native transfer: [v1.testnet.gwscan.com/account/0xd1667cbf1cc60da94c1cf6c9cfb261e71b6047f7?search=0xd1667cbf1cc60da94c1cf6c9cfb261e71b6047f7](https://v1.testnet.gwscan.com/account/0xd1667cbf1cc60da94c1cf6c9cfb261e71b6047f7?search=0xd1667cbf1cc60da94c1cf6c9cfb261e71b6047f7)
> > Please have a review @Dawn-githup
> 
> > No problem, just add the Method field

Adding a method name for native transfer is tracked by an independent issue(https://github.com/Magickbase/godwoken_explorer/issues/999) so this one could be closed
