### ISSUE TITLE
Native transfer could have a specific method name

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#999]

**Comment by Keith-CY** [comment]
How about namnig the `Send` because `Transfer` will be mixed with `ERC 20 Transfer` @Dawn-githup

**Comment by Dawn-githup** [comment]
> How about namnig the `Send` because `Transfer` will be mixed with `ERC 20 Transfer` @Dawn-githup

> ok

**Comment by Keith-CY** [comment]
There're two kinds of transactions on the Ethereum
1. transfer native ETH token to another address, called `native transfer`
2. calling a contract method with a `method id/method name`

Now `method id/method name` will be shown in the transaction list but the field is blank if it's a `native transfer`, as the screenshot shows:
![image](https://user-images.githubusercontent.com/7271329/194820942-1a668cfe-a6f3-452a-8424-998427e20608.png)
Page: https://v1.testnet.gwscan.com/account/0x46a23e25df9a0f6c18729dda9ad1af3b6a131160?search=0x46a23e25df9a0f6c18729dda9ad1af3b6a131160

For visual consistency, we'd like to mark `Send` instead of `-` for a `native transfer` transaction but it should be different from other `method id/method name` of `contract call` because there might be a `contract call` having `Send` method.

Maybe we can make the `method` of a `native transfer` dim, non-interactable, etc. Any idea from @Kirl70?

**Comment by Kirl70** [comment]
> There're two kinds of transactions on the Ethereum
> 
> 1. transfer native ETH token to another address, called `native transfer`
> 2. calling a contract method with a `method id/method name`
> 
> Now `method id/method name` will be shown in the transaction list but the field is blank if it's a `native transfer`, as the screenshot shows: ![image](https://user-images.githubusercontent.com/7271329/194820942-1a668cfe-a6f3-452a-8424-998427e20608.png) Page: https://v1.testnet.gwscan.com/account/0x46a23e25df9a0f6c18729dda9ad1af3b6a131160?search=0x46a23e25df9a0f6c18729dda9ad1af3b6a131160
> 
> For visual consistency, we'd like to mark `Send` instead of `-` for a `native transfer` transaction but it should be different from other `method id/method name` of `contract call` because there might be a `contract call` having `Send` method.
> 
> Maybe we can make the `method` of a `native transfer` dim, non-interactable, etc. Any idea from @Kirl70?

My thoughts are the same as yours, tone down the text, non-interactable:

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/106060898/194826013-940d1891-616c-45c7-b718-c5577e3a56b9.png">

The color value of the tone down text is: #999999

**Comment by Keith-CY** [comment]
PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/619
